### ISSUE TITLE
toolbar -> 'fits all' icons missing from toolbar

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#1]
first submission for test ... ;-)

```
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.24992 (Git) AppImage
Build type: Release
Branch: master
Hash: 9332e52d944c1339e3b9a1b5a72dc6edc6d077a8
Python version: 3.9.4
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: Polish/Poland (pl_PL)
```

![obraz](https://user-images.githubusercontent.com/39754351/120901758-07237100-c63d-11eb-9456-80a1f5b6181b.png)
The first two utility icons are missing

**Comment by kaktusus** [comment]
![obraz](https://user-images.githubusercontent.com/39754351/140995375-19850707-2448-475c-a47f-fd01cd093af5.png)


the problem is back

**Comment by luzpaz** [comment]
Forum thread: https://forum.freecadweb.org/viewtopic.php?f=8&t=65257

**Comment by kaktusus** [comment]
> ```
> OS: Debian GNU/Linux bookworm/sid (XFCE/xfce)
> Word size of FreeCAD: 64-bit
> Version: 0.20.26202 (Git) AppImage
> Build type: Release
> Branch: master
> Hash: ca6d49d080dea0abc23d954743eca7c46f33469b
> Python version: 3.9.7
> Qt version: 5.12.9
> Coin version: 4.0.0
> OCC version: 7.5.3
> Locale: Polish/Poland (pl_PL)
> ```
> 
> the issue has been resolved

I wrote here that the problem was solved, and after another release it appeared again

I will check the suggestions in the forum.

Are you all right?

**Comment by kaktusus** [comment]
problem solved.
In order to display icons correctly you should use parameter: Bitmaps/Theme/ThemeSearchPaths, and set it to false.

Written in the forum thread you provided.

**Comment by luzpaz** [comment]
Maybe we should let theme creators know that this is an issue?

**Comment by kaktusus** [comment]
This is a good idea,
but the problem must be known,
because someone has provided a suitable control parameter in FreeCAD.
