### ISSUE TITLE
homepage.po

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#10]
file is missing the string `This project is supported by:`
homepage footer

![obraz](https://user-images.githubusercontent.com/39754351/121229134-e43bcb80-c88d-11eb-87bd-93ff448fb506.png)

https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=This%20project%20is%20supported%20by:

**Comment by luzpaz** [comment]
@yorikvanhavre how do we run translation on the webpage? Is this documented somewhere?

**Comment by kaktusus** [comment]
There are new strings to translate, but I don't see this one ...

**Comment by kaktusus** [comment]
something's going on

;-)

**Comment by luzpaz** [comment]
@yorikvanhavre ping

**Comment by kaktusus** [comment]
@luzpaz
Yorik prepared strings for translation, but omitted the first one

**Comment by kaktusus** [comment]
I am refreshing the topic due to an announcement from the forum

https://forum.freecadweb.org/viewtopic.php?style=4&f=21&t=68402

![obraz](https://user-images.githubusercontent.com/39754351/166133261-b6baca6d-771a-405a-aa87-dde6135fe4ec.png)


All texts from the home page are currently translated.
However, there are two strings without translations.

one submitted earlier:
`This project is supported by:` - no string in Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=This%20project%20is%20supported%20by:

and

`(current stable release)` - no string in Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=(current%20stable%20release)

**Comment by kaktusus** [comment]
Error in FreeCAD Wiki link

https://crowdin.com/translate/freecad/27908/en-pl#6596144


Have some of the links gone out of date?
Pages are loading after redirects.

https://crowdin.com/translate/freecad/27908/en-pl#6596148

**Comment by kaktusus** [comment]
Proposal to improve links so that appropriate language versions of pages can be displayed.
E.g. by adding them to a string with translation.

https://crowdin.com/translate/freecad/27908/en-pl#6511858

https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Wersja%200.

**Comment by kaktusus** [comment]
Homepage
![image](https://user-images.githubusercontent.com/39754351/174422274-49e4ae2f-5212-44b7-ad22-69ed66b6a951.png)

1. `Release 0.20 - June 2022`
2.  `(current stable release)`


Download tab
![image](https://user-images.githubusercontent.com/39754351/174422316-1717cacc-cf2f-4c39-abed-336e8acbf150.png)

3.  `Current stable version: 0.20`
4.  `This project is supported by:`

All in all, this needs no comment.
However, I can joke - probably no one was shocked that a new stable version came out
it could have been prepared earlier.
;-)

**Comment by kaktusus** [comment]
@yorikvanhavre 
I will ask you to update the homepage translations and source translations for FreeCAD.
;o)

**Comment by luzpaz** [comment]
@yorikvanhavre we need another push

**Comment by yorikvanhavre** [comment]
sorry guys. doing it right now!

**Comment by yorikvanhavre** [comment]
https://github.com/FreeCAD/FreeCAD-Homepage/commit/434fa63025b5e25fbd2cad722d90c87adbdd36b7

**Comment by kaktusus** [comment]
The translated homepage is starting to look really good.
It makes us happy.

However, it still needs polishing.
For example, the highlighted button leads to an old page.
![obraz](https://user-images.githubusercontent.com/39754351/187980477-396e763d-6de0-4e98-a7be-1b6b052cc544.png)

I also found one text with which there is still a problem.
![obraz](https://user-images.githubusercontent.com/39754351/187980807-cc83e254-714f-4e57-aa65-301ca0ecde5c.png)

**Comment by luzpaz** [comment]
What's left to do?

**Comment by kaktusus** [comment]
Please update home page translations
currently it does not look good
translated text is missing in many places.

**Comment by luzpaz** [comment]
@yorikvanhavre :point_up_2:

**Comment by yorikvanhavre** [comment]
Done with 3a08907

**Comment by kaktusus** [comment]
This thread is so old that, I think everyone is used to it.
So I'm closing it and will generate its descendants.
