### ISSUE TITLE
FreeCAD → File (Toolbar) / Edit mode (component)

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#102]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.26498 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 1895593)
Hash: 18955931c7f0926a4cd9d2719be5a433b49ae56e
Python version: 3.9.7
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.3
Locale: Polish/Poland (pl_PL)
```

Tooltips do not have translations in the GUI.

![obraz](https://user-images.githubusercontent.com/39754351/144759905-da7e7b13-36c9-4921-b613-c169f4cad28c.png)
`Dafault mode` - no string in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Dafault%20mode

![obraz](https://user-images.githubusercontent.com/39754351/144759960-d95f9b10-186e-4460-b04b-b3766073398d.png)
`Transform mode` - the string from Crowdin does not apply to this case
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Transform%20mode

![obraz](https://user-images.githubusercontent.com/39754351/144760005-3a715d03-23cf-44ba-975d-3ca49ea3c331.png)
`Cutting mode` - no string in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Cutting%20mode

![obraz](https://user-images.githubusercontent.com/39754351/144760042-d30fdee3-d7fa-4686-9012-d34b190ed96e.png)
`Color mode` - no string in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Color%20mode

**Comment by luzpaz** [comment]
Code is at  
* https://github.com/FreeCAD/FreeCAD/blob/175ceb2d12e69c81017fbb34c4e20d9eaa4fd5cc/src/Gui/Application.h#L244-L247
* https://github.com/FreeCAD/FreeCAD/blob/175ceb2d12e69c81017fbb34c4e20d9eaa4fd5cc/src/Gui/Workbench.cpp#L610

**Comment by luzpaz** [comment]
@kaktusus I don't see tooltips when i hover over the drop-down menus on either the AppImage or Snap edge build.

**Comment by kaktusus** [comment]
I prepared a short video for you, I hope you can see something.

https://vimeo.com/661623922

**Comment by luzpaz** [comment]
Oh, sorry. I didn't understand that it was on the toolbar not the dropdown menu :blush:

**Comment by luzpaz** [comment]
Ok, looks like the tooltips get pulled from an enum
https://github.com/FreeCAD/FreeCAD/blob/d6ad9f50bc67a028f460ed1c378e3550730357bb/src/Gui/ViewProvider.h#L426-L429

Context: 
* https://github.com/FreeCAD/FreeCAD/blob/175ceb2d12e69c81017fbb34c4e20d9eaa4fd5cc/src/Gui/Application.h#L244-L247
* https://github.com/FreeCAD/FreeCAD/blob/175ceb2d12e69c81017fbb34c4e20d9eaa4fd5cc/src/Gui/Workbench.cpp#L610

@chennes sorry to ask but how do translate strings that in enum's again :blush: (I failed to document this on the wiki, sorry to bug you!)

**Comment by kaktusus** [comment]
The problem still persists ...

**Comment by chennes** [comment]
Yes, the code for these tooltips is wrong: it is appending the word "mode" to the end of the mode name during dynamic translation, but never does that for the translation string extraction. I think the best way to handle this is to create a new translated string that's something like "Change to user edit mode: " and prepend that to the mode name. I don't think we can just separately translate the word "mode" by itself, because in some languages that won't give a grammatical result.

**Comment by kaktusus** [comment]
Such incorrect code that builds labels on the fly probably also causes problems elsewhere (#24, #25, #26, #27, #28, #29)
Thanks for the explanation.

**Comment by chennes** [comment]
Yes, all of those are actually the same issue. What if we just drop the name of the transform, and stick to just "Parameters"? That bypasses this issue altogether.

**Comment by kaktusus** [comment]
The description will be less informative.
