### ISSUE TITLE
  FreeCAD → Edit → Preferences → Addon Manager → Addon manager options

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#103]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.26683 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0388fbc)
Hash: 0388fbc98d49d874fb341b9037a743bc691d501f
Python version: 3.9.7
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.3
Locale: Polish/Poland (pl_PL)
```

New opportunities generate new problems ...
In the GUI, the translated option label is not displayed.

![obraz](https://user-images.githubusercontent.com/39754351/146949236-6589dbf1-71c7-4090-856e-a39f313db968.png)

`Addon Manager`  - the string from Crowdin does not apply to this case
https://crowdin.com/translate/freecad/32150/en-pl#6576000

`Addon manager options`  - The string is present in Crowdin, but is not displayed in the GUI.
https://crowdin.com/translate/freecad/32150/en-pl#6576124

`Automatically check for updates at start (requires GitPython)`  - The string is present in Crowdin, but is not displayed in the GUI.
https://crowdin.com/translate/freecad/32150/en-pl#6576680

`Cache update frequency`  - no string in Crowdin.
`Custom repositories (one per line):`  - The string is present in Crowdin, but is not displayed in the GUI.
https://crowdin.com/translate/freecad/32150/en-pl#6576116

`Proxy`  - The string is present in Crowdin, but is not displayed in the GUI.
https://crowdin.com/translate/freecad/32150/en-pl#6576684

`No proxy`   The string is present in Crowdin, but is not displayed in the GUI.
https://crowdin.com/translate/freecad/32150/en-pl#6576686

`User system proxy`  - The string is present in Crowdin, but is not displayed in the GUI.
https://crowdin.com/translate/freecad/32150/en-pl#6576688

`User-defined proxy:`  - Crowdin incompatibility
https://crowdin.com/translate/freecad/32150/en-pl#6576690

Tooltip:
`If this option is selected, when launching the Addon Manager,
installed addons will be checked for available updates
(this requires the GitPython package installed on your system)`  - The string is present in Crowdin, but is not displayed in the GUI.
https://crowdin.com/translate/freecad/32150/en-pl#6576678

`You can use this window to specify additional addon repositories
to be scanned for available addons`   - The string is present in Crowdin, but is not displayed in the GUI.
https://crowdin.com/translate/freecad/32150/en-pl#6584428

![obraz](https://user-images.githubusercontent.com/39754351/146949802-c3371406-e775-42cf-a8e4-e0dafa83c129.png)

`Manual (no automatic updates)`  - no string in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Manual%20(no%20automatic%20updates)

`Daily`  - no string in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Daily

`Weekly`  - no string in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Weekly

**Comment by luzpaz** [comment]
Hi @chennes do we need to add `src/Mod/AddonManager/AddonManagerOptions.ui` to some file so it gets parsed by lupdate?

**Comment by chennes** [comment]
No, all of those strings are extracting just fine. When was the last time CrowdIn was updated?

**Comment by kaktusus** [comment]
![obraz](https://user-images.githubusercontent.com/39754351/147858348-b01591ba-7a57-457a-8f3e-e444073c63c2.png)
recent activity at Crowdin has contributed nothing to this topic

**Comment by chennes** [comment]
Maybe translation only works when it's compiled into a resource file, and not loaded directly from the file on disk. I will do some experimentation.

**Comment by kaktusus** [comment]
I found an anomaly, in the AddonManager.ts file downloaded from Crowdin.

When loaded into QT Linguist (linux), the string `Delete cached version of this README and re-download`, is marked as incorrect.
The comment "The translation does not contain the necessary %n/%Ln tag."

Is it possible that this string is incorrectly exported from Crowdin, it is a compound string - with a language variation.

**Comment by chennes** [comment]
I think I have isolated the problem: it turns out that Qt's "lupdate" script does not correctly process UI files unless there is also at least one "source" file (e.g. a C++ header file of some kind). That source file can be empty, but it has to exist! So those translated strings all have the wrong context, which is why they aren't showing up. The fix for me is to either have a single dummy source file, or to modify the updatets script to detect this condition and modify the way it calls pylupdate.

**Comment by kaktusus** [comment]
it seems easier to give the wolf the lamb ;-)

Spreadsheet.ts contains two similar strings causing error messages in Qt Linguist.

**Comment by chennes** [comment]
https://github.com/FreeCAD/FreeCAD/pull/5318

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28793 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 5386d4e)
Hash: 5386d4ed864cd03edd026e1d3d128cccedf568df
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

All works as it should.

![obraz](https://user-images.githubusercontent.com/39754351/167247473-ce1fe5bc-4a3c-4caf-8430-e281b43178e4.png)
