### ISSUE TITLE
HTML in translatable strings

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#105]
The selected strings containing control characters have been translated by Yorik.

They are not consistent with strings in Crowdin.
Question - was this an experiment, or should we follow the modified content in the translation proposals?

Example:

Source string
`&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Check this to make FreeCAD start with a new blank document. Location in preferences: &lt;span style=&quot; font-weight:600;&quot;&gt;General &amp;gt; Document &amp;gt; Create new documentat startup&lt;/span&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;`

Yorik's translation proposal
`{[=-lt;-=]}html{[=-gt;-=]}{[=-lt;-=]}head/{[=-gt;-=]}{[=-lt;-=]}body{[=-gt;-=]}{[=-lt;-=]}p{[=-gt;-=]}Check this to make FreeCAD start with a new blank document. Location in preferences: {[=-lt;-=]}span style={[=-quot;-=]} font-weight:600;{[=-quot;-=]}{[=-gt;-=]}General {[=-amp;gt;-=]} Document {[=-amp;gt;-=]} Create new documentat startup{[=-lt;-=]}/span{[=-gt;-=]}{[=-lt;-=]}/p{[=-gt;-=]}{[=-lt;-=]}/body{[=-gt;-=]}{[=-lt;-=]}/html{[=-gt;-=]}`

filter for all strings:
all strings: https://crowdin.com/translate/freecad-addons/32152/en-pl?filter=basic&value=0#q=&lt;

If the link doesn't work properly, enter the string into the Crowdin search engine:
`&lt;`

**Comment by yorikvanhavre** [comment]
These come from the fact that some QT UI strings are encoded in HTML, which is pretty annoying on crowdin. I think we shoukd systematically remove all HTML from the UI files (only use plain text everywhere there is a text to translate)...

**Comment by luzpaz** [comment]
I imagine that would be a crap-ton of strings that would need to be retranslated :face_with_head_bandage:

**Comment by Kuzma30** [comment]
Crowdin show 226 strings with "html".

**Comment by chennes** [comment]
Just in BIM, or everywhere in FreeCAD?

**Comment by kaktusus** [comment]
In various WB

**Comment by yorikvanhavre** [comment]
Not sure what to do here... Maybe we should simply start trying to turn html strings to plain text ones, and do it bit by bit, as we see them?

**Comment by kaktusus** [comment]
No progress on the topic. :cry: 
New strings continue to appear with html tags. :sob:

**Comment by chennes** [comment]
In FreeCAD itself I see 87 strings with `&lt;` in them -- I actually expected far more. Is that really all of them?

**Comment by kaktusus** [comment]
Above is quoted a much larger result.

**Comment by chennes** [comment]
OK, I figured it out. So clearly, a lot of these strings are just strings, and HTML was enabled by someone who didn't know the consequences to translators. But some of them genuinely take advantage of the HTML, so I am going to leave those alone for now.

**Comment by kaktusus** [comment]
Right.
It is important to consistently follow the path that Yorik talked about to eliminate these tags in the future.
Also, these formatting works at all?

**Comment by kaktusus** [comment]
I close this ticket, for today there is a very big improvement,
The manual for developers also has pertinent notes on the subject.
https://github.com/FreeCAD/DevelopersHandbook/blob/master/technical/translation.md


However, there is still a lot of work to be done. :wink:
