### ISSUE TITLE
Sketcher  → Combo view (panels) → Tasks (tab)

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#106]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.26720 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 7bca26e)
Hash: 7bca26e7c14d4d43374ff7e0c8582735b249cbfd
Python version: 3.9.9
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.3
Locale: Polish/Poland (pl_PL)
```
New opportunities generate new problems ...
In the GUI, the translated option label is not displayed.

![obraz](https://user-images.githubusercontent.com/39754351/148083424-7fe32aab-3eb0-42f3-9da1-21e6513782b4.png)

1. `Under constrained` - no string in Crowdin.
 https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Under%20constrained
1A. `2 DoF` - no string in Crowdin.
 https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=DoF
2.  `Filter:` - The string is present in Crowdin, but is not displayed in the GUI.
 https://crowdin.com/translate/freecad/569/en-pl#194697
3.  `All` - The string is present in Crowdin, but is not displayed in the GUI.
 https://crowdin.com/translate/freecad/569/en-pl#194698
4.  `Select Multiple` - no string in Crowdin.
 https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Select%20Multiple
5.  `Show Listed` - no string in Crowdin.
 https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Show%20Listed
6.  `Hide Listed` - no string in Crowdin.
 https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Hide%20Listed
7.  `Restrict Visibility` - no string in Crowdin.
 https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Restrict%20Visibility
8. 

![obraz](https://user-images.githubusercontent.com/39754351/148085456-18b06bc6-9e69-426e-b616-0a7d308a90c5.png)

`Constrain widget settings` - no string in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Constrain%20widget%20settings

`List control` - no string in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=List%20control

`Extended information` - The string is present in Crowdin, but is not displayed in the GUI.
https://crowdin.com/translate/freecad/569/en-pl#6578456

`Hide internal alignment` - The string is present in Crowdin, but is not displayed in the GUI.
https://crowdin.com/translate/freecad/569/en-pl#6578452

`3D view control` - no string in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=3D%20view%20control

`Show only filtered constraints` - no string in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Show%20only%20filtered%20constraints

`Cancel` ... ;-p

**Comment by kaktusus** [comment]
next occurrence

![obraz](https://user-images.githubusercontent.com/39754351/148360691-3d372ea9-ac59-472b-ab71-8e73c9a1bf28.png)


`Fully constrained` - No corresponding string in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Fully%20constrained

I expect that all solver strings will require at least checking.

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28793 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 5386d4e)
Hash: 5386d4ed864cd03edd026e1d3d128cccedf568df
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

After recent updates, the reported issues have been resolved.
However, I found something else ...
Should I create a new ticket?


See comment.
https://crowdin.com/translate/freecad/569/en-pl?filter=basic&value=0#6597724

**Comment by donovaly** [comment]
Can you please open an issue in FreeCAD/FreeCAD?
Please also report there the issue that in the screenshot in https://github.com/FreeCAD/FreeCAD-translations/issues/106#issuecomment-1006409186 there is an untranslated "Close" button.

**Comment by kaktusus** [comment]
The issue of untranslated Close button labels _#149_ should already be resolved _(https://github.com/FreeCAD/FreeCAD/pull/6882 https://github.com/FreeCAD/FreeCAD/pull/6883)_ I'm waiting for a new release to check this.

**Comment by kaktusus** [comment]
New ticket opened in a different section of the repository at @donovaly's request

https://github.com/FreeCAD/FreeCAD/issues/6893
