### ISSUE TITLE
README: Add section on testing your own translations

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-translations#108]
Currently this is what the README shows in the section for testing ones own translations:

![Screenshot_20220414_185121](https://user-images.githubusercontent.com/4140247/163490227-a6c6ad51-27d3-4dea-bbd0-11be3d07c65d.png)

CC @kaktusus

Hi kaktusus, I forget where in the forum there was a write up of how to do this. Would you be open to improving the README?

**Comment by kaktusus** [comment]
Yes, I'm happy to help, 

I'll prepare something. 

Right now, for quick reference, I can offer this:
there   https://wiki.freecadweb.org/Polish_Translation#FreeCAD_aktualna_wersja  is a description in the Polish part of the wiki for translator guidelines. The text is in Polish but the shell commands are multilingual. ;)

**Comment by kaktusus** [comment]
Once again I have completed the test section, this time adding a comprehensively automated bash script.

   *- automatically converts any number of source files - 1 ... 3 ... 8 ...
    - adjusts the file name to the required criteria
    - independently recognizes the language of the source file
    - moves converted files to the appropriate FreeCAD folder*


If I can find out where FreCAD saves its variables it will be possible to add a small improvement to the script.
Then it'll be super automatic ;-D

**Comment by kaktusus** [comment]
Can this ticket be closed?

**Comment by chennes** [comment]
I think we can close this since the README looks great to me. If there are more specific changes needed we can open new Issues later on.
