### ISSUE TITLE
FreeCAD → Edit → Preferences ... → General / Preference packs / Manage...

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#113]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28717 (Git) AppImage
Build type: Release
Branch: (HEAD detached at fee4046)
Hash: fee404602bee4e1d576cb6f979a8623c63c6815a
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
...
```

Labels and tooltips do not have translations in the GUI.

![obraz](https://user-images.githubusercontent.com/39754351/163799794-fe79181a-5118-4baa-b65e-c91117f5a0f6.png)

1.  `Manage Preference Packs` - no string in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Manage%20Preference%20Packs

2.  `Open Addon Manager...` - no string in Crowdin
    [Crowdin link](https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Open%20Addon%20Manager...)

3.  `Built-In Preference Packs` - no string in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Toggle%20visibility%20of%20builr-in%20prference%20pack
    If this Package is a fixed item, it may be possible to display a translated label.

4.  `Toggle visibility of built-in preference pack` - no string in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Toggle%20visibility%20of%20built-in%20preference%20pack

**Comment by chennes** [comment]
These are all fixed now (note you have a typo in the search for #3).

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28793 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 5386d4e)
Hash: 5386d4ed864cd03edd026e1d3d128cccedf568df
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

All works as it should.

![obraz](https://user-images.githubusercontent.com/39754351/167247079-cb3a7beb-5c4e-4ed4-986d-04953346b612.png)
