### ISSUE TITLE
  FreeCAD → Tools → Addon manager [AddonsInstaller]

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#114]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28717 (Git) AppImage
Build type: Release
Branch: (HEAD detached at fee4046)
Hash: fee404602bee4e1d576cb6f979a8623c63c6815a
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
...
```

Labels do not have translations in the GUI.

![obraz](https://user-images.githubusercontent.com/39754351/163804255-fcfc7b12-2f3f-4f43-b0ab-35d60a21a29f.png)

1.  `Addon successfully installed.` - no string in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Addon%20successfully%20installed.

2.  `Check for updates` - no string in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Check%20for%20updates

![obraz](https://user-images.githubusercontent.com/39754351/163804886-5072bc2c-4455-4ca3-8953-141a652a9d45.png)

1. `Apply {} update(s)`
    For one occurrence, the translated label is displayed correctly. For more occurrences, the untranslated label is displayed.
    https://crowdin.com/translate/freecad/32150/en-pl#6595685

2. `Close` ...???
    There is a global problem in displaying translated labels for this button group ...

    Here, the translated label display is working correctly!

**Comment by luzpaz** [comment]
@chennes [git blame](https://github.com/FreeCAD/FreeCAD/blame/master/src/Mod/AddonManager/AddonManager.ui#L120) shows 'Check for updates' was touched by you 4 months ago. So it's curious why this isn't in crowdin?

**Comment by chennes** [comment]
The last two things I can explain: for 1), I was experimenting with Qt Linguist's pluralization function -- it appears to not work, at least not in that case. For 2), I am not using a QButtonBox there, so if the problem is with that type of widget, this is simply a manually-created button with the string "Cancel" in it, so it just works like all the other buttons.

As for the other two items: I don't have an explanation for why that isn't working right, since obviously most of the AM is being translated fine. I'll try to take a closer look later this week.

**Comment by chennes** [comment]
This should now be fixed in CrowdIn, there was a bug in the translation extraction script.

**Comment by kaktusus** [comment]
That's good news, I'll test it as soon as I'm done with the translation.
I hope that the bug has been permanently fixed, and will not bother you again.

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28793 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 5386d4e)
Hash: 5386d4ed864cd03edd026e1d3d128cccedf568df
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```
After recent updates, the reported issues have been resolved.
However, I found something else ...
Should I create a new ticket?

![obraz](https://user-images.githubusercontent.com/39754351/167246888-2a55c604-3dac-4125-9ae2-696e4ca73224.png)

**Comment by chennes** [comment]
Yes, if you can create a separate ticket for that, and assign it to me (if your permissions allow it), that would be great. I'll try to get to that on Monday.

**Comment by kaktusus** [comment]
I have prepared a new ticket. I can't assign you to it.
