### ISSUE TITLE
FreeCAD → Edit → Preferences ... → Addon Manager / Addon manager options

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#116]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28717 (Git) AppImage
Build type: Release
Branch: (HEAD detached at fee4046)
Hash: fee404602bee4e1d576cb6f979a8623c63c6815a
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
...
```

FreeCAD has a new options, whose labels and tooltips and do not have translations in the GUI.

![obraz](https://user-images.githubusercontent.com/39754351/163810400-46329ae9-0a86-411a-81b4-43b0885db4de.png)

![obraz](https://user-images.githubusercontent.com/39754351/163810103-07c215e5-23fa-4b7b-b8fe-629903b7a324.png)

![obraz](https://user-images.githubusercontent.com/39754351/163810185-bc74b122-d4de-4dee-a22d-9439573618f7.png)

Entire panel including tab name to be improved ...

1.  `Addon manager options` - the string is in Crowdin
    https://crowdin.com/translate/freecad/32150/en-pl#6576124

2. to be completed ...

**Comment by chennes** [comment]
@yorikvanhavre and I are working on resolving a bug with the `src/Tools/updatets.py` translation extraction script: I expect that resolution to fix this issue.

**Comment by chennes** [comment]
The missing strings issues have been resolved.

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28793 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 5386d4e)
Hash: 5386d4ed864cd03edd026e1d3d128cccedf568df
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```


All works as it should.

![obraz](https://user-images.githubusercontent.com/39754351/167245045-d99d1e92-6b73-4dd8-9e4d-31a624501736.png)
