### ISSUE TITLE
View Properties window not fully translated.

### ISSUE THREAD

**Issue by Kuzma30** [FreeCAD/FreeCAD-translations#118]
Unexpectedly failed to take a screenshot when a menu item is active. 
Therefore, I will describe in words. In the SpreadSheet menu, the last 2 items are not translated
![SpreadSheet1](https://user-images.githubusercontent.com/1382812/164261984-4f709238-7331-475b-ba9e-b8e2fe9f92bb.png)
There are also untranslated words on the View tab.

**Comment by kaktusus** [comment]
confirm

```
[code]
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28717 (Git) AppImage
Build type: Release
Branch: (HEAD detached at fee4046)
Hash: fee404602bee4e1d576cb6f979a8623c63c6815a
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
[/code]
```

![obraz](https://user-images.githubusercontent.com/39754351/164281690-747cc765-8f09-4677-8b49-b03689f6b3fb.png)

`Alignment` - the string from Crowdin does not apply to this case
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=alignment

`Styles`  - no string in Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Styles

we already have a similar submission #62

**Comment by Kuzma30** [comment]
Confirm with menu. But screenshot show other untranslated tests.

**Comment by kaktusus** [comment]
Alex if you mean the View Properties window, then this is a global issue.
I have not reported it so far.

**Comment by kaktusus** [comment]
Can these be **App::Property** objects?

**Comment by Kuzma30** [comment]
I don't know

**Comment by luzpaz** [comment]
@donovaly we need more emphasis on translations before release. Can you make an announcement?

**Comment by kaktusus** [comment]
> 

I've been waiting for this decision for probably a year.

Problems instead of decreasing are still increasing ... Until some time there was a lack of uniform guidelines.
Until now, new functionalities are created bypassing the translation mechanism. This generates a lot of problems and additional work.

I think it's worth thinking about how to avoid problems with lack of translations in the future. And take steps to reduce the number of problems.

;-)

**Comment by donovaly** [comment]
> @donovaly we need more emphasis on translations before release. Can you make an announcement?

What should I do?
I am currently traveling for work and have no time right now. Please bring this to the developer's forum section. Furthermore @yorikvanhavre can you please have a look at this too?

**Comment by luzpaz** [comment]
You could boost this effort https://forum.freecadweb.org/viewtopic.php?f=21&t=68402

**Comment by donovaly** [comment]
> You could boost this effort https://forum.freecadweb.org/viewtopic.php?f=21&t=68402

Thanks for stepping in!

**Comment by chennes** [comment]
These are being translated now.
