### ISSUE TITLE
Part Design → Preferences / Shape appearance tab

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#12]
```
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.25025 (Git) AppImage
Build type: Release
Branch: master
Hash: fb8b21ec43dca706a4aa2d63d59a4fb79f050369
Python version: 3.9.4
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: Polish/Poland (pl_PL)
```
Further irregularities regarding Part Design WB. This time in the configuration window.

![obraz](https://user-images.githubusercontent.com/39754351/121687848-1aae5c00-cac3-11eb-83e9-6ee2dcaa99c0.png)
![obraz](https://user-images.githubusercontent.com/39754351/121688125-62cd7e80-cac3-11eb-82e8-c3976a2772bc.png)
The default color for new vertices
![obraz](https://user-images.githubusercontent.com/39754351/121688271-8c86a580-cac3-11eb-8e08-01ad34daf765.png)
The default size for new vertices
![obraz](https://user-images.githubusercontent.com/39754351/121688431-bcce4400-cac3-11eb-8120-123e7ac2ac92.png)
The font size of bounding boxes in the 3D view
![obraz](https://user-images.githubusercontent.com/39754351/121688578-e8512e80-cac3-11eb-88b2-d18ed2ed389c.png)
Text color for document annotations

![obraz](https://user-images.githubusercontent.com/39754351/121688797-22bacb80-cac4-11eb-8e9d-776d4d8fa1df.png)

Button labels do not have translations displayed. Interestingly, when I choose another language GUI for example French these labels are translated.
![obraz](https://user-images.githubusercontent.com/39754351/121690149-c35dbb00-cac5-11eb-8581-84a82a0bcd10.png)

This is probably the last submission for Part Design WB.

**Comment by luzpaz** [comment]
It's weird that code that is from the Part WB that is called from PartDesign WB is not getting translated. @kaktusus can you do me a favor, restart FreeCAD and open Part WB and see what translations aren't exposed to the UI ?

**Comment by kaktusus** [comment]
I am and I read your message ...
I will immediately do what you asked ;-)

**Comment by kaktusus** [comment]
![obraz](https://user-images.githubusercontent.com/39754351/121695122-0bcba780-cacb-11eb-8bd0-10992a04d70f.png)
![obraz](https://user-images.githubusercontent.com/39754351/121695842-be9c0580-cacb-11eb-8771-c43755fbf240.png)
split submenu
![obraz](https://user-images.githubusercontent.com/39754351/121696099-0327a100-cacc-11eb-9521-9999fbe381cc.png)
create projection on surface
![obraz](https://user-images.githubusercontent.com/39754351/121696449-61ed1a80-cacc-11eb-90ff-ddce574ae640.png)
Attachment
![obraz](https://user-images.githubusercontent.com/39754351/121696784-b5f7ff00-cacc-11eb-801b-72720c6036cd.png)

Measure menu
![obraz](https://user-images.githubusercontent.com/39754351/121695418-51887000-cacb-11eb-8b23-68c5baaaf6f3.png)

**Comment by kaktusus** [comment]
Now I'm going to successively check Crowdin looking for strings from my screenshots

**Comment by luzpaz** [comment]
Wow, wasn't expecting all that extensive work! Ok.. thank you!

**Comment by kaktusus** [comment]
> Wow, wasn't expecting all that extensive work! Ok.. thank you!

It's obvious to me to help each other and not waste time. Then the work will move much faster.
Your time is more valuable than mine because you have different skills.
I can be a tool in your hands.  ;-)

**Comment by kaktusus** [comment]
> Case in point "Shape appearance" is from the `src/Mod/Part` https://github.com/FreeCAD/FreeCAD/blob/82211e0e76330415ffe23bcc61216c9d6f3c9cef/src/Mod/Part/Gui/DlgSettingsObjectColor.ui#L14

The source of the code you showed indicates that the code is not designed to handle translation, right?
