### ISSUE TITLE
Path → message during startup

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#120]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28717 (Git) AppImage
Build type: Release
Branch: (HEAD detached at fee4046)
Hash: fee404602bee4e1d576cb6f979a8623c63c6815a
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

 - no strings in Crowdin

![obraz](https://user-images.githubusercontent.com/39754351/164895503-7352995e-6597-4953-8ea1-6dcf43a3c63b.png)

https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=The%20currently%20selected

https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=CNC%20machines%20require

**Comment by luzpaz** [comment]
@Russ4262 can you check if the translation code for this is sound?
https://github.com/FreeCAD/FreeCAD/blob/553554f93654acfbe14f4629ef750a52df483cb3/src/Mod/Path/InitGui.py#L270-L273

**Comment by Kuzma30** [comment]
msg = translate("Path","The currently selected unit schema: \n     '{current_schema}'\n Does not use 'minutes' for velocity values. \n \nCNC machines require feed rate to be expressed in \nunit/minute. To ensure correct gcode: \nSelect a minute-based schema in preferences.\nFor example:\n    'Metric, Small Parts & CNC'\n    'US Customary'\n    'Imperial Decimal'")
without f on the start and last comma it recognize by lupdate.

**Comment by Kuzma30** [comment]
ping @luzpaz

**Comment by Russ4262** [comment]
@luzpaz 
My initial thought is no.  I created a PR to demonstrate how the translated message should be constructed *according to my understanding*.  However, I defer to project managers and their guidance.

**Comment by kaktusus** [comment]
Of course, you can always rely on me.

I really like the new labels, they let me know that I have to review the submission.

**Comment by Kuzma30** [comment]
@luzpaz @Russ4262 
After big update of .ts files there is no string on crowdin
https://crowdin.com/translate/freecad/6766/en-uk?filter=basic&value=3#q=unit%20schema

**Comment by kaktusus** [comment]
> @luzpaz @Russ4262 After big update of .ts files there is no string on crowdin https://crowdin.com/translate/freecad/6766/en-uk?filter=basic&value=3#q=unit%20schema


Aleks you searched in the Arch module. I corrected it, but it doesn't change anything ...
https://crowdin.com/translate/freecad/all/en-uk?filter=basic&value=3#q=unit%20schema

**Comment by Kuzma30** [comment]
https://crowdin.com/translate/freecadtest/all/en-uk?filter=basic&value=0#q=unit%20sche

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28945 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0fb7cd9)
Hash: 0fb7cd9758d850f536d571cc094c9833fee18fff
Python 3.9.13, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```


Fixed.


![obraz](https://user-images.githubusercontent.com/39754351/170874264-9498e6b9-d321-4f43-8af5-e9eb2102bf21.png)
