### ISSUE TITLE
Spreadsheet → context menu

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#121]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28717 (Git) AppImage
Build type: Release
Branch: (HEAD detached at fee4046)
Hash: fee404602bee4e1d576cb6f979a8623c63c6815a
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

![obraz](https://user-images.githubusercontent.com/39754351/164985523-ccb475c2-d878-4ba8-81fd-7cf6f9a76055.png)

1.  `Recompute` - no string in Crowdin
    https://crowdin.com/translate/freecad/27907/en-pl?filter=basic&value=0#q=recompute

2. `Bind...` - no string in Crowdin
   [Crowdin link](https://crowdin.com/translate/freecad/27907/en-pl?filter=basic&value=0#q=Bind...)

3. `Configuration table...` - no string in Crowdin
    [Crowdin link](https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Configuration%20table...)

4. `Merge cells` - the string is found in Crowdin
    https://crowdin.com/translate/freecad/27907/en-pl#6498227

6. `Split cells` - no string in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Split%20cells

8. `Cut` - the string from Crowdin does not apply to this case
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Cut

10. `Copy` - the string from Crowdin does not apply to this case
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Copy

12. `Paste` - the string from Crowdin does not apply to this case
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Paste

14. `Delete` - the string is found in Crowdin
    https://crowdin.com/translate/freecad/27907/en-pl#6591257

**Comment by Kuzma30** [comment]
You can test himself with linguist tools. If you run fixed (3 days ago) script updatets.py in src/Tools directory you can see this Texts in .ts file. We need wait for updating master branch and crowdin server :)

**Comment by Kuzma30** [comment]
@luzpaz 
Can you run script and make commit with result's?

**Comment by kaktusus** [comment]
[105 strings](https://crowdin.com/translate/freecad/all/en-pl#h=cdb8f3ce46a1201af43d9cc84ed8aa4f1256332) were added to the project [FreeCAD](https://crowdin.com/project/freecad)

This link hides the latest Crowdin update, but I guess something went wrong ...
Strings that have been (supposed to be) added are not available to translators.

**Comment by luzpaz** [comment]
I can't make commits. @yorikvanhavre can

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28793 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 5386d4e)
Hash: 5386d4ed864cd03edd026e1d3d128cccedf568df
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```


All works as it should.

![obraz](https://user-images.githubusercontent.com/39754351/167245269-70f764f7-83ee-4667-bfaf-683d48cc105d.png)
