### ISSUE TITLE
Draft: utf8 issue in draftguitools/gui_beziers.py 

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-translations#122]
https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Draft/draftguitools/gui_beziers.py#L64-L65 

is causing issues in crowdin: 
https://crowdin.com/translate/freecad/548/en-en?filter=basic&value=13#6595695
![image](https://user-images.githubusercontent.com/4140247/165583732-6e8cb5fc-4160-44ee-8b21-d45960e699b3.png)

https://crowdin.com/translate/freecad/548/en-en?filter=basic&value=13#6595697
![Screenshot_20220427_132205](https://user-images.githubusercontent.com/4140247/165583833-5d815e76-8691-4369-a0a1-65633aed03eb.png)

**Comment by kaktusus** [comment]
I think the original string has a different encoding than UTF8?

**Comment by luzpaz** [comment]
I was thinking that since this is the only string in the source that uses `Bézier` to just rename it to `Bezier`.

**Comment by chennes** [comment]
At some point we should code a long-term general solution for this: presumably it's simply an encoding issue with one of our translation utility tools. I'm sure CrowdIn can display accented characters if we just get them uploaded correctly.

**Comment by luzpaz** [comment]
Indeed. Not sure how you want to proceed? Merge the PR and create a new issue for the long-term encoding issue?

**Comment by kaktusus** [comment]
> At some point we should code a long-term general solution for this: presumably it's simply an encoding issue with one of our translation utility tools. I'm sure CrowdIn can display accented characters if we just get them uploaded correctly.

Definitely yes ...

This was also the reason I asked about the encoding of the original string.

I work on Linux and my native encoding is UTF8.
I once improved the translation of this very word to "exemplary".

See the effect, gentlemen:

https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=B%C3%A9zier

Everything works correctly.

**Comment by kaktusus** [comment]
![obraz](https://user-images.githubusercontent.com/39754351/165672536-661b1b4f-7674-4d53-aa98-42db65b560c6.png)


![obraz](https://user-images.githubusercontent.com/39754351/165672886-c11b7cd7-b4a7-42c1-abee-b8049d085f13.png)


On the other hand, in FreeCAD all `Bézier` names are displayed correctly but in Crowdin not _(well at least not everywhere)_. I'm starting to think that Crowdin has a problem displaying this char.

![obraz](https://user-images.githubusercontent.com/39754351/165673320-80848674-9f95-4495-a34d-8afe32e06b6e.png)


![obraz](https://user-images.githubusercontent.com/39754351/165673425-27f30572-8474-4939-8bc1-01539a3bea11.png)

**Comment by kaktusus** [comment]
One more test.

I downloaded the source file with the text to be translated. Because it is a text file you can easily examine it with tools that linux has.
For example enca and gedit can do a Character Encoding Checker


![obraz](https://user-images.githubusercontent.com/39754351/165674847-5608d1c1-a4d3-48cf-8df1-0e78b76ce0ad.png)


```
06:04 prompt:~/Pobrane/FreeCAD$ enca -fd draft.ts 
draft.ts: Universal transformation format 8 bits; UTF-8
06:07 prompt:~/Pobrane/FreeCAD$ 
```

**Comment by kaktusus** [comment]
One more observation that proves Crowdin is not guilty of dysfunction.

When I did a test to recognize the encoding used in the draft.ts file, I opened it in QT Linguist, and to my surprise the strings with the word are displayed identically to those in Crowdin.

What's worse the same word is displayed by the program in different ways - does it prove a problem with encoding this specific letter?

![obraz](https://user-images.githubusercontent.com/39754351/165676937-657b4e59-dab1-4121-9633-03138be5fdd0.png)

**Comment by kaktusus** [comment]
I'll use a sports term - chess-mat ;-)

It all comes down to my question I asked in the introduction - what encoding was used in Bézier word
Below is the solution to the puzzle.

![obraz](https://user-images.githubusercontent.com/39754351/165679674-39823c1a-f69f-4227-8ceb-c28dcabeb4db.png)


![obraz](https://user-images.githubusercontent.com/39754351/165680022-f5cd9395-2f04-48d7-8acc-a0a700dcc1d5.png)

```
06:51 prompt:~/Pobrane/FreeCAD$ cat draft_test.ts 

      <translation>Krzywa Béziera</translation>

      <translation>Krzywa Béziera</translation>

      <source>Creates an N-degree BÃ©zier 

      <source>BÃ©zier tools</source>

      <source>Create various types of BÃ©zier curves.</source>
06:51 prompt:~/Pobrane/FreeCAD$ enca -fd draft_test.ts 
draft_test.ts: Universal transformation format 8 bits; UTF-8
  Doubly-encoded to UTF-8 from CORK
06:51 prompt:~/Pobrane/FreeCAD$ ^C
06:57 prompt:~/Pobrane/FreeCAD$ cat draft_test1.ts 

      <source>Creates an N-degree BÃ©zier 

      <source>BÃ©zier tools</source>

      <source>Create various types of BÃ©zier curves.</source>
07:00 prompt:~/Pobrane/FreeCAD$ enca -fd draft_test1.ts 
draft_test1.ts: Universal transformation format 8 bits; UTF-8
  Doubly-encoded to UTF-8 from CORK
```

In my opinion, the source code file containing this word should be corrected by re-writing the word using the correct encoding.

**Comment by chennes** [comment]
This has been resolved.

**Comment by luzpaz** [comment]
> This has been resolved.

Nice! How? Where?

**Comment by chennes** [comment]
@yorikvanhavre modified the updates.py script to use pylupdate5, which fixes the UTF-8 issue.
