### ISSUE TITLE
[PartDesign] text correction proposal

### ISSUE THREAD

**Issue by Kuzma30** [FreeCAD/FreeCAD-translations#123]
https://github.com/FreeCAD/FreeCAD/blob/cd65de7e44cf7542f0c97d7586c3baca26e2d354/src/Mod/PartDesign/Gui/Command.cpp#L344

Now it
    sMenuText       = QT_TR_NOOP("Create a sub-object(s) shape binder");
    sToolTipText    = QT_TR_NOOP("Create a sub-object(s) shape binder");

I propose
    sMenuText       = QT_TR_NOOP("Create a sub-object(s) shape binder");
    sToolTipText    = QT_TR_NOOP("Create a new sub-object(s) shape binder");

like 
https://github.com/FreeCAD/FreeCAD/blob/cd65de7e44cf7542f0c97d7586c3baca26e2d354/src/Mod/PartDesign/Gui/Command.cpp#L278

**Comment by luzpaz** [comment]
Please open a forum  thread and reference this ticket so folks can discuss. I already see a grammatical issue with using `Create a` when we're also predicting possible plural `sub-object(s)`

**Comment by Kuzma30** [comment]
There is special translations branch on forum? Where the best place to discuss translations?

**Comment by kaktusus** [comment]
I recently touched on this topic in the forum:

https://forum.freecadweb.org/viewtopic.php?style=4&f=21&t=68091

I think this is important, and could use a little more organization in this area.

**Comment by Roy-043** [comment]
> I already see a grammatical issue with using `Create a` when we're also predicting possible plural `sub-object(s)`

That grammatical issue does not exist, you are creating a single object that can reference one or more objects. But there are other 'linguistic' issues with the shapebinder commands. Their names are quite confusing:
https://wiki.freecadweb.org/PartDesign_SubShapeBinder#PartDesign_SubShapeBinder_vs._PartDesign_ShapeBinder

IMO the word "new" is superfluous. The word "create" already implies that the object is new. I would suggest removing "new" from the PartDesign_ShapeBinder tooltip instead.

**Comment by chennes** [comment]
Changes like this are best discussed either in the [translation sub-forum](https://forum.freecad.org/viewforum.php?f=45) or just in the sub-forum related to the workbench you are discussing. Only those specifically working on translations are likely to see a discussion here, which means we'll mostly miss the input from people just working generally in FreeCAD.
