### ISSUE TITLE
Harcoded name for first new document and imported doc(without translation)

### ISSUE THREAD

**Issue by Kuzma30** [FreeCAD/FreeCAD-translations#124]
I think this is a problem (small).
When you create first new document its name hard-coded to "Unnamed". Second new document name is localized (For example in Ukrainian it will be "Без Назви1".
I found place where it's harcoded

[getUniqueDocumentName](https://github.com/FreeCAD/FreeCAD/blob/d2253c7be4db12dbf9b89a53abfacff87692d216/src/App/Application.cpp#L440)

![Знімок екрана з 2022-04-30 16-26-38](https://user-images.githubusercontent.com/1382812/166107527-18174e39-0570-47fd-a167-23f32a7b0a8b.png)

**Comment by kaktusus** [comment]
confirm


```

OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28751 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 660655e)
Hash: 660655e54c97b5017ff0ac1e030059308cd4e3f5
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...

```


![obraz](https://user-images.githubusercontent.com/39754351/166108509-bc459ccf-9d73-4c4f-960f-3689c5107122.png)

**Comment by Kuzma30** [comment]
Simular situation for import .step files. It imported to "Unnamed" for first, "Unnamed1' for second.

Harcoded here (for .step)

https://github.com/FreeCAD/FreeCAD/blob/d2253c7be4db12dbf9b89a53abfacff87692d216/src/Mod/Part/App/AppPartPy.cpp#L640

and for .iges
https://github.com/FreeCAD/FreeCAD/blob/d2253c7be4db12dbf9b89a53abfacff87692d216/src/Mod/Part/App/AppPartPy.cpp#L651

![Знімок екрана з 2022-04-30 17-03-59](https://user-images.githubusercontent.com/1382812/166108762-f504bd34-a95a-415b-ae15-7ce17934b8a9.png)

[code]
OS: Ubuntu 22.04 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.20.28804 (Git)
Build type: Release
Branch: master
Hash: 219f2e3cf38725cc574a75a40e4213b3641a05c3
Python 3.10.4, Qt 5.15.3, Coin 4.0.0, OCC 7.7.0.dev
Locale: Ukrainian/Ukraine (uk_UA)
[/code]

**Comment by Kuzma30** [comment]
Final version (all in one) https://github.com/Kuzma30/FreeCAD/commit/d1406343458990ee6f23cb744fa247a4625b1e80
The reason of creating Resources/tranlations for src/App - we text "Unnamed" text for creating new document. 
The second string in ts file created automatic when run lupdate in current directory.
May be there are more texts that we can add to .ts later.

**Comment by Kuzma30** [comment]
@wwmayer @luzpaz Can I create pull-request in such form (prev comment with link)? 
I also can create separate pull-request if need.

**Comment by luzpaz** [comment]
I would encourage you to leave the `lupdate` compilation work for yorik. Just add the code that is significant to the issue you're fixing

**Comment by Kuzma30** [comment]
To solve part of described problem we need create in new place .tm files. Or I need create separate commit for such operation?

**Comment by luzpaz** [comment]
Why not just revert all the .qm and .ts files and submit the source code changes by themselves?

**Comment by Kuzma30** [comment]
Please mark as "for 0.21v"

**Comment by ronnystandtke** [comment]
We can't provide L10n for the "Unnamed" string because the App.ts file is still missing in Crowdin.
Someone more familiar with the details should add it to the src/Tools/updatecrowdin.py script and run it.

See https://github.com/FreeCAD/FreeCAD/pull/9275 for more details.

**Comment by luzpaz** [comment]
@yorikvanhavre any issue with adding `App.ts` to crowdin ?

**Comment by chennes** [comment]
A search of our code for `"Unnamed"` still seems to yield a few untranslated strings, and several different contexts used for what appear to be the same basic usage. I'm seeing instances in Application, Document, DocumentRecovery, and Spreadsheet.

**Comment by ronnystandtke** [comment]
I just noticed that in the current release and also in the current git version this issue is still there.

It seems that despite having i18n in the header and source files, complete translations in crowdin and \*.ts files, updates of all \*.qm files, *NOT A SINGLE* translation from src/App/Resources/translations/App_\* is picked up when running FreeCAD.
I would be glad if someone more familiar with the source code and the i18n/L10n infrastructure of FreeCAD could take a look at it.

**Comment by kaktusus** [comment]
there are three ways to open a new project file

- Main menu
- Toolbar
- Start page

at the moment all three give failure previously it was not so bad.

**Comment by ronnystandtke** [comment]
I think I found the culprit for the missing translations. They were not included in the build scripts for the FreeCAD App. I (hopefully) fixed this issue in this pull request: https://github.com/FreeCAD/FreeCAD/pull/13928

**Comment by kaktusus** [comment]
I am extremely glad that this problem will be solved.
Probably the other one is quite similar: https://github.com/FreeCAD/FreeCAD-translations/issues/257

**Comment by ronnystandtke** [comment]
Yes, it was the same problem. I just updated my pull request to also include the translations of FreeCAD Base in the build process.

**Comment by kaktusus** [comment]
Thanks to 
:1st_place_medal:

**Comment by kaktusus** [comment]
Problem solved, details: https://github.com/FreeCAD/FreeCAD-translations/issues/222#issuecomment-2105549471
Report can be closed.

**Comment by Kuzma30** [comment]
close
