### ISSUE TITLE
[PartDesign] Add datum point,line ....

### ISSUE THREAD

**Issue by Kuzma30** [FreeCAD/FreeCAD-translations#125]
Illegal order for translation in Cyrillic. Word " parameters" must be first in translated text.
Must be "Параметри лінії" (better "Параметри опорної лінії") 

Defined here

https://github.com/FreeCAD/FreeCAD/blob/d2253c7be4db12dbf9b89a53abfacff87692d216/src/Mod/PartDesign/Gui/TaskDatumParameters.cpp#L56

datumtext defined here

https://github.com/FreeCAD/FreeCAD/blob/d2253c7be4db12dbf9b89a53abfacff87692d216/src/Mod/PartDesign/Gui/ViewProviderDatum.cpp#L106-L122

![Знімок екрана з 2022-04-30 18-02-51](https://user-images.githubusercontent.com/1382812/166111016-ae019a73-e07a-4397-96fe-f2dd7fb45f0a.png)

We can define in ViewProviderDatum.cpp  datumText = QObject::tr("Plane parameters");  //example
and delete word "parameters" from TaskDatumParameters.cpp if this not crash another thing :)

**Comment by kaktusus** [comment]
I confirm, problem reported here:

#11

**Comment by Kuzma30** [comment]
Proposed solution
https://github.com/Kuzma30/FreeCAD/commit/e1e172b5d39efbbb84ffc5e174239bd3f7a327fb

**Comment by Kuzma30** [comment]
Proposed solution for #24 
https://github.com/Kuzma30/FreeCAD/commit/fb58fd825367bb35f9fbe75a3d89fa9f48ec2249

**Comment by Kuzma30** [comment]
@wwmayer @luzpaz Can I create pull-request in such form? No claims to the code (last 2 comment with links)?

**Comment by luzpaz** [comment]
I think so. I say go for it!

**Comment by Kuzma30** [comment]
This strings will be on Crowdin during next update by Yorik.
Tested on test crowdin server. It's fix problem.

**Comment by Kuzma30** [comment]
This strings will be on Crowdin during next update by Yorik.
Tested on test crowdin server. It's fix problem.
