### ISSUE TITLE
[Crowdin] MeshWB - "Fix self-intersections" string

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-translations#128]
The issue is about clarification. 
> Fix?
> Maybe it should be "Remove"

ref: https://crowdin.com/translate/freecad/561/en-en?filter=basic&value=0#6585606

Edit: found a separate issue in the mean time https://github.com/FreeCAD/FreeCAD/pull/6817

**Comment by chennes** [comment]
I'm going to close this one: while technically it does remove the intersections, I'm not sure it's worth forcing a complete retranslation for this minor bit of undo text.
