### ISSUE TITLE
[Crowdin] MeshWB: Alt+O string

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-translations#129]
This is a strange issue. If I'm reading the source code right, the shortcut Alt+O is associated with [Closing](https://github.com/FreeCAD/FreeCAD/blob/69b36ab34a177bf894e017faf6410cd5401ce58f/src/Mod/Mesh/Gui/DlgRegularSolid.ui#L825)?  
 
crowdin issue: https://crowdin.com/translate/freecad/561/en-en?filter=basic&value=0#1172084
code: https://github.com/FreeCAD/FreeCAD/blob/69b36ab34a177bf894e017faf6410cd5401ce58f/src/Mod/Mesh/Gui/DlgRegularSolid.ui#L828

**Comment by chennes** [comment]
You're not mistaken: that's exactly what's happening. This is a very old dialog that hasn't been touched in a while. I propose we eliminate this shortcut, which is so non-discoverable it's basically worthless. Hitting "Esc" closes the dialog just fine.
