### ISSUE TITLE
Sketcher → Constrain diameter (tool)

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#13]
```
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.25025 (Git) AppImage
Build type: Release
Branch: master
Hash: fb8b21ec43dca706a4aa2d63d59a4fb79f050369
Python version: 3.9.4
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: Polish/Poland (pl_PL)
```

I found only one inconvenience in the sketcher,
![obraz](https://user-images.githubusercontent.com/39754351/121722313-94574180-cae5-11eb-9b9f-42ab903cd7f0.png)
the same window launched from other tools looks correct.

**Comment by luzpaz** [comment]
Hi @abdullahtahiriyo any idea where this would be in the source code. Search "Change diameter" in the source code doesn't reveal it 

I found `Constrain diameter` though

https://github.com/FreeCAD/FreeCAD/blob/4de2ad46b2b9c78ac2721a0dbea7c19306261095/src/Mod/Sketcher/Gui/CommandConstraints.cpp#L5230

https://github.com/FreeCAD/FreeCAD/blob/4de2ad46b2b9c78ac2721a0dbea7c19306261095/src/Mod/Sketcher/Gui/CommandConstraints.cpp#L6005

**Comment by abdullahtahiriyo** [comment]
Hi there!

I think it is gone with one of the latests PRs. 

However, maybe the same issue appears now with "Insert Diameter". Does this help?

```
Gui/EditDatumDialog.cpp:            dlg.setWindowTitle(tr("Insert angle"));
Gui/EditDatumDialog.cpp:            dlg.setWindowTitle(tr("Insert radius"));
Gui/EditDatumDialog.cpp:            dlg.setWindowTitle(tr("Insert diameter"));
Gui/EditDatumDialog.cpp:            dlg.setWindowTitle(tr("Insert weight"));
Gui/EditDatumDialog.cpp:            dlg.setWindowTitle(tr("Insert length"));
```

Let me know if it does not, and I will take another look. :)

**Comment by luzpaz** [comment]
I see them in Crowdin, and they are all translated to polish already. 

`Insert angle`: https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=3#6497559  
`Insert radius`: https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=3#6497561  
`Insert diameter`: https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=3#6511428  
`Insert weight`: https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=3#6585764  
`Insert length`: https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=3#6497563

They are also in the .ts file  
https://github.com/FreeCAD/FreeCAD/blob/147b2ec3c93b1c33447c032b31283f1f679cd518/src/Mod/Sketcher/Gui/Resources/translations/Sketcher.ts#L3782-L3817

**Comment by luzpaz** [comment]
@kaktusus can you retry with the latest translations?

**Comment by kaktusus** [comment]
ok ...
during ;-)

**Comment by luzpaz** [comment]
OK, that's partially good news. The translations are working but there is a separate bug w/ window position. So I'll close this ticket then?

**Comment by kaktusus** [comment]
in the meantime, I edited my message ...

I think this ticket can be closed. We are working on improving the translations.
