### ISSUE TITLE
[Cowdin] MeshWB: "Mesh Create" string

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-translations#130]
Perhaps "Create mesh" instead?

There are 2 instances of this in the source:  
https://github.com/FreeCAD/FreeCAD/blob/69b36ab34a177bf894e017faf6410cd5401ce58f/src/Mod/Mesh/Gui/Command.cpp#L151
https://github.com/FreeCAD/FreeCAD/blob/69b36ab34a177bf894e017faf6410cd5401ce58f/src/Mod/Mesh/Gui/Command.cpp#L111

Crowdin: https://crowdin.com/translate/freecad/561/en-en?filter=basic&value=0#6589156

**Comment by chennes** [comment]
This string no longer exists in the code. @yorikvanhavre do you know why it's still in the TS file?

**Comment by kaktusus** [comment]
Is this ticket suitable for closing already?

**Comment by kaktusus** [comment]
I renew my question if this ticket can be closed?

**Comment by kaktusus** [comment]
![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/f33aa7a8-b209-413c-9345-e4124975e5be)


https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Mesh%20Create

**Comment by kaktusus** [comment]
@chennes 
in my opinion this ticket can be closed.
