### ISSUE TITLE
[Crowdin] QObject: "Select which object to copy..." string 

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#132]
https://crowdin.com/translate/freecad/549/en-pl#6598708

No spacing between words:
`changes.All`

![obraz](https://user-images.githubusercontent.com/39754351/167242729-2d52e722-d89f-44f2-98f9-ac746655c06e.png)

**Comment by luzpaz** [comment]
There is also a typo: object->objects

I'll submit a PR to fix both.

**Comment by luzpaz** [comment]
Merged in https://github.com/FreeCAD/FreeCAD/commit/086d86ee118717000320dfb410eaf902826ac2d1
