### ISSUE TITLE
FreeCAD → Tools → Addon manager [AddonsInstaller] - part 2

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#133]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28793 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 5386d4e)
Hash: 5386d4ed864cd03edd026e1d3d128cccedf568df
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

Continuation of submission #114
A lot of translations have been improved, but I still found something:

![obraz](https://user-images.githubusercontent.com/39754351/167269188-01efb6ad-892c-4fef-9df3-f01c22bb5758.png)

1. `Some packages updates failed.`  - no string in Crowdin.
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Some%20packages%20updates%20failed.

![obraz](https://user-images.githubusercontent.com/39754351/167269383-102fe83d-2545-41c0-a808-6c626d94c690.png)

2.  `You must restart FreeCAD for changes to take effect.`  - no string in Crowdin.
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=You%20must%20restart

3. `Retrieving macros from FreeCAD/FreeCAD-Macros Git repository`  - no string in Crowdin.
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Retrieving%20macros%20from
![obraz](https://user-images.githubusercontent.com/39754351/167269797-e579cda1-322c-490a-b54c-3d9ab132644e.png)

4. `Retrieving macros from FreeCAD Wiki` - no string in Crowdin.

I found it difficult to take a screenshot of this message because the displayed message changes quickly.
I tried to make a movie but the messages are unreadable.
There may also be other untranslated messages that are difficult to see.

I click on the "Refresh local cache" button.

**Comment by Kuzma30** [comment]
https://github.com/Kuzma30/FreeCAD/tree/final_133
Check on my fork. This add 25+ new string to translate.
But with one string I need help of Python guru.
https://github.com/Kuzma30/FreeCAD/blob/355485b290b09afa0cc69545ee2a528abfb11965/src/Mod/AddonManager/AddonManager.py#L1384-L1388
One part is added to crowdin normaly, but another part show as description in crowdin.
![Знімок екрана з 2022-05-08 12-14-37](https://user-images.githubusercontent.com/1382812/167289699-35fe9277-d982-4c51-936e-9153e18ad138.png)

**Comment by Kuzma30** [comment]
ping @yorikvanhavre

**Comment by kaktusus** [comment]
Alex, this is what @chennes is doing.

**Comment by chennes** [comment]
In the string I have here:
https://github.com/Kuzma30/FreeCAD/blob/355485b290b09afa0cc69545ee2a528abfb11965/src/Mod/AddonManager/AddonManager.py#L1384-L1388

You only translate the main string -- the second string is a note to translators so it's understood what is going inside the `{}`.

**Comment by Kuzma30** [comment]
@chennes please review and merge https://github.com/FreeCAD/FreeCAD/pull/6853

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28945 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0fb7cd9)
Hash: 0fb7cd9758d850f536d571cc094c9833fee18fff
Python 3.9.13, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```


Fixed.
