### ISSUE TITLE
[FreeCAD-addons] Reinforcement → Edit → Preferences ... → Reinforcement / BillOfMaterial

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#136]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28793 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 5386d4e)
Hash: 5386d4ed864cd03edd026e1d3d128cccedf568df
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

No translations throughout the preferences window. Applies to tab names, options, and drop-down lists. 
There is also no pop-up hints which are very helpful.

![obraz](https://user-images.githubusercontent.com/39754351/167284083-a04907b7-7246-4dab-ab57-3287649cbdab.png)

SVG tab.
![obraz](https://user-images.githubusercontent.com/39754351/167284103-2c426027-10d9-4bad-b69a-955563f0738e.png)

**Comment by kaktusus** [comment]
still needs attention.

**Comment by luzpaz** [comment]
CC @amrit3701

**Comment by hasecilu** [comment]
We need to use a `lupdate` on the `.ui` files, I'm preparing a PR

![image](https://github.com/FreeCAD/FreeCAD-translations/assets/53124818/b5aa60f5-2897-43c2-86ca-a38dddb503d5)

**Comment by kaktusus** [comment]
fixed:
pre-translation :wink:
![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/66bf06dc-10d4-4b02-b6f6-684b9bf8e2e4)

**Comment by kaktusus** [comment]
fixed:
pre-release translation :wink:

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/66bf06dc-10d4-4b02-b6f6-684b9bf8e2e4)
