### ISSUE TITLE
Mesh Design → main menu / View → Toolbars

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#138]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28793 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 5386d4e)
Hash: 5386d4ed864cd03edd026e1d3d128cccedf568df
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

Toolbar names do not have translations in the GUI.

![obraz](https://user-images.githubusercontent.com/39754351/167286935-8102e648-1126-420a-8a38-cabcc3a6e76d.png)

1. `Mesh modify`- no string in Crowdin.
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Mesh%20modify

2. `Mesh boolean` - No corresponding string in Crowdin.
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Mesh%20boolean

3. `Mesh cutting`- no string in Crowdin.
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Mesh%20cutting

4. `Mesh segmentation` - No corresponding string in Crowdin.
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Mesh%20segmentation

5. `Mesh analyze`- no string in Crowdin.
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Mesh%20analyze

**Comment by chennes** [comment]
These should be resolved by https://github.com/FreeCAD/FreeCAD/commit/44540a4d82e9a990ddbada09a1f3368f8c319d93

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28945 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0fb7cd9)
Hash: 0fb7cd9758d850f536d571cc094c9833fee18fff
Python 3.9.13, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```


Fixed.

![obraz](https://user-images.githubusercontent.com/39754351/170874478-492a8082-ec1b-44e1-a164-e2b440fd03f3.png)
