### ISSUE TITLE
FreeCAD → Edit → Preferences ... → Path / Advanced (tab)

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#139]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28810 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 6f5a5a2)
Hash: 6f5a5a2019c586db63650713de860d3e810739d4
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

The label and information has no translation in the GUI

![obraz](https://user-images.githubusercontent.com/39754351/167378767-fb4f5cf1-8880-415b-bac3-ed4abf2017dd.png)

1. `Suppress Velocity warning`- The string is present in Crowdin, but is not displayed in the GUI.
    https://crowdin.com/translate/freecad/27909/en-pl#6598350

3. The information displayed in the window is not available to translators in the Crowdin.

**Comment by Kuzma30** [comment]
But we have it on upstream .ts
https://github.com/FreeCAD/FreeCAD/blob/b4cb34c4d34d965838290490e478c16c84b655e7/src/Mod/Path/Gui/Resources/translations/Path.ts#L6303

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28945 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0fb7cd9)
Hash: 0fb7cd9758d850f536d571cc094c9833fee18fff
Python 3.9.13, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```


Fixed.


![obraz](https://user-images.githubusercontent.com/39754351/170874319-6ae0fb5b-f0ef-44ab-bbf8-f2b704c63d53.png)
