### ISSUE TITLE
Part → Solids toolbar → Create tube

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#140]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28810 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 6f5a5a2)
Hash: 6f5a5a2019c586db63650713de860d3e810739d4
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

Label and tooltip do not have translations in the GUI.

![obraz](https://user-images.githubusercontent.com/39754351/167488507-6e4d7238-04f4-4026-b0c6-9550c0ddbcb1.png)

1.  `Create tube` - no string in Crowdin.
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Create%20tube

1.  `Creates tube` - no string in Crowdin.
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Creates%20tube

**Comment by Kuzma30** [comment]
https://crowdin.com/translate/freecadtest/364/en-uk?filter=basic&value=5#q=Create%20tube
same as https://github.com/FreeCAD/FreeCAD-translations/issues/142

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28945 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0fb7cd9)
Hash: 0fb7cd9758d850f536d571cc094c9833fee18fff
Python 3.9.13, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```


Fixed all.

![obraz](https://user-images.githubusercontent.com/39754351/170874008-225ba299-5d95-4ca5-9d6b-3d9258e5fa32.png)
