### ISSUE TITLE
TechDraw → TechDraw menu → Extensions: Attributes/Modifications → Customize Format Label (tool)

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#144]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28810 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 6f5a5a2)
Hash: 6f5a5a2019c586db63650713de860d3e810739d4
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

The new tools in TechDraw are just amazing.

However, I found a minor inconvenience.
The author used an abbreviation in the description.
I decided to expand it in the translation, so that the user could have clear information.

`GD&T`  → `Wymiarowanie geometrii i tolerancja (GD&T)`
https://crowdin.com/translate/freecad/27911/en-pl#6597878

![obraz](https://user-images.githubusercontent.com/39754351/167596214-d498e1ea-835d-44f2-8718-1cea23a7905a.png)

Result - the text was cut off. on my screen there is a lot of space in this place.
Could the title be presented dynamically depending on the width of the window?

...

All in all, it's dynamic but leaves too little place for the label ...

**Comment by luzpaz** [comment]
ping @wandererfan

**Comment by WandererFan** [comment]
commit f0f0124f76 should fix this, but I couldn't find a language with a long enough string to test with.  Let me know if it doesn't work.

**Comment by kaktusus** [comment]
Of course, when I test it, I will notify you of the result.

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28884 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 51fdb42)
Hash: 51fdb42f21b4c6a7c9f91956e51427b896070f96
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```
Solver - thanks.

![image](https://user-images.githubusercontent.com/39754351/168883563-4f7fe8b2-5e37-4421-af58-3c60dcc55b38.png)
