### ISSUE TITLE
TechDraw → TechDraw menu → Move View

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#147]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28810 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 6f5a5a2)
Hash: 6f5a5a2019c586db63650713de860d3e810739d4
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

Tools labels do not have translations in the GUI.

![image](https://user-images.githubusercontent.com/39754351/167787611-10c744a2-6321-44ae-bdcc-5b4f34fb6bb7.png)

1.  `Move View to a different Page` - The string is in Crowdin.
    https://crowdin.com/translate/freecad/27911/en-pl#6595243

**Comment by Kuzma30** [comment]
Is the FreeCAD compiled with the latest translations (manually updated) from crowdin ?

**Comment by kaktusus** [comment]
FreeCAD downloaded from the GIT weekly-builds repository.

Translations updated manually as needed.

**Comment by Kuzma30** [comment]
Strange. We have all needed thing, but still tools labels do not have translations in the GUI.
1. Move View to a different Page - The string is in Crowdin.    https://crowdin.com/translate/freecad/27911/en-pl#6595243
2. https://github.com/FreeCAD/FreeCAD/blob/391c9a6bbf8a6302ac1d837a2ea3f10860d8253a/src/Mod/TechDraw/TechDrawTools/TaskMoveView.py#L29
3. https://github.com/FreeCAD/FreeCAD/blob/391c9a6bbf8a6302ac1d837a2ea3f10860d8253a/src/Mod/TechDraw/TechDrawTools/TaskMoveView.py#L47
4. https://github.com/FreeCAD/FreeCAD/blob/391c9a6bbf8a6302ac1d837a2ea3f10860d8253a/src/Mod/TechDraw/Gui/Resources/translations/TechDraw_pl.ts#L18

**Comment by Kuzma30** [comment]
I found that MoveView and ShareView use the same .ui file and redefine texts in ui. Also it use same .ui fol Dialog which select View.
QT_TRANSLATE_NOOP for texts for some reason not working in this situation. After trying with QtGui.QApplication.translate() it start working.

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.29277 (Git) AppImage
Build type: Release
Branch: master
Hash: ad0f1147f74d8e010d47cfca2bb08033e0f3b4ae
Python 3.10.5, Qt 5.12.9, Coin 4.0.0, Vtk 9.1.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
```



following the creator ...

![obraz](https://user-images.githubusercontent.com/39754351/176487097-f4dfe479-37a4-4e20-9335-1576d7024a01.png)

1. `Select Page` - the string is found in Crowdin
    https://crowdin.com/translate/freecad/27911/en-pl#6599762
3. `Select From Page.` - the string is found in Crowdin
    https://crowdin.com/translate/freecad/27911/en-pl#6599760

**Comment by Kuzma30** [comment]
Can you check this strings in _pl.ts on upstream.

**Comment by kaktusus** [comment]
Applies to both options:
From Page
To Page

![obraz](https://user-images.githubusercontent.com/39754351/176722693-f97c7e55-4078-423a-8148-7cd9916768ef.png)

The following window also needs attention:
![obraz](https://user-images.githubusercontent.com/39754351/176722879-be5b1004-20cd-4c0d-93fe-7d4d8acd3c15.png)

**Comment by chennes** [comment]
None of these strings should be using QT_TRANSLATE_NOOP -- that one just extracts the string, but does not apply the translation. For things like Commands that is correct, because the code that actually creates the widgets calls `tr()`, but in these cases the translate function must be called directly.

**Comment by kaktusus** [comment]
fixed

Version: 0.21.0.33110 (Git) AppImage
