### ISSUE TITLE
Qt translation files are out-of-date

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#149]
**needs urgent attention**

Thanks to the support of @Kuzma30 we managed to validate the problem of the lack of translations in Polish for the windows function buttons.

https://github.com/FreeCAD/FreeCAD/issues/6875

Ultimately, the problem lies in the outdated content of the QT translation files relative to the source project.
Related to the file **qt_pl.qm** https://github.com/qt/qttranslations/blob/dev/translations/qt_pl.ts
The file qt_pl.qm depends on the qtbase_pl multimedia_pl files also from the QT project.

Please update the QT environment files for the Polish language in the FreeCAD project.

**Comment by kaktusus** [comment]
Source files with translations for QT environment:
https://github.com/FreeCAD/FreeCAD/tree/master/src/Gui/Language

**Comment by luzpaz** [comment]
So you're saying the version schema needs to be updated?

**Comment by kaktusus** [comment]
I want to update the files to contain all the translated records,

By the way, I discovered as you did that the structure has changed.

I think it would be a good idea to update the whole thing for the other languages as well (all languages, not just selected ones)

I can also prepare a PR for the "old" qt_pl file with the completed translations, but this will not ensure compatibility with the current QT project.

Which solution is better?

**Comment by Kuzma30** [comment]
I have idea. May be we delete this Qt translation from FreeCAD source. This is Qt related package. I think there is ability for all OS get it. 
For Linux this files provides as separate package. For example for Ubuntu this is https://packages.ubuntu.com/bionic/qttranslations5-l10n. 
For Windows we can transfer it to LibPack. For Mac - I don't know (I don't work with Mac at all)

**Comment by luzpaz** [comment]
Lets open a forum thread to discuss this.

**Comment by Kuzma30** [comment]
Agree with you. Please create forum thread.

**Comment by kaktusus** [comment]
> I have idea. May be we delete this Qt translation from FreeCAD source. This is Qt related package. I think there is ability for all OS get it in actual state.

Very but very good solution.

Always ensures compatibility and up-to-date.

**Comment by kaktusus** [comment]
> Agree with you. Please create forum thread.

In the sub forum for translators, of course.

;-p

**Comment by kaktusus** [comment]
![image](https://user-images.githubusercontent.com/39754351/168373595-983cb2ce-f00f-45f8-8243-0e8763447698.png)

In my opinion, Alex's proposal is a good one, it brings a positive breath of fresh air and relieves the responsibility of taking care of the QT environment files. The lack of their updates caused a big problem with the Polish language interface. This may happen many times.
I think, that the developers project managers should make a decision in this topic.

**Comment by luzpaz** [comment]
This is not just for polish language but all languages, right?

**Comment by kaktusus** [comment]
Yes, a problem in the Polish language has led us to this point.
The problem has become global. You can do something good for the whole project.

**Comment by kaktusus** [comment]
Additionally please note that the [FreeCAD repository on GitHub](https://github.com/FreeCAD/FreeCAD/tree/master/src/Gui/Language) is not consistent, it contains old files:

1. `qt_xx.qm` for **11** languages

![image](https://user-images.githubusercontent.com/39754351/168412230-352693bf-6b48-4f5e-8b40-5b65de2e3021.png)

   In case of Polish language, this source is not up-to-date - it does not contain translations for the program options used.

2. `qtbase_xx.qm` for **10** languages

![image](https://user-images.githubusercontent.com/39754351/168412302-670d1eb9-9f4c-472f-9c2a-8bb07d10a428.png)

Currently _(2022-05-14)_ FreeCAD is translated into **66** languages.

**Comment by kaktusus** [comment]
Noticed that this topic is developed by @wmayer and managed by @yorikvanhavre

**Comment by kaktusus** [comment]
Solving the lack of Polish translations:  [#6882](https://github.com/FreeCAD/FreeCAD/pull/6882)

**Comment by kaktusus** [comment]
A different global solution might be to give up additional "foreign" translation files.
FreeCAD has its own personal files used for GUI localization.
As you can see the use of translations from foreign files _(QT)_ is small, in addition similar strings are already present in FreeCAD.

I think it's worth considering which solution to use and what advantages and disadvantages does it bring.

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28884 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 51fdb42)
Hash: 51fdb42f21b4c6a7c9f91956e51427b896070f96
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```
So the problem with untranslated function key labels in the Polish GUI has been solved.
Fix https://github.com/FreeCAD/FreeCAD/pull/6883

I wonder who else will struggle with it.

The topic for now I do not close because there were raised here interesting matters.

**Comment by kaktusus** [comment]
Foreign translation files have once again left a bad mark.

![obraz](https://user-images.githubusercontent.com/39754351/172070511-77aeb1d1-1ad2-498d-9de5-9ca8d228b310.png)

Menu contains incorrectly translated keyboard shortcut.
Repairing this will be cumbersome but possible.

**Comment by Kuzma30** [comment]
You can check translation for this text in qt related .qm file.

**Comment by adrianinsaval** [comment]
IMO it doesn't make sense to have Qt translations on our source code

**Comment by chennes** [comment]
Are there any actions left to be taken on this Issue?

**Comment by kaktusus** [comment]
My problem was directly solved.
But in general the topic is open, it will also cause problems for translators of other nationalities.

**Comment by chennes** [comment]
I am going to merge in the latest files from the Qt GitHub repo once we have a system for compiling the QM files from the TS files as part of the compilation process. Hopefully in the next couple of weeks here.

**Comment by kaktusus** [comment]
When I made the corrections to the Polish language I did it locally bypassing the source files in the QT repo.
So at that time the translation files in FreeCAD were more up-to-date than in the QT repository.

**Comment by chennes** [comment]
This merge is complete.
