### ISSUE TITLE
[Preferences - PartDesign - General] Copy/paste error?

### ISSUE THREAD

**Issue by Kuzma30** [FreeCAD/FreeCAD-translations#150]
![Знімок екрана з 2022-05-15 13-59-35](https://user-images.githubusercontent.com/1382812/168469433-4d6f3971-6446-49b9-81c7-3bb837e3c1a3.png)
First and second string equal.

**Comment by kaktusus** [comment]
Itt's not quite like that.

These are two different options, although they differ little in description.
Let me explain.

1. The check option looks for errors after a logical operation,
2. The refine option improves the shape, e.g., by optimizing the contour.

It's explained decently here:
https://wiki.freecadweb.org/PartDesign_Preferences/pl#General

**Comment by Kuzma30** [comment]
Thanks, this is my mistake. :)
