### ISSUE TITLE
FreeCAD → Edit → Preferences ... → Display / Navigation (tab)

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#152]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28884 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 51fdb42)
Hash: 51fdb42f21b4c6a7c9f91956e51427b896070f96
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

The label has no translation in the GUI.

![image](https://user-images.githubusercontent.com/39754351/169593604-491bfdf1-3db3-4b38-8253-48e057e04cfe.png)

1.  `Zoom step` - string is found in Crowdin but I don't know if that occurrence applies to this case.
    https://crowdin.com/translate/freecad/549/en-pl?filter=basic&value=0#q=Zoom%20step

**Comment by Kuzma30** [comment]
![Знімок екрана з 2022-05-28 20-28-21](https://user-images.githubusercontent.com/1382812/170836339-9acefab1-3472-484c-849f-aff090b20dc2.png)
Fixed, test on latest snap build (edge channel)

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28945 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0fb7cd9)
Hash: 0fb7cd9758d850f536d571cc094c9833fee18fff
Python 3.9.13, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```


Fixed.
