### ISSUE TITLE
Start → Help (tab)

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#156]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28909 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 2084652)
Hash: 20846523c9d8219ec0fe33c499a64e700d2266b6
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

The Help page does not follow your language settings.

1. I have the Help tab open, click on any workbench item or whatever:

![image](https://user-images.githubusercontent.com/39754351/169692740-3f9dea1e-7955-4ca8-b968-e1e1ded94bc7.png)

2. It is necessary to change the current language with the available option...

![image](https://user-images.githubusercontent.com/39754351/169692839-4aadeb30-6fee-438a-9b6c-c087fbbe26d1.png)

3. The option to go back to the start page from step 1 would also be helpful.

**Comment by yorikvanhavre** [comment]
yes. indeed the "back" button of the web browser does not behave correctly when giving it html code directly... so far i haven't found what's wrong

**Comment by kaktusus** [comment]
hehe, 
your answer led me to a discovery I had the "navigation" toolbar disabled
;-D

Since the back button doesn't work that way, you might want to work around the problem and add a button that loads the FreeCAD home page (FreeCAD Home button).

One home button is already there but I have no idea what it does.

**Comment by kaktusus** [comment]
![image](https://user-images.githubusercontent.com/39754351/169697178-50872b65-1707-4775-864f-81f004ab34f4.png)

One piece of good news, 
the button I checked led me to the entry point, 
loaded the start workbench.

It would leave localization of loaded wiki pages to be done.

**Comment by yorikvanhavre** [comment]
maybe we could add a "open start page" button, that's more or less easy, while we try to fix the back button

**Comment by kaktusus** [comment]
Not with me.
But when I click on it, the green arrow to the left activates.
Then I can click it which will load the "Start" page.

**Comment by kaktusus** [comment]
@Kuzma30 can you check how it works for you?

**Comment by Kuzma30** [comment]
![Знімок екрана з 2022-05-23 07-47-31](https://user-images.githubusercontent.com/1382812/169745639-083999a3-55c4-438b-ab79-4c1f0b7ba5c4.png)

There is no language code in links

**Comment by yorikvanhavre** [comment]
This works for me:

1. Open FreeCAD
2. In case it starts with the start WB, switch to another WB, and close the start page
3. Switch back to the start WB
4. Press the blue arrow button (Start_StartPage command)

The start page opens.

About the other issue notified by @Kuzma30 , I think this section actually needs to be redone to take advantage of the Help workbench... Ideally also, each addon workbench should inform the location of their own help page... there were provisions for that in the past, but I think they were never used...

**Comment by kaktusus** [comment]
It still does not work.
Additionally the homepage toolbar is not available.

**Comment by yorikvanhavre** [comment]
What still does not work? The start page does not open when pressing the blue arrow button?

**Comment by kaktusus** [comment]
1. choose a startup workbebch

2. click the help tab
the translated content is loading

3. click eg. draft workbebch
page loads in _English_
why not translated?

wrong

4. click back - previous page
`last used files` page loads
my previous page was `help`.

wrong

5. click redo - next page
Draft Workbench page loads in English
it's ok

6. I click the blue arrow - start page
nothing is happening

wrong

I can make a video of this activity if it helps you.

heh by the way I found my missing toolbar - I forgot that you have to enable the Start workbench. :rofl:

**Comment by yorikvanhavre** [comment]
Ok lots of different problems here...

- Module help links on the Help page are not going to the translated version on the wiki. That should not be hard to fix as we have the language code from the URL...
- The back button does not work: I cannot confirm, it works for me? After I click one of the workbench help links, clicking the "back" button brings me back to the s tart page. You mean you want to be sent back to the Help tab? I don't know if that's possible, as it is the same HTML page...
- The "load start page" button does not work if a start page is already open, even if it is displaying another page. That happens in https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Start/Gui/Workbench.cpp#L63 Basically we should somehow gt a reference to the browser MDI view, and make it reload the start page. Not sure yet how to do that...

**Comment by kaktusus** [comment]
thank you for clarifying the problems

I hope you will find free time that you can devote to repairing the issues

**Comment by kaktusus** [comment]
We no longer have a start page.

```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37249 (Git) AppImage
Build type: Release
Branch: main
Hash: 3acbc561f299b4cddea8215c387a52f3d5132cf6
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```
