### ISSUE TITLE
Part Design →  Chamfer (tool)

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#159]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28993 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 6d92e53)
Hash: 6d92e532bcc31c99a0ab4c153ff00b6414b8f527
Python 3.9.13, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
```

Message window without translation.

![obraz](https://user-images.githubusercontent.com/39754351/172016877-f6d6fb57-d868-4c68-8817-ae5b8e855fc3.png)

`Failed to create chamfer` - no string in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Failed%20to%20create%20chamfer

Also, the window is very small so the description is not clear. It is also impossible to resize it - stretch it.
This case can also apply to other tools, e.g. draft, thickness etc.

**Comment by kaktusus** [comment]
Another issue for this tool.

![obraz](https://user-images.githubusercontent.com/39754351/172018445-ab8f2238-d177-49fd-a6ab-94770ad8508e.png)

If, in a tree view, I open the popup menu for this object to edit, I see an untranslated option label.
The message in the window appears to be constructed from several strings.
This case can also apply to other tools, e.g. fillet, draft, thickness etc.
The problem was found by david69 from the FreeCAD forum.

**Comment by chennes** [comment]
That's really an unrelated issue. The first thing you reported is untranslatable because it's an instance of the GUI displaying directly an error message from the non-GUI code, which we do not translate. The second error is in an unrelated part of the code.

**Comment by kaktusus** [comment]
ok, I get it
do I have to do a separate ticket?

**Comment by chennes** [comment]
I recommend it -- from a developer's standpoint these two things have nothing in common. I'm trying to track down the option menu right now, since that should be relatively easy to fix. What is the original English string there?

**Comment by kaktusus** [comment]
`Edit chamfer`

![obraz](https://user-images.githubusercontent.com/39754351/172022904-d29434a6-f70d-40f6-8b15-b510189110f8.png)


In our conversation David said that in French the string is translated analogously.
That is, the first word is translated and the second is not.

**Comment by kaktusus** [comment]
Second submission moved to:
https://github.com/FreeCAD/FreeCAD-translations/issues/166

**Comment by chennes** [comment]
This is fixed in my copy (though the translation of "Chamfer" doesn't always seem to happen, and the menu doesn't appear to get recreated when you change the object's label).

**Comment by kaktusus** [comment]
is still occurring
