### ISSUE TITLE
FreeCAD or Arch → Combo View (tree view)

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#16]
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.25025 (Git) AppImage
Build type: Release
Branch: master
Hash: fb8b21ec43dca706a4aa2d63d59a4fb79f050369
Python version: 3.9.4
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: Polish/Poland (pl_PL)

I move the cursor to the position with the error
![obraz](https://user-images.githubusercontent.com/39754351/121738949-3897b300-cafb-11eb-8086-bcc177b6df5b.png)

1.  list index out of range
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=list%20index%20out%20of%20range

RMB on position with error "door"
![obraz](https://user-images.githubusercontent.com/39754351/121739573-1c484600-cafc-11eb-9d99-80f8fff73ee0.png)

1. Invert opening direction - translation from Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=invert%20opening%20direction
2. Invert hinge position - translation from Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=invert%20hinge
3. Utilities - translation from Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Utilities
4. Link actions - translation from Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Link%20actions

I'm not sure if the translation links provided contain the right items.

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28793 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 5386d4e)
Hash: 5386d4ed864cd03edd026e1d3d128cccedf568df
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

After recent updates the problem still persists ...

![obraz](https://user-images.githubusercontent.com/39754351/167264828-deed7531-eab0-4c02-a50b-38b04cf846f0.png)

**Comment by chennes** [comment]
These are fixed now (if not, then something deeper is going wrong, please re-open and @-mention me).

**Comment by kaktusus** [comment]
these options have disappeared

Version: 0.21.0.33110 (Git) AppImage
