### ISSUE TITLE
Part Design → Fillet (tool)

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#160]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28993 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 6d92e53)
Hash: 6d92e532bcc31c99a0ab4c153ff00b6414b8f527
Python 3.9.13, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
```

Message window without translation.

![obraz](https://user-images.githubusercontent.com/39754351/172016771-2910de89-140d-4e81-a083-9b23152d3c79.png)

`Failed to create fillet` - no string in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Failed%20to%20create%20fillet

Also, the window is very small so the description is not clear. It is also impossible to resize it - stretch it.
This case can also apply to other tools, e.g. draft, thickness etc.

**Comment by kaktusus** [comment]
Another issue for this tool.

![obraz](https://user-images.githubusercontent.com/39754351/172018525-ff0d832e-ba23-4dc3-bb33-41af62dd99a0.png)

If, in a tree view, I open the popup menu for this object to edit, I see an untranslated option label.
The message in the window appears to be constructed from several strings.
This case can also apply to other tools, e.g. chamfer, draft, thickness etc.
The problem was found by david69 from the FreeCAD forum.

**Comment by chennes** [comment]
I'm going to close this in favor of the more general issue about untranslated exceptions.
