### ISSUE TITLE
Part Design → Draft (tool)

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#161]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28993 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 6d92e53)
Hash: 6d92e532bcc31c99a0ab4c153ff00b6414b8f527
Python 3.9.13, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
```

Message window without translation.

![obraz](https://user-images.githubusercontent.com/39754351/172017412-1abd7418-e912-43ec-a16e-fd5390e2fe5a.png)

The message in the window appears to be constructed from several strings.

Crowdin includes only part of the message:
` not possible on selected faces/edges.` - https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=%20nie%20jest%20mo%C5%BCliwe%20na%20wybranych%20%C5%9Bcianach%20/%20kraw%C4%99dziach.

This case can also apply to other tools, e.g. fillet, chamfer, thickness etc.

**Comment by kaktusus** [comment]
Another issue for this tool.

![obraz](https://user-images.githubusercontent.com/39754351/172018352-20fb6aea-a114-4763-a3b1-39d24bbb1509.png)

If, in a tree view, I open the popup menu for this object to edit, I see an untranslated option label.
The message in the window appears to be constructed from several strings.
This case can also apply to other tools, e.g. fillet, chamfer, thickness etc.
The problem was found by david69 from the FreeCAD forum.

**Comment by kaktusus** [comment]
this notification is so old that my notes how I caused this error are lost, I have to try to reproduce it

arm yourself with patience ;-)

**Comment by kaktusus** [comment]
I think I managed to cause this error
but the behavior of the program has been changed

The new notification looks nice even very nice but contains untranslated text ...
;-D

![image](https://user-images.githubusercontent.com/39754351/234034478-b556e41b-5753-4964-b5c6-3606aa2b446a.png)

**Comment by chennes** [comment]
The vast majority of console messages are currently untranslated: there is some ongoing discussion in the Forum about this state of affairs, which was a deliberate choice from some years ago. For now I am only concerned with messages that appear in dialog boxes, translating the console is a much larger discussion.

**Comment by kaktusus** [comment]
![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/a82a19ed-a915-4417-9118-744da5395d63)
,
```
OS: Debian GNU/Linux 12 (bookworm) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33263 (Git) AppImage
Build type: Release
Branch: master
Hash: 864f99bf984c237ef38d9451fd6f3a5ec34e6eb4
Python 3.11.3, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.2, OCC 7.7.1
Locale: Polish/Poland (pl_PL)
Installed mods: 
  * Curves 0.5.0
  * sheetmetal 0.2.56
  * Reinforcement
  * BIM 2021.12.0
```
