### ISSUE TITLE
Part Design → tree view / popup menu → Edit Thickness

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#162]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28993 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 6d92e53)
Hash: 6d92e532bcc31c99a0ab4c153ff00b6414b8f527
Python 3.9.13, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
```

Option name label without translation.

![obraz](https://user-images.githubusercontent.com/39754351/172018005-e580dd67-3337-4ada-b036-27696c54fa34.png)

If, in a tree view, I open the popup menu for this object to edit, I see an untranslated option label.
The message in the window appears to be constructed from several strings.
This case can also apply to other tools, e.g. fillet, chamfer, draft etc.
The problem was found by david69 from the FreeCAD forum.

**Comment by chennes** [comment]
It's showing the string `"Edit %1" where `%1` is the object's label (in this case "Thickness"). There is still some problem related to this, but Edit is being translated correctly. It seems the menu is not recreated when the label changes, but that's a different bug.
