### ISSUE TITLE
Code formater for C++

### ISSUE THREAD

**Issue by Kuzma30** [FreeCAD/FreeCAD-translations#163]
What code formater for C++ source code can I use?
For example I make change to code like this (one long line)
ui->pcbLineGroup->setToolTip(tr("%1 defines these line widths:\n thin: %2\n graphic: %3\n thick: %4").arg(QString::fromStdString(lgNames.at(0).substr(1)),QString::fromStdString(lgNames.at(1)),QString::fromStdString(lgNames.at(2)),QString::fromStdString(lgNames.at(3))));

**Comment by kaktusus** [comment]
Notepad++ works well under windows, it has many plugins
for Linux you might like Kate.

besides 
    1 Sublime Text
    2 Bluefish
    3 GNU Emacs
    4 Geany
    5 Gedit
    6 Brackets
    7 Atom

Many of them also have excellent plugin support.
