### ISSUE TITLE
Part Design → tree view / popup menu → Edit Fillet

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#165]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28993 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 6d92e53)
Hash: 6d92e532bcc31c99a0ab4c153ff00b6414b8f527
Python 3.9.13, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
```

If, in a tree view, I open the popup menu for this object to edit, I see an untranslated option label.

![obraz](https://user-images.githubusercontent.com/39754351/172018525-ff0d832e-ba23-4dc3-bb33-41af62dd99a0.png)

The message in the window appears to be constructed from several strings.
This case can also apply to other tools, e.g. chamfer, draft, thickness etc.
The problem was found by david69 from the FreeCAD forum.

**Comment by chennes** [comment]
See #166 - "Fillet" is the name of the object.
