### ISSUE TITLE
 Part Design → tree view / popup menu → Edit Chamfer

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#166]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28993 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 6d92e53)
Hash: 6d92e532bcc31c99a0ab4c153ff00b6414b8f527
Python 3.9.13, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
```

If, in a tree view, I open the popup menu for this object to edit, I see an untranslated option label.

![obraz](https://user-images.githubusercontent.com/39754351/172018445-ab8f2238-d177-49fd-a6ab-94770ad8508e.png)

The message in the window appears to be constructed from several strings.
This case can also apply to other tools, e.g. fillet, draft, thickness etc.
The problem was found by david69 from the FreeCAD forum.

**Comment by chennes** [comment]
It's not actually untranslated: that's the name of the object. So the underlying issue is the question of whether we should be creating those objects with translated names.

**Comment by kaktusus** [comment]
The translated label will be a good solution for users.

**Comment by Kuzma30** [comment]
@chennes  Can you review?
I propose such solution
https://github.com/Kuzma30/FreeCAD/commit/7f048de2b7ba464e04abd456f372bfffda9cd598
There is featureName() function (declared in ViewProviderDressUp class) that return "Fillet", "Chamfer", "Draft" or "Thickness".
It used for context menu 
```
act = menu->addAction(QObject::tr("Edit %1").arg(QString::fromStdString(featureName())), receiver, member);
```
and in 
```
TaskDressUpParameters::TaskDressUpParameters(ViewProviderDressUp *DressUpView, bool selectEdges, bool selectFaces, QWidget *parent)
    : TaskBox(Gui::BitmapFactory().pixmap((std::string("PartDesign_") + DressUpView->featureName()).c_str()),
              DressUpView->menuName,
              true,
              parent)
TaskDressUpParameters
```
For easy translate ability I propose add 
virtual QString getL10nContextMenuText(); for 4 class

**Comment by Kuzma30** [comment]
@chennes Need feedback, as there are many things where use same principle.

**Comment by chennes** [comment]
I don't think variant 2 is viable. In variant 1, is your idea that every class only returns a single value to be used in the context menu, rather than using the object name?

**Comment by Kuzma30** [comment]
Idea - make for all class separate context menu text (var1)

**Comment by chennes** [comment]
https://forum.freecad.org/viewtopic.php?t=77860

**Comment by kaktusus** [comment]
fixed 

```
OS: Debian GNU/Linux 12 (bookworm) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33303 (Git) AppImage
Build type: Release
Branch: master
Hash: 5b075a9938b78076fdde9034de4a05685e42690e
Python 3.10.11, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
  * Curves 0.5.0
  * sheetmetal 0.2.56
  * Reinforcement
  * BIM 2021.12.0
  * Rocket 3.1.0
```


![image](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/c11622c8-0e89-4082-9ae4-bf05e2cda32d)
