### ISSUE TITLE
Sketcher → Sketch (main menu) 

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#168]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.29085 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 1e96bbd)
Hash: 1e96bbd2815683d6afa0afe8f985cdd04ef839fe
Python 3.10.4, Qt 5.12.9, Coin 4.0.0, Vtk 9.1.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
```

The menu label has no translation.

![image](https://user-images.githubusercontent.com/39754351/173224963-f5703766-0147-4479-836c-53cfcf80e7ef.png)
Something was broken earlier this label was translated. Can be seen in submission #106

1. `Sketch` or `S&ketch` - Lack of relevant occurrence in Crowdin

    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=S&ketch

**Comment by Kuzma30** [comment]
@yorikvanhavre 
https://crowdin.com/translate/freecad/all/en-fr?filter=basic&value=0#q=&ketch
Translation is found in Complete.ts file. This .ts file not updated by updatets.py. I think it may be deleted from crowdin.

**Comment by yorikvanhavre** [comment]
Indeed. I have deleted it now. I think Ship and Plot should be moved to https://crowdin.com/project/freecad-addons at some point too

**Comment by kaktusus** [comment]
I believe that more wb can be moved to add-ons.

**Comment by kaktusus** [comment]
Still no translation

**Comment by kaktusus** [comment]
The issue is occurring again ...

...
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.29485 (Git) AppImage
Build type: Release
Branch: master
Hash: a236ca843fdd6674afb6d7ed1454fbd3b547f5ea
Python 3.10.5, Qt 5.12.9, Coin 4.0.0, Vtk 9.1.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...


![obraz](https://user-images.githubusercontent.com/39754351/183297904-6ad11c70-64c4-446f-a34d-c6619575d2ba.png)

**Comment by kaktusus** [comment]
@luzpaz are you able to reopen this submission? the problem still exists.
Corwdin does not contain a suitable string for translation.

**Comment by kaktusus** [comment]
It is interesting to note that for the PartDesign workbench this translation works correctly ...

![obraz](https://user-images.githubusercontent.com/39754351/184589046-f379486f-435f-4bd6-826a-dd5b90f8c74d.png)

https://crowdin.com/translate/freecad/564/en-pl#6589832
