### ISSUE TITLE
Inspection →  Inspection / main menu

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#175]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.29192 (Git) AppImage
Build type: Release
Branch: master
Hash: fb1a7af3605ed86631afabb1eb77ae305e418d98
Python 3.10.5, Qt 5.12.9, Coin 4.0.0, Vtk 9.1.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
```

Menu label do not have translations in the GUI.

![image](https://user-images.githubusercontent.com/39754351/174486598-0df21225-79d5-49c8-b2af-60456a9bb62f.png)

1.  `Inspection` - The string is in Crowdin but this occurrence does not apply to this case.
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Inspection

The problem was found by david69 from the FreeCAD forum.

**Comment by Kuzma30** [comment]
Inspection WB don't have .ts file at all. Need to create it.

**Comment by kaktusus** [comment]
Or move this workbench to add-ons and then create a translation file.
Does anyone use this workbench at all?

**Comment by Kuzma30** [comment]
> Or move this workbench to add-ons and then create a translation file.
I think it must be on freecad crowdin, not add-ons. It will be simple update translation in future.

**Comment by chennes** [comment]
Inspection is a C++ workbench and cannot be moved to the external Addons repository.

**Comment by chennes** [comment]
I took a look at this and although the source code has some translation calls in it, it is not included in our extracts.py script, and it does not have the appropriate translation resources directory setup. I'll add this to my to-do list.

**Comment by Kuzma30** [comment]
@chennes Can you also look why updatets.py change order of source links in .ts?

**Comment by Kuzma30** [comment]
This not related to this issues. I can create new, if you want.
@chennes Example of problem https://github.com/FreeCAD/FreeCAD/pull/7056/commits/4ccd24fe14195cf14afb95db8148a4b8641e9990
As you can see it add 3 new text near the end of files. All other changes is changing order of  "location filename"

**Comment by chennes** [comment]
I probably can't do anything about it going backwards: I could add a sort to the filenames going forward, so we only see one more order change. If you want me to look into it, file an issue in the FreeCAD repo.

**Comment by Kuzma30** [comment]
@chennes (This is issue related)
https://github.com/Kuzma30/FreeCAD/commits/add_ts latest 4 commits. Please review

**Comment by Kuzma30** [comment]
Also found that Material has't .ts file too. Add it
https://github.com/Kuzma30/FreeCAD/commit/40395a0a573c67d14f4949015ae41a739a77e0cb

**Comment by chennes** [comment]
Consolidating to #178 -- it's all the same issue. Translators should see these strings on CrowdIn now.
