### ISSUE TITLE
Inspection → Inspection menu → Inspection...

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#177]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.29192 (Git) AppImage
Build type: Release
Branch: master
Hash: fb1a7af3605ed86631afabb1eb77ae305e418d98
Python 3.10.5, Qt 5.12.9, Coin 4.0.0, Vtk 9.1.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
```

Menu label do not have translations in the GUI.

![image](https://user-images.githubusercontent.com/39754351/174487066-7124dc20-829c-4485-827b-d960a7de16bc.png)

1.  `Inspection...`  - no string in Crowdin.
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Inspection...

The problem was found by david69 from the FreeCAD forum.

**Comment by chennes** [comment]
Consolidating to #178 -- it's all the same issue. Translators should see these strings on CrowdIn now.
