### ISSUE TITLE
Inspection → Visual inspection... (tool)

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#178]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.29192 (Git) AppImage
Build type: Release
Branch: master
Hash: fb1a7af3605ed86631afabb1eb77ae305e418d98
Python 3.10.5, Qt 5.12.9, Coin 4.0.0, Vtk 9.1.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
```

No translations in the tool dialog.

![image](https://user-images.githubusercontent.com/39754351/174487995-3b206ced-d26e-4931-9c5e-0906414ccb54.png)

1.  `Visual inspection` - no string in Crowdin.
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Visual%20inspection

2.  `Actual` - no string in Crowdin.
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Actual

3.  `Nominal` - no string in Crowdin.
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Nominal

4.  `Objects` - The string is in Crowdin but this occurrence does not apply to this case.
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Objects

5.  `Parameter` - The string is in Crowdin but this occurrence does not apply to this case.
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Parameter

6.  `Search distance` - no string in Crowdin.
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Search%20distance

**Comment by chennes** [comment]
Well, our first problem is that Inspection isn't on CrowdIn at all!

**Comment by chennes** [comment]
OK, I uploaded it now, translators should be able to start. I'll submit a PR updating the script next.

**Comment by kaktusus** [comment]
When I was translating the new strings I already noticed a few deficiencies in Crowdin.

I will wait for the translations to be implemented.

**Comment by chennes** [comment]
I'm going to close this issue -- if there are individual problems with the Inspection WB let's open individual issues for those things.

**Comment by kaktusus** [comment]
![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/69eb6688-235e-4c20-918b-8bd7b4ff74ef)

```
OS: Debian GNU/Linux 12 (bookworm) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33263 (Git) AppImage
Build type: Release
Branch: master
Hash: 864f99bf984c237ef38d9451fd6f3a5ec34e6eb4
Python 3.11.3, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.2, OCC 7.7.1
Locale: Polish/Poland (pl_PL)
Installed mods: 
  * Curves 0.5.0
  * sheetmetal 0.2.56
  * Reinforcement
  * BIM 2021.12.0
  ```

No improvement, I will wait until the new build release

**Comment by kaktusus** [comment]
still requires attention
