### ISSUE TITLE
TechDraw → Tree View → popup message

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#179]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.29192 (Git) AppImage
Build type: Release
Branch: master
Hash: fb1a7af3605ed86631afabb1eb77ae305e418d98
Python 3.10.5, Qt 5.12.9, Coin 4.0.0, Vtk 9.1.0, OCC 7.5.3
```

Pop-up message has no translation.

![obraz](https://user-images.githubusercontent.com/39754351/175133183-a07c04f6-4d8f-464e-8435-aa6842868f9f.png)

1. `Cannot open file ...` - No corresponding string in Crowdin?
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Cannot%20open%20file

**Comment by chennes** [comment]
Closing in favor of https://github.com/FreeCAD/FreeCAD-translations/issues/203
