### ISSUE TITLE
Part Design → Pad (tool)

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#180]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.29365 (Git) AppImage
Build type: Release
Branch: master
Hash: 59b945dcc329303ad781075ecf30544aab909415
Python 3.10.5, Qt 5.12.9, Coin 4.0.0, Vtk 9.1.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
```

No translations in the message window.

![obraz](https://user-images.githubusercontent.com/39754351/177033095-9b68175e-3406-437f-a7fb-389ecbf502e0.png)

1.  `Wire is not closed.`- no string in Crowdin.
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Wire%20is%20not%20closed.

In addition, I can point out that the message window is too small. The description on the bar is not readable and the window cannot be stretched.
_This is a fairly common inconvenience._

**Comment by chennes** [comment]
That's another instance of us directly displaying exception text. I'm working on formulating a general solution to this issue.
