### ISSUE TITLE
Part Design → Fillet (tool)

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#181]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.29365 (Git) AppImage
Build type: Release
Branch: master
Hash: 59b945dcc329303ad781075ecf30544aab909415
Python 3.10.5, Qt 5.12.9, Coin 4.0.0, Vtk 9.1.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
```

No translations in the message window.

![obraz](https://user-images.githubusercontent.com/39754351/177033627-e94f4882-22ac-4e6d-8a5b-b3d58bae029e.png)

1.  `Failed to create fillet` - no string in Crowdin 
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Failed%20to%20create%20fillet

![obraz](https://user-images.githubusercontent.com/39754351/177033819-cb0adef4-94a2-41ee-ae94-c5402dac6f07.png)

2.  `Resulting shape is invalid` - no string in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Resulting%20shape%20is%20invalid

In addition, I can point out that the message windows is too small. The description on the bar is not readable and the windows cannot be stretched.
_This is a fairly common inconvenience._

;-)

**Comment by Kuzma30** [comment]
https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/PartDesign/App/FeatureFillet.cpp
code is here
```
return new App::DocumentObjectExecReturn("Fillet not possible on selected shapes");
```
What is untranslated description text?

**Comment by kaktusus** [comment]
My guess is that it is an input error.

**Comment by Kuzma30** [comment]
Can you locate this text in crowdin?

**Comment by kaktusus** [comment]
I tried it, without success ...

I only have so much - not sure
https://crowdin.com/translate/freecad/564/en-pl?filter=basic&value=0#q=b%C5%82%C4%85d%20danych%20wej%C5%9Bciowych

**Comment by kaktusus** [comment]
![obraz](https://user-images.githubusercontent.com/39754351/177249874-4b5a7cff-c5f4-45a7-8662-e01495e23630.png)
![obraz](https://user-images.githubusercontent.com/39754351/177249968-1b12a0c8-45fb-405f-9c38-6fb066ad2d9e.png)
![obraz](https://user-images.githubusercontent.com/39754351/177250015-42637bd9-87d5-4d0d-8631-bff871939d1c.png)

**Comment by kaktusus** [comment]
When you change the filter parameters to _all strings_ get a large number of strings "input error" with hidden attribute

**Comment by chennes** [comment]
These are exceptions being shown to the user. Closing this issue in favor of https://github.com/FreeCAD/FreeCAD-translations/issues/203
