### ISSUE TITLE
Translation: "displacement" in ship.ts and fem.ts have different meaning and need differentiation in the sourcecode

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD-translations#187]
Issue imported from https://tracker.freecad.org/view.php?id=3902

* **Reporter:** kazan417
* **Date submitted:** 3/12/2019
* **FreeCAD version:** 0.18
* **Category:** General
* **Status:** new
* **Tags:** FEM, ship, translation

# Original report text

I found some bad translation in fem.ts. First of all displacement (водоизмещение) automatically copied by crowdin from ship.ts, but here should be different word - смещение. This is true for many languages, not just Russian.
I think we can solve it by changing "displacement" in ship.ts source string to "ship displacement"

# Other bug information

* **Priority:** normal
* **Severity:** text
* **Category:** General
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by kazan417 2019-03-12 17:12
https://forum.freecadweb.org/viewtopic.php?f=10&t=32573&p=291900#p291900

**Comment by chennes** [comment]
This does not seem relevant now: FEM does not contain the simple string "displacement", as far as I can tell, only things like "displacement X". The context does appear to be correct everywhere I looked, and CrowdIn is supplying different translation strings as expected. If the problem re-appears please re-open this Issue.
