### ISSUE TITLE
FreeCAD → Edit → Preferences ... → Import_Export / IGES & STEP (tab)

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#189]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.30089 (Git) AppImage
Build type: Release
Branch: master
Hash: 335196a468fcf069f365dcbb24279a8295cc4683
Python 3.10.5, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.2
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

The label has no translation in the GUI.

![obraz](https://user-images.githubusercontent.com/39754351/184581870-8d682279-3378-431e-8aa5-191f566dcb74.png)
![obraz](https://user-images.githubusercontent.com/39754351/184581959-fd17b662-99a4-4cfb-8a50-9129dd9ef108.png)

1. `Export` - Crowdin contains several hidden occurrences but none match - no string in Crowdin.
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Export

**Comment by Kuzma30** [comment]
This is crowdin related problem. 
We have it in .ts but not in crowdin server.
https://github.com/FreeCAD/FreeCAD/blob/283fec68f87e7797e3f37f6485e6d08b68ff01a4/src/Mod/Part/Gui/Resources/translations/Part.ts#L3131
https://github.com/FreeCAD/FreeCAD/blob/283fec68f87e7797e3f37f6485e6d08b68ff01a4/src/Mod/Part/Gui/Resources/translations/Part.ts#L3228

**Comment by Kuzma30** [comment]
![Screenshot_20220826_094640](https://user-images.githubusercontent.com/1382812/186840014-1955aabb-a75b-4fde-a2be-48774a7566d6.png)
On my test server

**Comment by chennes** [comment]
These are both showing up translated for me (I tested Español)
```
OS: macOS 13.2
Word size of FreeCAD: 64-bit
Version: 0.21.0.32240 (Git)
Build type: Release
Branch: pr8826
Hash: 75808785c909acebd8a0283668ce683673f0d266
Python 3.10.9, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.7.0
Locale: English/United States (en_US)
```
