### ISSUE TITLE
FreeCAD → Edit → Preferences ... → General → Units  → Units settings

### ISSUE THREAD

**Issue by FreeCAD-Tools** [FreeCAD/FreeCAD-translations#190]
![изображение](https://user-images.githubusercontent.com/90561109/186499149-1ae5ad10-1e2f-489e-bca3-8e191e37b166.png)

This string exists in crowdin, but for some reason there is no effect in the interface. 

![изображение](https://user-images.githubusercontent.com/90561109/186499657-42a27780-50ba-495e-9da1-8eaf6b5a6653.png)

The translation was updated several times with no result.

![изображение](https://user-images.githubusercontent.com/90561109/186502258-2e8cdb58-699f-4189-9890-e955405e42dc.png)

**Comment by kaktusus** [comment]
`FEM (mm, N, sec)`

https://crowdin.com/translate/freecad/549/en-pl#6584644

**Comment by Kuzma30** [comment]
Here is error place
https://github.com/FreeCAD/FreeCAD/blob/283fec68f87e7797e3f37f6485e6d08b68ff01a4/src/Base/UnitsApi.cpp#L84
It return "FEM (mm, N, s)"; while in 
https://github.com/FreeCAD/FreeCAD/blob/283fec68f87e7797e3f37f6485e6d08b68ff01a4/src/Gui/DlgSettingsUnitsImp.cpp#L52
we have FEM (mm, N, sec)
ping @chennes Can you fix this? I can't make PR now

**Comment by FreeCAD-Tools** [comment]
Because the request is primitive, I tried to add it myself.

**Comment by Kuzma30** [comment]
Better change text in UnitsApi. As you can see (few lines upper)FreeCAD use "sec".

**Comment by FreeCAD-Tools** [comment]
> Better change text in UnitsApi. As you can see (few lines upper)FreeCAD use "sec".

![изображение](https://user-images.githubusercontent.com/90561109/189484056-2cd62cc9-674e-45e6-b7b7-10f5e2a90f94.png)

Standart and MKS use 's'. 'sec' use only Civil Imperial.

**Comment by Kuzma30** [comment]
We need use one term in all place. After searching in SI I agree that  "s" is correct.

**Comment by kaktusus** [comment]
the string appeared in Crowdin
again

**Comment by chennes** [comment]
It's on the first page of preferences, near the top.

**Comment by kaktusus** [comment]
yes ...
general tab
thanks for the hint, I couldn't see it

**Comment by kaktusus** [comment]
by the way

It would be useful to have some import of signs to Crowdin.
There are very many changes that do not have translations also in the preferences
