### ISSUE TITLE
FEM → Model → Fluid Constrains → Constraint flow velocity 

### ISSUE THREAD

**Issue by FreeCAD-Tools** [FreeCAD/FreeCAD-translations#191]
![изображение](https://user-images.githubusercontent.com/90561109/186501499-011f1164-15f9-42d0-aaa5-806653548de2.png)

This string exists in crowdin, but for some reason there is no effect in the interface. The translation was updated several times with no result.

![изображение](https://user-images.githubusercontent.com/90561109/186848500-16c0ace7-0d14-493c-9fbf-a5999c6510da.png)

**Comment by FreeCAD-Tools** [comment]
Mistake in:

https://github.com/FreeCAD/FreeCAD/blob/5d49bf78de785a536f941f1a6d06d432582a95d3/src/Mod/Fem/femguiutils/selection_widgets.py#L280-L282

in the Python script, the String is divided into three parts but in crowding it is whole.

https://crowdin.com/translate/freecad/559/en-ru?filter=basic&value=0#q=Geometry

Click on "Add" and select geometric elements to add them to the list.{}The following geometry elements are allowed to select: {}{}{}

**Comment by FreeCAD-Tools** [comment]
https://github.com/FreeCAD/FreeCAD/blob/5d49bf78de785a536f941f1a6d06d432582a95d3/src/Mod/Fem/femguiutils/selection_widgets.py#L274

is fixed by commit

https://github.com/FreeCAD-Tools/FreeCAD/commit/582621b3bcb49b79d66adeee75ff7b18f4ab8134#diff-117d8794a4e67a859f633065357fedc6a593657f23858fae9a63d485e09f1bad

But for some reason the changes are not merged

**Comment by FreeCAD-Tools** [comment]
Can anyone fix this?

**Comment by Kuzma30** [comment]
@FreeCAD-Tools use master branch for checking
https://github.com/FreeCAD/FreeCAD/blob/4310b49a8b2b704f1ce22a52fcb5806531d5a2d1/src/Mod/Fem/femguiutils/selection_widgets.py#L275
