### ISSUE TITLE
FreeCAD → Edit → Preferences ... → TechDraw / Dimensions (tab)

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#193]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.30121 (Git) AppImage
Build type: Release
Branch: master
Hash: 9c929897ac46f2309e2bf34b7106f49fcb737a1d
Python 3.10.5, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.2
Locale: Polish/Poland (pl_PL)
Installed mods: 
```

No translation of options in the GUI

![obraz](https://user-images.githubusercontent.com/39754351/187141923-dd6dfdc8-6cde-4d1f-a047-0d26401807c4.png)

1. `Extension Gap Factor - ISO`  - no string in Crowdin.

2.  `Extension Gap Factor - ASME`  - no string in Crowdin.

    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Extension%20Gap%20Factor

**Comment by Kuzma30** [comment]
I can't found this strings in source code.

**Comment by kaktusus** [comment]
the strings appeared in Crowdin
