### ISSUE TITLE
FEM → Clipping plane on face (tool)

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#197]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.30492 (Git) AppImage
Build type: Release
Branch: master
Hash: b4578fb3eae842eb510a1bc055d07d369a67ce94
Python 3.10.6, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...

```

a strange situation has arisen ...
String is currently translated but is now not present in Crowdin.

![obraz](https://user-images.githubusercontent.com/39754351/194689060-29ac2a01-e020-44bb-b30f-b065515796c1.png)

![obraz](https://user-images.githubusercontent.com/39754351/194689133-7ed6d420-ef56-439a-8afb-553f726b66d2.png)

1. `Clipping plane on face` - No string in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Clipping%20plane%20on%20face

2. `Add clipping plane on a selected face` - no string in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Add%20clipping%20plane%20on%20a%20selected%20face

The glitch was found by David69 from the FreeCAD forum.

_A similar situation occurs with other utilities from the **tool menu** of this workbench._

**Comment by luzpaz** [comment]
Weird, looks like its formatted correctly:  
https://github.com/FreeCAD/FreeCAD/blob/69c95e3fc0957a152f96389b0726dff4f35240b6/src/Mod/Fem/femcommands/commands.py#L84-L88

**Comment by kaktusus** [comment]
I might also add that I expect more problems like this to occur
a long time ago, after some import to Crowdin, the Fem.ts file got a lot smaller in terms of the number of translation strings it contains

**Comment by luzpaz** [comment]
>  a long time ago, after some import to Crowdin, the Fem.ts file got a lot smaller in terms of the number of translation strings it contains

I wonder if we can track the commit down in which this happened?

**Comment by kaktusus** [comment]
it's going to be difficult, I didn't pay attention to it
I will try to trace my old conversations with translator friends.

**Comment by kaktusus** [comment]
I found two mentions in my conversations on a similar topic

it could be around Nov 17th, 2021

this date also does not coincide with my whining here:

https://github.com/FreeCAD/FreeCAD-translations/issues/94#issuecomment-1120184612

and I bet on the latter occurrence that it is more likely this date ....

**Comment by luzpaz** [comment]
@donovaly IIRC you were making large edits to FEM source around that time?

**Comment by donovaly** [comment]
> @donovaly IIRC you were making large edits to FEM source around that time?

Yes, but I cannot see a bug in the line where the string is defined. I changed now its formatting:
https://github.com/FreeCAD/FreeCAD/commit/459f6bd476

> Add clipping plane on a selected face - no string in Crowdin

The string is :
"Add a clipping plane on a selected face"
(note the "a")

**Comment by kaktusus** [comment]
Fixed.

![obraz](https://user-images.githubusercontent.com/39754351/236656410-a8e2c3f6-9754-4197-a1a2-8219e2172e97.png)

However, the tool icon is missing 
Can anyone check if it has a similar effect?

**Comment by chennes** [comment]
I can confirm your missing icon.

**Comment by kaktusus** [comment]
Fixed.


```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33458 (Git) AppImage
Build type: Release
Branch: master
Hash: 8b89dd29d2382c72d738c52e8974216130ffa9db
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
  * Curves 0.5.0
  * sheetmetal 0.2.56
  * Reinforcement
  * BIM 2021.12.0
  * Rocket 3.1.0
  * kicadStepUpMod 10.19.4
  * fasteners 0.4.56
```


![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/a1897259-15db-4a34-8e79-6f02c43b2253)
