### ISSUE TITLE
Part design -> main menu

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#2]
```
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.24992 (Git) AppImage
Build type: Release
Branch: master
Hash: 9332e52d944c1339e3b9a1b5a72dc6edc6d077a8
Python version: 3.9.4
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: Polish/Poland (pl_PL)
```
![obraz](https://user-images.githubusercontent.com/39754351/120902283-bd885580-c63f-11eb-8243-50a6766454ac.png)
No translation for the "Measure" menu.
When other WBs are loaded, the menu has a localized translation.

**Comment by luzpaz** [comment]
Related to #6

**Comment by kaktusus** [comment]
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: **0.20.25157** (Git) AppImage
Build type: Release
Branch: master
Hash: 257cdd8f423f1530b8df6f53e242de629fee4e85
Python version: 3.9.5
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: Polish/Poland (pl_PL)


![obraz](https://user-images.githubusercontent.com/39754351/124386052-a721f800-dcd8-11eb-9edc-4639e581c159.png)


Fixed.
