### ISSUE TITLE
MeshDesign →Meshes (menu)→ Unwrap Face (tool)

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#201]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.31109 (Git) AppImage
Build type: Release
Branch: master
Hash: c23ee7ad88433a0f00e84afae0a62fe738be0c09
Python 3.10.8, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

Utility label do not have translations in the GUI.

![obraz](https://user-images.githubusercontent.com/39754351/208289093-e2a408ac-ab70-4857-8a8c-f4869be19796.png)

1.  `Unwrap Face` - No string in Crowdin.

    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Unwrap%20Face

it was already mentioned earlier [#54](https://github.com/FreeCAD/FreeCAD-translations/issues/54)

I will ask in passing:

Will this tool be removed in the near future?
Is there even such a plan?

**Comment by Kuzma30** [comment]
https://github.com/FreeCAD/FreeCAD/blob/856af2a12287a2d7c0d5ab23646be43af26b14b1/src/Mod/MeshPart/Gui/MeshFlatteningCommand.py#L45-L48

https://github.com/FreeCAD/FreeCAD/blob/856af2a12287a2d7c0d5ab23646be43af26b14b1/src/Mod/MeshPart/Gui/MeshFlatteningCommand.py#L77-L80

@chennes Is MeshPart_FlatteningCommand context correct? Or it will be MeshPart_CreateFlatMesh and MeshPart_CreateFlatFace as declared https://github.com/FreeCAD/FreeCAD/blob/856af2a12287a2d7c0d5ab23646be43af26b14b1/src/Mod/MeshPart/Gui/MeshFlatteningCommand.py#L115-L116

Another question/ In line
https://github.com/FreeCAD/FreeCAD/blob/856af2a12287a2d7c0d5ab23646be43af26b14b1/src/Mod/MeshPart/Gui/MeshFlatteningCommand.py#L80
this is copy/paste error? and it must be "Find a flat representation of a face."??

**Comment by chennes** [comment]
> @chennes Is MeshPart_FlatteningCommand context correct? Or it will be MeshPart_CreateFlatMesh and MeshPart_CreateFlatFace as declared

I thought the context strings had to match there, but I see that for example Part "Boolean XOR" does not work like that. Is its translation working correctly?

**Comment by kaktusus** [comment]
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=XOR

no string in Crowdin

**Comment by Kuzma30** [comment]
After better research I think problem is here
https://github.com/FreeCAD/FreeCAD/commit/d87fd4d97e600c0753145da5b8706376173781fd
There are many deleted strings (not only "Unwrap Face"). Look like @yorikvanhavre use old script or software for update ts.

**Comment by Roy-043** [comment]
The translation context for these commands is wrong. It should be the command name.
See: https://wiki.freecadweb.org/Translating_an_external_workbench#Inside_each_FreeCAD_command_class

> this is copy/paste error? and it must be "Find a flat representation of a face."??

Yes

I'll do a PR.

**Comment by kaktusus** [comment]
string came in for translation yesterday at Crowdin
