### ISSUE TITLE
Crowdin Scripts wiki page is out of date and inconsistent

### ISSUE THREAD

**Issue by ronnystandtke** [FreeCAD/FreeCAD-translations#202]
I wanted to learn and understand how the Crowdin scripts are supposed to be used and found this wiki page:
https://wiki.freecad.org/Crowdin_Scripts
Unfortunately, this page seems to be quite out of date (the updatefromcrowdin.py script doesn't exist anymore, the token file name is different from the one in the actual script, ...) and inconsistent (first stating that these scripts are run from the root of the FreeCAD/ directory and then running cd /path/to/freecad-source-code/src/Tools in the examples below).

Someone who is more familiar with the scripts should probably update this page.

See https://github.com/FreeCAD/FreeCAD/pull/9275 for more details.

**Comment by luzpaz** [comment]
I'd be happy to help here.

**Comment by yorikvanhavre** [comment]
The whole FreeCAD translation process should indeed be heavily rewritten.. And also include the homepage translation.
I'll have a look at it

**Comment by chennes** [comment]
I started putting developer information in the Handbook [here](https://github.com/FreeCAD/DevelopersHandbook/blob/master/technical/translation.md).

**Comment by chennes** [comment]
I consider the [Handbook page on translation](https://github.com/FreeCAD/DevelopersHandbook/blob/master/technical/translation.md) the authoritative source now, so I'm going to close this Issue. There is of course still work to be done on that page, and I welcome both Pull Requests and Issues filed there.

**Comment by kaktusus** [comment]
As always, good job. :trophy: 
You didn't even forget a few words about HTML tags. It's really annoying and unwelcome.

**Comment by kaktusus** [comment]
As always, good job. :trophy: 
You didn't even forget a few words about HTML tags. It's really annoying and unwelcome.
