### ISSUE TITLE
Missing toolbar strings

### ISSUE THREAD

**Issue by cehjan** [FreeCAD/FreeCAD-translations#206]
I am translating FreeCAD into the Serbian language (Latin and Cyrillic) and I noticed that certain toolbar strings are missing.

Sketcher workbench

Constrain horizontal distance
![constrain](https://user-images.githubusercontent.com/131595212/233971852-9088538d-6ff7-4570-9f94-fe318400199b.jpg)

Create arc
![arc](https://user-images.githubusercontent.com/131595212/233971867-39a17c63-1e1f-4f81-abbc-875b49c6cd5a.jpg)

**Comment by kaktusus** [comment]
Can you find this string in Crowdin?
Paste the link here, I expect that the translation was messed up - someone saved the untranslated string.
