### ISSUE TITLE
Misspelled language name in Preferences

### ISSUE THREAD

**Issue by cehjan** [FreeCAD/FreeCAD-translations#207]
I am translating FreeCAD into the Serbian language (Latin and Cyrillic) and I noticed that  in Preferences/General/Language the name of the Serbian Latin translation was written incorrectly. Both language names are written in Cyrillic, and one version of the translation should be in Cyrillic and the other in Latin.

Serbian latin version is – Srpski
Serbian cyrillic version is - Српски 

![preferences](https://user-images.githubusercontent.com/131595212/233973806-84b6321d-a24a-4d2d-933b-00662a85069b.jpg)

**Comment by chennes** [comment]
I can see that our translation files from CrowdIn are coding Serbian (Latin) as sr-CS, rather than sr_Latn, which is the root of the problem. QLocale does not seem to treat CS as (the country code) as entailing Latn, the script code. I can manually code in a fix, but that seems pretty awful. @yorikvanhavre, any thoughts on a better answer?

**Comment by yorikvanhavre** [comment]
It comes that way from crowdin ( hovering the mouse over the flags in https://crowdin.com/project/freecad shows the language code they use)... Might be useful to file an issue at crowdin about that?

But I think the main problem is rather here: https://github.com/FreeCAD/FreeCAD/blob/master/src/Gui/Language/Translator.cpp#L169 The string "Serbian, Latin" is translated by Qt in cyrillic :disappointed:

**Comment by chennes** [comment]
@yorikvanhavre if I manually transform sr-CS to sr_Latn, Qt does the translation correctly (in Latin characters). We can tell CrowdIn to do that mapping for us, it appears. I will experiment with that.

**Comment by chennes** [comment]
Well, trying to tell CrowdIn to change the mapping didn't appear to have any effect. So we can do the mapping from sr-CS -> sr_Latn in the function that does the menu construction, or in the tools that pull the data from CrowdIn. If we do it in the tools, we'll have to change all the QM files and QRC files. I'll make a PR that does the first, and we can see just how awful everyone thinks it is.
