### ISSUE TITLE
OpenSCAD → main menu / View / Toolbars

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#210]
```
OS: Debian GNU/Linux 12 (bookworm) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.32985 (Git) AppImage
Build type: Release
Branch: master
Hash: 5cd377f931312ede305e4c764ba2028b20eaacfd
Python 3.10.10, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods:
```

Toolbar names have no translations ...

![image](https://user-images.githubusercontent.com/39754351/234894408-0aba9296-da4a-4139-867b-4042137e682f.png)

1. `OpenSCAD Tools` - the string is found in Crowdin no translation in the GUI
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=OpenSCAD%20Tools

2. `Frequently-used Part WB tools` - the string is found in Crowdin no translation in the GUI
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Frequently

**Comment by chennes** [comment]
Are you seeing any translations in OpenSCAD at all? For me the whole OpenSCAD menu is untranslated, as are its task panels. So I think there is something bigger wrong there.

**Comment by kaktusus** [comment]
There is no reason to complain, the entire menu is translated also the toolbar.

![image](https://user-images.githubusercontent.com/39754351/235032088-4bf33100-32b7-46ed-8e5f-07d50dc98cbf.png)

**Comment by yorikvanhavre** [comment]
https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/OpenSCAD/InitGui.py#L156
`QT_TRANSLATE_NOOP("Workbench", "Frequently-used Part WB tools"), parttoolbarcommands`
Maybe the context is wrong? Not sure anymore...

**Comment by chennes** [comment]
I think "Workbench" is the correct context: https://github.com/FreeCAD/FreeCAD/blob/4d076a70568403f87c33d403835810053ef97aaf/src/Gui/MenuManager.cpp#L273

**Comment by chennes** [comment]
OK, I see. I was testing Spanish (I don't speak any Polish!) -- Polish looks fine. Both of those strings appear to be getting translated for me now: @kaktusus can you confirm?

**Comment by kaktusus** [comment]
when I run *FreeCAD_weekly-builds-32926-2023-04-29-conda-Linux-x86_64-py311.AppImage* in the release information I have:
![image](https://user-images.githubusercontent.com/39754351/235338313-6ff3506b-56ab-467e-be7f-f4a93d188985.png)
note the date of release

there translations are okay

![image](https://user-images.githubusercontent.com/39754351/235338603-6fd651f7-a976-4568-873b-732478c48c30.png)


but when I run the:
*FreeCAD_weekly-builds-32985-2023-04-27-conda-Linux-x86_64-py310.AppImage*
by date older release
![image](https://user-images.githubusercontent.com/39754351/235338499-93bdb0a0-281d-47d5-9257-9425ed7d1fd0.png)

no translation updates there.

The date markings in the file name are completely different from what FreeCAD shows
One can get lost ...

Submission to close. ;-)

**Comment by kaktusus** [comment]
hahaha

in this release we have instead untranslated other toolbar names and I was under the impression that this was fixed earlier.
I mean:
`Edit`
`Clipboard`
`Structure`
`Help `

**Comment by kaktusus** [comment]
Exactly biuld *FreeCAD_weekly-builds-32985-2023-04-27-conda-Linux-x86_64-py310.AppImage* has better translated this part of the release.
Who should I congratulate for the super results? 
D-)

**Comment by kaktusus** [comment]
> Are you seeing any translations in OpenSCAD at all? For me the whole OpenSCAD menu is untranslated, as are its task panels. So I think there is something bigger wrong there.

The new release broke down the translations of the tools in the menu.
FreeCAD_weekly-builds-33040-2023-04-30-conda-Linux-x86_64-py311.AppImage

**Comment by kaktusus** [comment]
Version: 0.21.0.33303 (Git) AppImage

fixed
