### ISSUE TITLE
Path → main menu / View / Toolbars

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#211]
```
OS: Debian GNU/Linux 12 (bookworm) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.32985 (Git) AppImage
Build type: Release
Branch: master
Hash: 5cd377f931312ede305e4c764ba2028b20eaacfd
Python 3.10.10, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods:
```

Toolbar names have no translations ...

![image](https://user-images.githubusercontent.com/39754351/234896319-30788e48-3fc1-4baf-ac96-98a729b82b79.png)

1. `Project Setup`  - no string in Crowdin.
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Project%20Setup

2. `Tool Commands`  - no string in Crowdin.
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Tool%20Commands

3. `New Operations`  - no string in Crowdin.
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=New%20Operations

4. `Path Modification`  - no string in Crowdin.
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Path%20Modification

**Comment by chennes** [comment]
These strings should all be available in CrowdIn now.

**Comment by kaktusus** [comment]
You are amazing.
