### ISSUE TITLE
Raytracing → main menu / View / Toolbars

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#212]
```
OS: Debian GNU/Linux 12 (bookworm) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.32985 (Git) AppImage
Build type: Release
Branch: master
Hash: 5cd377f931312ede305e4c764ba2028b20eaacfd
Python 3.10.10, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods:
```

Toolbar names have no translations ...

![image](https://user-images.githubusercontent.com/39754351/234898412-37c5ebe1-7609-458e-bf85-5762d707b848.png)

`Raytracing tools` - no string in Crowdin.
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Raytracing%20tools

**Comment by chennes** [comment]
I've proposed removing this Workbench entirely.

**Comment by kaktusus** [comment]
Will be available as external workbench?

nothing prevents you from polishing it ;-)

**Comment by chennes** [comment]
Its replacement, Render, is an external WB.
