### ISSUE TITLE
FreeCAD → main menu / Edit / Preferences

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#213]
```
OS: Debian GNU/Linux 12 (bookworm) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.32985 (Git) AppImage
Build type: Release
Branch: master
Hash: 5cd377f931312ede305e4c764ba2028b20eaacfd
Python 3.10.10, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
```

Labels of some workbench have no translations ...

![image](https://user-images.githubusercontent.com/39754351/234902882-dc4952ff-db50-4484-a127-d88b9935bb2b.png)

1. `Addon Manager`
2. `TechDraw`
3. `Draft`
4. `Path`
5. `Raytracing`
6. `Spreadsheet`

Is it possible to provide two lines per signature for selected items?

eg:
https://crowdin.com/translate/freecad/549/en-pl#6498640
https://crowdin.com/translate/freecad/563/en-pl#6600898

**Comment by chennes** [comment]
I thought that we didn't translate workbench names?

**Comment by kaktusus** [comment]
Some do not want to translate others prefer to have everything translated.
I'm not the only one who pays attention to this.
In any case, I think it's worth systematizing.

**Comment by chennes** [comment]
Linked to the main FreeCAD repo issue https://github.com/FreeCAD/FreeCAD/issues/5548

**Comment by chennes** [comment]
PR https://github.com/FreeCAD/FreeCAD/pull/9614 Fixes this for the Preferences dialog, anyway.

**Comment by kaktusus** [comment]
fixed

Version: 0.21.0.33303 (Git) AppImage
