### ISSUE TITLE
Path → main menu / Path ...

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#214]
I have a __general inquiry__ about what happened to GUI translations for this workbench.
No translations have been available for some time.

**Comment by chennes** [comment]
I looked into this tonight: the Qt utility that extracts the translatable strings (lupdate) is hanging on one of the files in Path (src/mod/Path/Path/Post/UtilsArguments.py), which then times out for Path. So on CrowdIn Path.ts is only showing 537 translatable strings, when there are actually more like 1500. I'll push new ts files.
