### ISSUE TITLE
FreeCAD → Navigation cube

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#216]
```
OS: Debian GNU/Linux 12 (bookworm) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33040 (Git) AppImage
Build type: Release
Branch: master
Hash: 1e830a8800156097ccb3ef6124dced30d4002e76
Python 3.11.3, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.2, OCC 7.7.0
Locale: Polish/Poland (pl_PL)
Installed mods: 
```

Context menu labels without translations.

![image](https://user-images.githubusercontent.com/39754351/235894040-4462f334-ff8d-4cdb-ae16-8f51adf9ba8e.png)

`Movable navigation cube` -  - no string in Crowdin.

https://crowdin.com/translate/freecad/564/en-srcs?filter=basic&value=0#q=Movable%20navigation%20cube

The problem of lack of translation was found by David69 from the forum.

**Comment by chennes** [comment]
That string is brand new, it should be in the next upload, which will be in a day or two.

**Comment by chennes** [comment]
OK, I just pushed new TS files, you should see this string in FreeCAD.ts now.
