### ISSUE TITLE
FreeCAD → main menu / Open ...

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#217]
```
OS: Debian GNU/Linux 12 (bookworm) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33110 (Git) AppImage
Build type: Release
Branch: master
Hash: 18e40941ceb36c52701a7c74ea26043ef3385701
Python 3.11.3, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.2, OCC 7.7.1
Locale: Polish/Poland (pl_PL)
Installed mods: 
```

Opening the obj file.
Not all labels are translated

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/fe14fa36-e6b8-4c06-9476-2249650a70d0)

1. `Alias mesh (Mesh)` - no string in Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Alias%20mesh%20(Mesh)

2. `Wavefront OBJ - Arch module (importOBJ)` - no string in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Wavefront%20OBJ%20-%20Arch%20module%20(importOBJ)

At this point it is impossible to cancel the option. Cannot close the dialog box.

**Comment by kaktusus** [comment]
Interesting situation because I also can't find the already translated string `Otwórz obj jako`.

https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Otw%C3%B3rz%20obj%20jako

**Comment by chennes** [comment]
The inability to close the dialog box is a separate bug (obviously). I suggest a Problem report in https://github.com/FreeCAD/FreeCAD, it will get lost here.

**Comment by xtemp09** [comment]
I propose not to translate those strings. kaktusus, how would you translate Wavefront OBJ into Polish? Or Alias Mesh?

**Comment by kaktusus** [comment]
Note that the strings are longer and do not include only this specific proper name.

**Comment by xtemp09** [comment]
Alright, how would you translate those strings into Polish?

**Comment by kaktusus** [comment]
I can imagine this translation so that the author's intention is clear to the vast majority of users.
And especially for those who are not advanced.

**Comment by xtemp09** [comment]
kaktusus, I've also translated strings on Crowdin. If these strings show up there, I'll have to translate them too. I can't imagine how to translate them. How would you translate them into Polish?

**Comment by kaktusus** [comment]
What language do you support?

If you see fit you can always leave the original content as a translator, you make the decision.
Polish translations are edited by a team of translators so sometimes it is easier.
And sometimes there are many different opinions.
If you have the support of the user community it also sometimes helps. Have you tried asking on the forum? There is a subforum for users of your nation?

**Comment by xtemp09** [comment]
> What language do you support?

Russian

Why do you keep not answering the question? I asked you twice a plain simple straightforward question. Why do you keep not answering it?

# How would you translate those strings into Polish?

If they show up in Crowdin I'll keep them as they are, since they are import modules.

**Comment by chennes** [comment]
Since the solution will have to be completely general here (it will apply to all imports and exports, of all types), it's actually not so bad: in this particular case the translation is only semi-useful, but possibly in some others it will make more sense. We have previously discussed that Workbench names should be made available to translators so that the team for each language can determine whether or not to translate, so at the very least the second part of the string should get translated. It won't be possible to guarantee that the strings are always available because Addons can configure themselves to support import types (and will often not provide translations), but I can at least call `tr()` on each string and see if there is something available.

The question then becomes, what context to use? "Alias Mesh" already exists with a `QObject` context, for example. But for the rest of the strings here, there isn't an obvious choice.

**Comment by chennes** [comment]
If you have a look at the PR linked just above, you'll see that in many cases it does make sense to translate these strings. I've omitted those that contained nothing but the name of a software package (.e.g. there is nothing to translate in "Collada (*.dae)").

**Comment by kaktusus** [comment]
In general, this dialog is very specific. If the displayed texts are translated literally a bunch of nonsense will come out.

This is a case where translators _(who are interested, of course)_ can be inventive and do the translation so that the messages are actually understandable to the user. And so that the user knows what actions will be taken by the program _(learned the programmer's intentions)_.

:walking_man: :walking_man: :walking_man: :walking_man: :walking_man: 


In this case, FreeCAD will perform an implicit conversion of the file to open.
So the title of the window can be translated better `select module to import file`.
if this caption is done well (more informative) the next one may seem negligible `open obj file in workbench by function:`
Of course, one may wonder whether such in-depth knowledge is needed by the user. Does he need to know what function will import his file?

Here the eternal dilemma arises: 
the programmer often knows what his code does and the user does not necessarily. He has to rely on the messages that the programmer provides. The programmer, in turn, when creating code, treats the quality of the messages as an unwanted child because he doesn't have time for it because he is focused on other goals. So initially the message is created in a modest version _(the programmer thinks now I will do it like this - temporarily and someday I will improve it when there is more time)_. Such a course of action can lead to an effect similar to the one obtained now.

Of course, this is just an assumption and I don't have to be right.

So judge for yourself how much truth there is in this.

The situation can be complicated by the fact that the same strings can be used in yet another place.  But that's a different topic.

@chennes  thanks you for your willingness to fix everything you can and your open mind. :wink:

**Comment by kaktusus** [comment]
fixed

Version: 0.21.0.33303 (Git) AppImage

Dialog box has been removed.

**Comment by kaktusus** [comment]
I followed the same steps as before.
I use Appimage and did not change anything myself.
Now it simply followed the loading of this model without any unnecessary questions.

**Comment by kaktusus** [comment]
I understand and thank you for the clarification.
:wink:

**Comment by kaktusus** [comment]
Today I was able to test the new import.
Opening of `obj` files is done without additional window.
However, you could work on trying to translate some of the labels from the new import window.

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/13804a40-05f4-4998-a717-5f0a159d65e7)

**Comment by kaktusus** [comment]
Should I open a new ticket?

**Comment by chennes** [comment]
No, i have an in-progress PR that will resolve that for all file types, but it will not merge before 0.21, it is too complex.

**Comment by kaktusus** [comment]
I understand
thank you for the information.

**Comment by kaktusus** [comment]
closing 
functionality has been changed and translations adjusted
