### ISSUE TITLE
 Sketcher → task window → constraints section / object pop-up menu

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#218]
```
OS: Debian GNU/Linux 12 (bookworm) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33110 (Git) AppImage
Build type: Release
Branch: master
Hash: 18e40941ceb36c52701a7c74ea26043ef3385701
Python 3.11.3, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.2, OCC 7.7.1
Locale: Polish/Poland (pl_PL)
Installed mods: 
```

The object pop-up menu has untranslated option labels

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/b162de3c-b729-4bf1-a86d-7bfc0731cf09)

1. `Select elements` - no string in Crowdin

    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Select%20elements

**Comment by chennes** [comment]
I believe this is completed now.

**Comment by kaktusus** [comment]
done
