### ISSUE TITLE
Sketcher → task window → elements section / object pop-up menu & sub menu

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#219]
```
OS: Debian GNU/Linux 12 (bookworm) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33110 (Git) AppImage
Build type: Release
Branch: master
Hash: 18e40941ceb36c52701a7c74ea26043ef3385701
Python 3.11.3, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.2, OCC 7.7.1
Locale: Polish/Poland (pl_PL)
Installed mods: 
```

The object pop-up menu has untranslated option labels

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/03f1037d-f363-4b01-806b-f55d59803b6c)

1. `Point Coincidence` - no string in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Point%20coincidence

2. `Point on object` - string is in Crowdin
    https://crowdin.com/translate/freecad/569/en-pl#6590727

3. `Vertical Constraint` - no string in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Vertical%20Constraint

4. `Horizontal Constraint` - no string in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Horizontal%20Constraint

5. `Parallel Constraint` - no string in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Parallel%20Constraint

6. `Perpendicular Constraint` - no string in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Perpendicular%20Constraint

7. `Tangent Constraint` - no string in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Tangent%20Constraint

8. `Equal length` - no string in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Equal%20length

9. `Symmetric` - string is in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Symmetric

10. `Block Constraint` - string is in Crowdin in the dictionary
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Block%20Constraint

11. `Lock Constraint` - no string in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Lock%20Constraint

12. `Horizontal Distance` - string is in Crowdin
    https://crowdin.com/translate/freecad/569/en-pl#6590743

13. `Vertical Distance` - string is in Crowdin
    https://crowdin.com/translate/freecad/569/en-pl#6590745

14. `Length Constraint` - string is in Crowdin
    https://crowdin.com/translate/freecad/569/en-pl#6590745

15. `Radius Constraint` - no string in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Radius%20Constraint

16. `Diameter Constraint` - no string in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Diameter%20Constraint

17. `Radiam Constraint` - no string in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Radiam%20Constraint

18. `Angle Constraint` - string is in Crowdin in the dictionary
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Angle%20Constraint

19. `Toggle construction line` - no string in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Toggle%20construction%20line

20. `Select Constraints` - no string in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Select%20Constraints

21. `Select Origin` - string is in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Select%20Origin

22. `Select Horizontal Axis` - string is in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Select%20Horizontal%20Axis

23. `Select Vertical Axis` - string is in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Select%20Vertical%20Axis

24. `Layer 0` - no string in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Layer%200

25. `Layer 1` - no string in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Layer%201

26. `Hidden` - String is in Crowdin but does not apply to this occurrence
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Hidden

**Comment by chennes** [comment]
I can see the problem clearly, but the solution is not entirely straightforward. I have started a discussion about it here: https://github.com/FreeCAD/FreeCAD/discussions/9584

**Comment by chennes** [comment]
The bulk of this one is done, if anything remains let's open a new ticket.

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux 12 (bookworm) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33263 (Git) AppImage
Build type: Release
Branch: master
Hash: 864f99bf984c237ef38d9451fd6f3a5ec34e6eb4
Python 3.11.3, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.2, OCC 7.7.1
Locale: Polish/Poland (pl_PL)
Installed mods: 
  * Curves 0.5.0
  * sheetmetal 0.2.56
  * Reinforcement
  * BIM 2021.12.0
```
Not everything worked as expected ...
I'll wait until the next build. :wink:

**Comment by kaktusus** [comment]
done
