### ISSUE TITLE
Arch → option name notation without the word `object`

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#221]
```
OS: Debian GNU/Linux 12 (bookworm) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33110 (Git) AppImage
Build type: Release
Branch: master
Hash: 18e40941ceb36c52701a7c74ea26043ef3385701
Python 3.11.3, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.2, OCC 7.7.1
Locale: Polish/Poland (pl_PL)
Installed mods:
```

Reported at the request of David69 from the forum.

Suggestion to shorten option names by omitting the word 'object' throughout the menu.

Example:
https://crowdin.com/translate/freecad/6766/en-fr?filter=basic&value=0#6613357

**Comment by yorikvanhavre** [comment]
Yes that's a good move I think.
Could you maybe help building a list of those strings? That would be really useful...

**Comment by kaktusus** [comment]
I asked David to prepare links from Crowdin to the options whose names he proposes to correct.

We have to wait I think he is very busy right now.

**Comment by kaktusus** [comment]
On left side, the existing string, after `==>` the suggested string.

`Creates a stairs object` ==> Creates a stair.
    https://crowdin.com/translate/freecad/6766/en-fr#6613357

`Creates a structure object from scratch or from a selected object (sketch, wire, face or solid)` ==> Creates a structure from scratch or from a selected object (sketch, wire, face or solid).
    https://crowdin.com/translate/freecad/6766/en-fr#6604403

`Creates an equipment object from a selected object (Part or Mesh)` ==> Creates an equipment from a selected object (Part or Mesh).
    https://crowdin.com/translate/freecad/6766/en-fr#6606221

`Creates a BuildingPart object including selected objects` ==> Creates a Building Part including selected objects.
    https://crowdin.com/translate/freecad/6766/en-fr#6606241

`Creates a profile object` ==> Creates a profile.
https://crowdin.com/translate/freecad/6766/en-fr#6606347

`Creates a site object including selected objects.` ==> Creates a site including selected objects.
    https://crowdin.com/translate/freecad/6766/en-fr#6606357
