### ISSUE TITLE
FreeCAD → Start → Create a new empty document

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#222]
```
OS: Debian GNU/Linux 12 (bookworm) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33110 (Git) AppImage
Build type: Release
Branch: master
Hash: 18e40941ceb36c52701a7c74ea26043ef3385701
Python 3.11.3, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.2, OCC 7.7.1
Locale: Polish/Poland (pl_PL)
Installed mods: 
  * Curves 0.5.0
  * sheetmetal 0.2.56
  * Reinforcement
```

New document label has no translation ...

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/c2544919-8d7e-4360-a309-b35ec7404649)

Was already fixed

https://github.com/FreeCAD/FreeCAD-translations/issues/57
https://github.com/FreeCAD/FreeCAD-translations/issues/198

and it's broken again. :cry:

**Comment by kaktusus** [comment]
Applies to options in the toolbar, menu and button on the start panel

**Comment by chennes** [comment]
I'm not sure what's going on here: a call to `QObject::tr("Unnamed")` just returns "Unnamed", regardless of your language selection, but it's clearly in the TS files. I will have to look closer.

**Comment by kaktusus** [comment]
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Unnamed

I have all the occurrences translated even the hidden ones.

**Comment by kaktusus** [comment]
still needs attention

**Comment by chennes** [comment]
At looks to me like 439-441 of Application.cpp need to address translations:
```
        if (defaultName) {
            Name = "Unnamed";
        }
```
That, or per my earlier note, there is something wrong with the context for the translation of "Unnamed", and we should call `translate` instead of `tr` to beat it into submission.

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37249 (Git) AppImage
Build type: Release
Branch: main
Hash: 3acbc561f299b4cddea8215c387a52f3d5132cf6
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

Done :bangbang:  :smiley: 

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/872b154d-a2ac-4b15-9d33-2aaf77ca8551)

@ronnystandtke thank to :1st_place_medal:
