### ISSUE TITLE
BIM add-on → main menu

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#225]
```
OS: Debian GNU/Linux 12 (bookworm) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33110 (Git) AppImage
Build type: Release
Branch: master
Hash: 18e40941ceb36c52701a7c74ea26043ef3385701
Python 3.11.3, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.2, OCC 7.7.1
Locale: Polish/Poland (pl_PL)
Installed mods: 
  * Curves 0.5.0
  * sheetmetal 0.2.56
  * Reinforcement
  * BIM 2021.12.0
```

Main menu labels are displayed in wrong code page after loading BIM workbench.

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/2c64cccf-fa88-4ed8-917d-36ccd9f68daf)

Instead of diacritical characters, "funny marks" are displayed.
In addition, this strings disappeared from Crowdin for the add-on BIM.

eg.
https://crowdin.com/translate/freecad-addons/32152/en-pl?filter=basic&value=0#q=&Kre%C5%9Blenie%202D
https://crowdin.com/translate/freecad-addons/32152/en-pl?filter=basic&value=0#q=Prz&yci%C4%85ganie
https://crowdin.com/translate/freecad-addons/32152/en-pl?filter=basic&value=0#q=&Zarz%C4%85dzanie

They are also not in the main Crowdin repository for FreeCAD.

In this workbench there are more problems related to the lack of translations in the GUI.

**Comment by yorikvanhavre** [comment]
This is strange, it is done the same way as other workbenches...
Are other python-based workbenches like Draft, Arch, etc... working OK?

**Comment by kaktusus** [comment]
> Are other python-based workbenches like Draft, Arch, etc... working OK?

Yes

**Comment by kaktusus** [comment]
We also have two old tickets that have not been resolved so far.

1.  https://github.com/FreeCAD/FreeCAD-translations/issues/135 

2.  https://github.com/FreeCAD/FreeCAD-translations/issues/136

**Comment by kaktusus** [comment]
Today I was surprised by the behavior of the program.
Having BIM WB loaded, I switched the application language to English. To my surprise, the standard options were reloaded to English. The menu belonging to BIM was reloaded to Polish with the correct code page.
Only by restarting the program and BIM wb did the full English version appear.

**Comment by kaktusus** [comment]
@yorikvanhavre  
we had a similar problem with the code page with `Bézier` string, as I recall the problem was on the side of your development environment

**Comment by yorikvanhavre** [comment]
Should be solved with the above commit. But of course it will take time for translators to update their translations. I'll leave this open so we don't forget to check

**Comment by kaktusus** [comment]
I'm glad. :wink:

**Comment by kwahoo2** [comment]
Hi,

These strings stays in English for me
![sshot](https://i.imgur.com/PoYWyyN.png)
```
OS: Fedora Linux 37 (KDE Plasma) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33617 (Git) AppImage
Build type: Release
Branch: master
Hash: ae215724dd6c5336dcbb263733c6830a24917963
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
  * freecad-mbdyn-dynamics-workbench
  * BIM 2021.12.0
  * freecad.gears 1.0.0
```

**Comment by luzpaz** [comment]
@kwahoo2 are the strings available to translate in freecad-addon crowdin ?

**Comment by kaktusus** [comment]
all are available and translated, example
`Modify` https://crowdin.com/translate/freecad-addons/32152/en-pl#6620885

**Comment by kaktusus** [comment]
fixed

```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33631 (Git) AppImage
Build type: Release
Branch: master
Hash: 2167fb6f7ec6ac5c2f6365d4c3035d2db6879b1e
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
  * Curves 0.5.0
  * sheetmetal 0.2.56
  * Reinforcement
  * BIM 2021.12.0
  * Rocket 3.1.0
  * kicadStepUpMod 10.19.4
  * fasteners 0.4.56
  * Alternate_OpenSCAD 1.0.0
  * Render 2023.2.6
```


![image](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/145212e5-092d-4b6e-b0d6-703b9c4a6f6b)

**Comment by kaktusus** [comment]
overall, no
the error persists
I forgot that I previously activated Arch wb.

![image](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/70763700-c02f-4279-b1ce-f7cb53db50c1)

**Comment by kaktusus** [comment]
Today, for a test, I did a local import of translations for BIM.
The issue did not occur.

**Comment by yorikvanhavre** [comment]
This should in any case be solved now with https://github.com/yorikvanhavre/BIM_Workbench/commit/83620ae44a424424981d36a7fa6c7a7eaa68d348

**Comment by kwahoo2** [comment]
It is fixed for me.

**Comment by yorikvanhavre** [comment]
closing, then!

**Comment by kaktusus** [comment]
When I do a local import of translations the problem does not exist.

![image](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/d62b296d-8002-4a31-a21b-c2ff78c1c7c5)

If I run FreeCAD without a local translation file there is a problem with the encoding of these characters.

![image](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/1d40a956-decd-4414-8b16-2ae222410f25)


@kwahoo2  Can you check it with you with the latest AppImage?

**Comment by kaktusus** [comment]
I started looking through the sources on GitHub with translations for the BIM workbench.

https://github.com/yorikvanhavre/BIM_Workbench/blob/3928e0a9301026ae74a5e1cae8b8dfaca1edf095/translations/BIM_pl.ts

This file is very old. I don't see the reason for the character encoding problem in it. Probably at that time everything was still working properly.
Where can I find up-to-date sources with the current translation file ... I would like to try to identify the problem.

**Comment by kaktusus** [comment]
Most work after the BIM update.

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/46b6751a-9d4c-4980-a517-59200d1883ee)

There remains one `&2D Drafting` that was not included in the source code fixes. [line #571]

**Comment by kaktusus** [comment]
Notice that the `3D / BIM` menu now appears twice. :fearful:

**Comment by yorikvanhavre** [comment]
> Notice that the 3D / BIM menu now appears twice. fearful

Weird, this does not happen here with me... Any error message?

![image](https://github.com/FreeCAD/FreeCAD-translations/assets/1136856/81bf2bfb-4d39-43c3-8e8a-78bfb9b72ad8)

**Comment by kaktusus** [comment]
I have not had any error messages

However, in your image, I see the menu name in an unfamiliar language ...

`Desenho2D`

**Comment by yorikvanhavre** [comment]
Indeed that "2D drawing" menu didn't update... I had to restart FreeCAD. It's weird, it still shows wrong characters...

![image](https://github.com/FreeCAD/FreeCAD-translations/assets/1136856/618cfdb8-c1fc-4fca-bef9-759227df609a)

I have no idea what is causing this, though... Everything is the the same as other menu items in the InitGui file. Maybe something wrong with the translation on crowdin? Can you check if it's correct there?

**Comment by kaktusus** [comment]
I downloaded the translation file from Crowdin.
I also reviewed the translation file in the sources on GitHub.
I did not find any anomalies.

The only sensible comment of this situation I wrote here: https://github.com/FreeCAD/FreeCAD-translations/issues/225#issuecomment-1655918589

**Comment by yorikvanhavre** [comment]
Aah good catch! I had missed that one. It's now fixed!

**Comment by kaktusus** [comment]
All in all, it is very puzzling why only in my case the error occurs.
It seems that you have a good tester in my person .... :laughing:

**Comment by yorikvanhavre** [comment]
And testing is super important and a very big part of bugfixing... Thanks!

**Comment by luzpaz** [comment]
Well done!

**Comment by kaktusus** [comment]
Now and with me everything works properly after the BIM update.

![image](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/c16a0682-3988-4e22-8e8a-6666a22285f9)
