### ISSUE TITLE
BIM  →  Context menu on the `body` object of the model.

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#234]
```
OS: Debian GNU/Linux 12 (bookworm) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33303 (Git) AppImage
Build type: Release
Branch: master
Hash: 5b075a9938b78076fdde9034de4a05685e42690e
Python 3.10.11, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
  * Curves 0.5.0
  * sheetmetal 0.2.56
  * Reinforcement
  * BIM 2021.12.0
  * Rocket 3.1.0
```
In the model tree, I select the `body` object. In the 3D view window, I click RMB.
Not all pop-up menu utilities labels have translations.

![image](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/73397772-807d-4181-8815-13a5bf6e9926)

1. `Snapping` - no string in Crowdin
    https://crowdin.com/translate/freecad-addons/32152/en-pl?filter=basic&value=0#q=Snapping

2. `Reorder children` - no string in Crowdin
    https://crowdin.com/translate/freecad-addons/32152/en-pl?filter=basic&value=0#q=Reorder%20children

**Comment by yorikvanhavre** [comment]
The ts file was hugely outdated. The one now on crowdin is now complete.
