### ISSUE TITLE
TechDraw → TechDraw Attributes (toolbar) → Calculate the area of selected faces (tool)

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#235]
```
OS: Debian GNU/Linux 12 (bookworm) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33303 (Git) AppImage
Build type: Release
Branch: master
Hash: 5b075a9938b78076fdde9034de4a05685e42690e
Python 3.10.11, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
  * Curves 0.5.0
  * sheetmetal 0.2.56
  * Reinforcement
  * BIM 2021.12.0
  * Rocket 3.1.0
```

Window title without translation.

![image](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/608bdde1-fa1b-49b5-bd41-74e24bf21447)

`TechDraw calculate selected area` - no string in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=TechDraw%20calculate%20selected%20area

**Comment by chennes** [comment]
See https://github.com/FreeCAD/FreeCAD-translations/issues/240 -- this is the same problem, with the same fix.

**Comment by kaktusus** [comment]
still needs attention
