### ISSUE TITLE
TechDraw → TechDraw Centerlines (toolbar) → Change Line Attributes (tool) and others

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#239]
```
OS: Debian GNU/Linux 12 (bookworm) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33303 (Git) AppImage
Build type: Release
Branch: master
Hash: 5b075a9938b78076fdde9034de4a05685e42690e
Python 3.10.11, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
  * Curves 0.5.0
  * sheetmetal 0.2.56
  * Reinforcement
  * BIM 2021.12.0
  * Rocket 3.1.0
```

Window title without translation.

![image](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/bfd8a7e6-6faa-41c1-8ba4-3fc69fb8ea45)

`TechDraw Cosme.../Perpendicular` - I don't even know what it says I'm guessing that this string is not in Crowdin.

![image](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/e26a350c-45db-4227-849c-cdaff71dee3e)

`TechDraw Cosmetic Circle` - no string in Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=TechDraw%20Cosmetic%20Circle

![image](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/54a4c9f3-5513-43fa-bd15-d03a52576c88)

`TechDraw Cosme...ion Vertex(es)` - I don't even know what it says I'm guessing that this string is not in Crowdin.

![image](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/46e3a6a9-18b8-4945-b2c2-0f551199fa74)

`TechDraw Circle Centerlines` - no string in Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=TechDraw%20Circle%20Centerlines

Component `Add Cosmetic Thread Hole Side View` has this window with translated text but the title is not readable because the window is too narrow.

**Too narrow window and unreadable title is a global problem for FreeCAD**
Should I generate some generic ticket for this inconvenience?

**Comment by WandererFan** [comment]
This one also looks like it should be translatable:

    sAppModule = "TechDraw";
    sGroup = QT_TR_NOOP("TechDraw");
    sMenuText = QT_TR_NOOP("Add Circle Centerlines");
    sToolTipText = QT_TR_NOOP("Add centerlines to circles and arcs:<br>\
- Specify the line attributes (optional)<br>\
- Select one or more circles or arcs<br>\
- Click this tool");
    sWhatsThis = "TechDraw_ExtensionCircleCenterLines";
    sStatusTip = sMenuText;
    sPixmap = "TechDraw_ExtensionCircleCenterLines";

**Comment by chennes** [comment]
The fix for this is the same as for https://github.com/FreeCAD/FreeCAD-translations/issues/240 -- it's not the command itself that is the problem, it's the use of `_checkSel` with a string that is never provided to the translation system in CommandExtensionPack.cpp. This is present in at least two files: are there others? Also, I think there's another, similar function, at least in CommandExtensionDims.cpp (`_checkSelAndObj` or something) that has the same problem.

**Comment by kaktusus** [comment]
Good thing you're back from leave ...
as you can see without you nothing could be done ....

**Comment by kaktusus** [comment]
still needs attention
