### ISSUE TITLE
Part Design → Create a mirrored feature (tool)

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#24]
```
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.25025 (Git) AppImage
Build type: Release
Branch: master
Hash: fb8b21ec43dca706a4aa2d63d59a4fb79f050369
Python version: 3.9.4
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: Polish/Poland (pl_PL)
```

Section title in tool window has no translation
![obraz](https://user-images.githubusercontent.com/39754351/121808983-49f7d100-cc5b-11eb-84cd-619166f38165.png)

1. Mirrored parameters
no string in Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Mirrored%20parameters

1. As usual, the Cancel button has an untranslated label
 ;-)

**Comment by luzpaz** [comment]
Weird, I can't find `Mirrored parameters` in the source code. Did the name of this dialog change?

**Comment by kaktusus** [comment]
https://crowdin.com/translate/freecad/564/en-pl#6496550

??
A label combined like the one here: #11  ??

**Comment by Kuzma30** [comment]
Proposed solution https://github.com/Kuzma30/FreeCAD/commit/fb58fd825367bb35f9fbe75a3d89fa9f48ec2249

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28793 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 5386d4e)
Hash: 5386d4ed864cd03edd026e1d3d128cccedf568df
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

After recent updates the problem still persists ...

![obraz](https://user-images.githubusercontent.com/39754351/167264447-e4b13910-ca2b-4182-a581-097a7d9963ac.png)

**Comment by chennes** [comment]
I believe this is the same issue discussed elsewhere, where the code's author has split the string into two parts, and is not correctly ensuring that the translation of the combined string is being extracted. I think the offending code is here:
https://github.com/FreeCAD/FreeCAD/blob/971743a2e99a2749870231c33d6d0f923c03cf03/src/Mod/PartDesign/Gui/TaskTransformedParameters.cpp#L57

**Comment by yorikvanhavre** [comment]
I think we should definitely edict a rule like "NO MULTIPLE LINES IN translate()". I have the impression that pyside2-lupdate could pick them up correctly, but pylupdate5 not, anyway, it's a mess, and to avoid further problems we should definitely stop using them. And track them down and fix them. Maybe it's possible to set up a regex rule to find them? Like lines with translate( and " + end if line... I'll try that.

**Comment by kaktusus** [comment]
I think making rules for all developers is a very good step forward.
However, it is important to make them accessible to all.
This bodes well for the future.

**Comment by yorikvanhavre** [comment]
A first step is to make sure all mergers know about this, so they can spot issues in PRs

**Comment by kaktusus** [comment]
We'll come up with something for the opportunity, after all, there are some smart heads here.
;-)

**Comment by kaktusus** [comment]
Would the README.md file be a good place to present rules and guidelines for developers on how to prepare code with tool and menu descriptions so that they do not cause problems when preparing .ts files?

**Comment by luzpaz** [comment]
Possibly. Or workbench creation type pages? Or perhaps we can have a github action that checks for this?

**Comment by kaktusus** [comment]
Since you're asking that, I'm sure it's a possibility.
Github is strange for me.

I'm learning about its possibilities and I don't have much time for that.

And let me tell you that you have succeeded because thanks to you I do whatever I do here.
;-)

**Comment by kaktusus** [comment]
> Possibly. Or workbench creation type pages? ....

So something along the lines of how to do it properly so as not to generate problems.
Just like on the page you mentioned.
There are quite a few of these guidelines.
I have already read about some of them because you are talking about these topics. These are serious matters. If they are systematized it will be a great benefit because you won't have to constantly go back and work on fixes.
See how many people are involved in the repair and how much time everyone has to spend.

Most importantly, there are results from these efforts.
And that makes me happy.
