### ISSUE TITLE
TechDraw → TechDraw Extend Dimensions (toolbar) → all tools

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#240]
```
OS: Debian GNU/Linux 12 (bookworm) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33303 (Git) AppImage
Build type: Release
Branch: master
Hash: 5b075a9938b78076fdde9034de4a05685e42690e
Python 3.10.11, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
  * Curves 0.5.0
  * sheetmetal 0.2.56
  * Reinforcement
  * BIM 2021.12.0
  * Rocket 3.1.0
```

Window title without translation.

1.  ![image](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/5120d0e7-e2fb-4445-9a38-5bc3e5862af7)

2.  ![image](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/09218269-9b39-43e4-8146-27e4f52c8545)

3.  ![image](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/e15d1488-d806-4f94-9708-732e3913a085)

4.  ![image](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/04e17ead-13ef-4c4f-a9dd-c8c863d1684e)

5.  ![image](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/21ba0a07-6a47-4c1d-bcce-b9c0e9764bf0)

1.  ![image](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/5a55aaea-1635-4fb5-a398-514dfc0aed2a)

ad 2.
`TechDraw Insert Prefix` - no string in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=TechDraw%20Insert%20Prefix

ad 1, 3, 4, 5, 6 - I don't even know what it says I'm guessing that this string is not in Crowdin.

**Comment by WandererFan** [comment]
What is missing here that it doesn't get added to Crowdin?

    sAppModule      = "TechDraw";
    sGroup          = QT_TR_NOOP("TechDraw");
    sMenuText       = QT_TR_NOOP("Increase Decimal Places");
    sToolTipText    = QT_TR_NOOP("Increase the number of decimal places of the dimension text:<br>\
- Select one or more dimensions<br>\
- Click this tool");
    sWhatsThis      = "TechDraw_ExtensionIncreaseDecimal";
    sStatusTip      = sMenuText;
    sPixmap         = "TechDraw_ExtensionIncreaseDecimal";

**Comment by WandererFan** [comment]
Every command in CommandExtensionDims.cpp is coded the same way:

    sAppModule      = "TechDraw";
    sGroup          = QT_TR_NOOP("TechDraw");
    sMenuText       = QT_TR_NOOP("Insert '⌀' Prefix");
    sToolTipText    = QT_TR_NOOP("Insert a '⌀' symbol at the beginning of the dimension text:<br>\
- Select one or more dimensions<br>\
- Click this tool");
    sWhatsThis      = "TechDraw_ExtensionInsertPrefixGroup";
    sStatusTip      = sMenuText;
}

**Comment by kaktusus** [comment]
The text on the title bar is translated but still remains compressed and is impossible to read
