### ISSUE TITLE
TechDraw → TechDraw menu → Stacking

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#241]
```
OS: Debian GNU/Linux 12 (bookworm) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33321 (Git) AppImage
Build type: Release
Branch: master
Hash: 1d61ed187c9633702818c6cc5d7a1f07dd052ca8
Python 3.10.11, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
  * Curves 0.5.0
  * sheetmetal 0.2.56
  * Reinforcement
  * BIM 2021.12.0
  * Rocket 3.1.0
```

One menu item has no translation.

![image](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/58dcdbf9-775d-4b7f-9914-548d5ee82e4e)

`Stacking` - no string in Crowdin.
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Stacking

By request of David69 of the forum. :wink:

**Comment by WandererFan** [comment]
there is only one place where "Stacking" appears by itself and it doesn't look any different from the menu items that do have a translation.  I don't know how to force "Stacking" into the translation process.

Mod/TechDraw/Gui/Workbench.cpp
    // stacking
    Gui::MenuItem* stacking = new Gui::MenuItem;
    stacking->setCommand("Stacking");
    *stacking << "TechDraw_StackTop";
    *stacking << "TechDraw_StackBottom";
    *stacking << "TechDraw_StackUp";
    *stacking << "TechDraw_StackDown";

**Comment by kaktusus** [comment]
Fixed


```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33458 (Git) AppImage
Build type: Release
Branch: master
Hash: 8b89dd29d2382c72d738c52e8974216130ffa9db
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
  * Curves 0.5.0
  * sheetmetal 0.2.56
  * Reinforcement
  * BIM 2021.12.0
  * Rocket 3.1.0
  * kicadStepUpMod 10.19.4
  * fasteners 0.4.56
```


![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/98f7363d-c75a-498b-b073-e72cbe020dc5)
