### ISSUE TITLE
BIM → main menu / Utils → Nudge

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#244]
```
OS: Debian GNU/Linux 12 (bookworm) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33321 (Git) AppImage
Build type: Release
Branch: master
Hash: 1d61ed187c9633702818c6cc5d7a1f07dd052ca8
Python 3.10.11, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
  * Curves 0.5.0
  * sheetmetal 0.2.56
  * Reinforcement
  * BIM 2021.12.0
  * Rocket 3.1.0
```

Sub menu `Nudge` has translation deficiencies.

![image](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/33261894-c48c-43bb-9838-10a3505140c5)

1. `Nudge` - the string "already" is in Crowdin :wink: 
    https://crowdin.com/translate/freecad-addons/32152/en-pl#6580106
2. `Nudge Switch` - the string "already" is in Crowdin :wink: 
   https://crowdin.com/translate/freecad-addons/32152/en-pl#6618973
3. `Nudge Up` - the string "already" is in Crowdin :wink: 
    https://crowdin.com/translate/freecad-addons/32152/en-pl#6618975
4. `Nudge Extend` - the string "already" is in Crowdin :wink: 
    https://crowdin.com/translate/freecad-addons/32152/en-pl#6618961
5. `Nudge Shrink` - the string "already" is in Crowdin :wink: 
    https://crowdin.com/translate/freecad-addons/32152/en-pl#6618971

A few more discrepancies and deficiencies were found, however, Yorik did an update in Crowdin yesterday and I will not describe everything now. We will wait for developments. After translation I will test everything in the local environment.

![image](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/6426dd98-57d6-48a2-acf8-7c40fcd92def)

![image](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/2292dd99-ab39-4a18-9f7f-f13caeaa7a52)

![image](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/d7fd0a80-ef8a-4fb2-9657-1112a4088d4a)
Here's an interesting fact
visible options after switching to the `Draft` workbench are translated.

**Comment by yorikvanhavre** [comment]
So, needs to be fixed:

* [ ] Nudge tools - already on crowdin
* [ ] Move to trash - already on crowdin
* [ ] Snapping - fixed by https://github.com/yorikvanhavre/BIM_Workbench/commit/41da98e905d931dbc72b884f10098ab7d78e506d - restart needed
* [ ] Reorder children - already on crowdin
* [ ] Toolbars objectNames - these are on crowdin, but a restart might be needed

Also need to check if we can avoid the need to restart FreeCAD to apply changes in the InitGui file

**Comment by kaktusus** [comment]
still requires attention

**Comment by yorikvanhavre** [comment]
I just merged the latest translations from crowdin. Unfortunately, almost nothing is translated in https://crowdin.com/project/freecad-addons ... I'll try working on the addons translations so we can better test

**Comment by kaktusus** [comment]
It's true in this corner little is happening,
it needs to be promoted.

For a long time I've been thinking about making such a thread on the forum for translators and collecting in it all the Crowdin and GitHub places where translators can find some work with FreeCAD.

But somehow I can't go about it ... :rofl:

**Comment by kaktusus** [comment]
fixed.

After BIM update.
