### ISSUE TITLE
PartDesign → Create sketch / dialog called from the view properties panel

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#245]
```
OS: Debian GNU/Linux 12 (bookworm) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33321 (Git) AppImage
Build type: Release
Branch: master
Hash: 1d61ed187c9633702818c6cc5d7a1f07dd052ca8
Python 3.10.11, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

![image](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/9f3a20a8-9758-488c-8c2e-5941694e06cb)

`Attachment` - the string is in Crowdin with attribute hidden
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Attachment

**Comment by chennes** [comment]
I have marked the string visible in CrowdIn.

**Comment by kaktusus** [comment]
What could have caused the translation to be missing from the panel?

**Comment by kaktusus** [comment]
still needs attention

this panel is activated by clicking the ellipsis next to the `Map Mode` property.

**Comment by kaktusus** [comment]
![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/e52ba7b1-f0fc-4f0b-b56f-eb4bed65607e)

Fixed

```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36677 (Git) AppImage
Build type: Release
Branch: main
Hash: 3fadb1f40bdfa4ee1c61acbf12fbe44680723965
Python 3.11.8, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
Installed mods: 
```
