### ISSUE TITLE
[Crowdin] Configuration regarding import  →  Source Strings  →  Duplicate Strings

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#252]
The problem is very annoying and has affected all of us for several years.

**It creates impassable difficulties for translators of nationalities where there are no proofreaders.**
___
Gentlemen, have you considered what percentage of the total translation base are hidden strings?

If not then I will suggest ... way tooooooooooooooooooooooooooooooooooooo laaaaaaaaaaaaarge.

_I will do a quiz on the forum for readers we will examine the awareness of the community and project managers in this regard._
___
Where do hidden strings come from in a FreeCAD project?
An appropriate configuration that is designed to facilitate the work of translators to some extent allows such a procedure.
During import, identical source strings are detected and accumulated on the Crowdin platform. When the "main" is translated, the rest is machine-translated on the remaining occurrences.
___
In principle, this behavior of the program in certain situations can be helpful. However, not in "our" project. As it is a very serious and complex project, 
Some of the source strings may take different translations, for example, depending on the context.
I would like to remind here that at the moment FreeCAD is translated by the community into **71 languages**. In a little while, this great result will be achieved by the teams of the following nations. 
Each of them is complex in itself and lives by its own laws.
This year, seven nationalities have already reached the 100% translation advancement ceiling. For several years, only the Polish translation team could boast such an achievement.

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/445a09fe-19c1-4ce5-823f-518aff7b2b46)

II believe this is a very big asset :1st_place_medal:  for you developers and managers. It proves that your work is noticed and accepted in the community. Even more, it IS NEEDED as evidenced by such a large _(and growing)_ interest in, for example, the translation of the GUI.
Let such an achievement also drive you to keep working not only on new functionalities.
Let it "drive" you to keep working on the GUI and improving it for other nationalities as well.
___
_I will complain for a while more, but only a little. :wink: 
I began to pay attention to the problem of appearing hidden strings a very long time ago. I tried to talk to some of you individually. So far without success._

I do not have permissions that allow me to view the Crowdin platform configuration for the project.
However, I found a detailed description in the documentation.

In this situation, I can only ask a few of you to review and try to decide. I expect that only one of you will be able to take the appropriate steps if my proposed solution is accepted.
___
Now the much-awaited specifics:

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/7572ef24-1e39-4aca-b9b1-efbaa2489934)

source of the image with text
https://support.crowdin.com/project-settings/#import
___

The configured behavior of the Crowdin platfrorm which now defines the current problems, also causes other additional perturbations even to those with proofreader privileges.

Personally, I have reported the problem more than once when I had the need to change the translation of one of the source strings joined in this way.

Correcting the selected one (not necessarily with the master attribute) the others also changed the translation. Such behavior is unacceptable. And at this point it did not matter whether the string was approved or not. They were all machine-corrected by the program. :cry:  The same is true of approving strings merged in this way.
I select one program automatically transfers approval to the others....  :sob: 

https://crowdin.com/translate/freecad/549/en-pl#6598642
___

What's good.

In the past year, one of you has already undertaken the tedious and unmotivating work of correcting code written by others to improve the functioning of the GUI translation. @luzpaz you are what I mean here.
You did a lot of good work back then. But you yourself know how much more needs to be done. And how bad the situation was. You were supported at the time by @yorikvanhavre.
The problem is that some of you (developers) continued to generate code that did not support troubleshooting in this area. :scream: 
This year, @chennes took on this nasty task.
He is also supported by Yorik and other gents on an ad hoc basis.

**To all of you, I sincerely thank you for the many hours you have spent on this arduous work.**
---
I will ask myself a rhetorical question - is it necessary that so many hours are spent on correcting the same mistakes over and over again?  :dollar: 

I regret that "my friend" Alexandr aka @Kuzma30 is not among us. He was doing a wonderful job.

Getting back to the core of the problem, please talk in your circle and consider the current configuration of the Crowin platform.
If you make any decisions write about it here.

**Comment by kaktusus** [comment]
https://forum.freecad.org/viewtopic.php?style=4&t=79674

**Comment by kaktusus** [comment]
Following the blow, the same functionality would be desirable in the project configuration freecad-addons.
I mean this correct configuration favoring translators. :wink:

**Comment by chennes** [comment]
I talked to @yorikvanhavre about this change, and he agrees that it's a reasonable one, so we will do it. However, we are worried about the potential consequences to the current translation state, so we plan to do it after the 0.21 release, just in case it causes some sort of unforeseen havoc. However, I will likely forget I told you this, so please ping me after that release so that I can make the change 😄 .

**Comment by kaktusus** [comment]
no problem
theoretical when do you plan to release a new stable version?

thanks for the info :wink:

**Comment by chennes** [comment]
Basically waiting on one set of TNP code for the merge, but I think we're going to make a release candidate next weekend (pending other people's schedules).

**Comment by kaktusus** [comment]
ok

Sounds good :wink: 
play with the others with this crazy survey - please. :rofl:

**Comment by kaktusus** [comment]
As you can see, someone has already pointed out the source _(#61)_ of this mess ...
And I had forgotten about it.
@FreeCAD-Tools applause for being perceptive. :wink:

**Comment by kaktusus** [comment]
As of 2023-07-14, the situation with strings with hidden attribute was not happy.
The following picture shows the page counter. Each page contains 50 translation entries. The current result starts with strings that only a few people in the international translation team have access to.


![ukryte_stringi_Firefox_Screenshot_2022-07-14T11-41-23 124Z](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/4b5c47ae-bed0-46af-a210-3b55bb744d58)

Thanks to Chris for changing the settings. 🥇 

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/f68674c6-7878-4efd-88b4-5596ce7755f4)

Can you tell which setting you chose?

**Comment by chennes** [comment]
It is not Top Sekrit! I chose the option you suggested above, to show the strings but to auto-translate them. I hope that minimizes translator work, but still allows good customization of the strings when they are wrong.

**Comment by kaktusus** [comment]
Do you want me to close this ticket or do you want us to keep it open for a few more weeks for observation?

**Comment by chennes** [comment]
Let's close it now.
