### ISSUE TITLE
FreeCAD → main menu → Edit → Preferences ... / General - Unit system 2

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#257]
```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33576 (Git) AppImage
Build type: Release
Branch: master
Hash: 8e6fbd2886d3ad51b75232bd0019d92d496e80cb
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
  * Curves 0.5.0
  * sheetmetal 0.2.56
  * Reinforcement
  * BIM 2021.12.0
  * Rocket 3.1.0
  * kicadStepUpMod 10.19.4
  * fasteners 0.4.56
  * Alternate_OpenSCAD 1.0.0
  * Render 2023.2.6
  * Movie 2023.6.10
  ```

The previous ticket #220 was closed but the problem still exists.

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/48f4b06c-e2b0-4b21-a5dc-1afc4c1ad81d)

**Comment by chennes** [comment]
Looks like I added the `tr()` calls to the source code, but didn't modify `lupdate` to extract strings from Base.

**Comment by kaktusus** [comment]
Translations still don't work ...

**Comment by kaktusus** [comment]
The export of translations has already gone through several full cycles from sources to Crowdin and from Crowdin to sources.
However, users still cannot enjoy the translated GUI in this area.

```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34387 (Git) AppImage
Build type: Release
Branch: master
Hash: d95b26dfb5dd23eaee004b4af3cf5cf4766e7f9c
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
```

![image](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/ee57990d-d7f2-48f7-b8f6-84a3a53b6723)

source string:
https://github.com/FreeCAD/FreeCAD/blob/c87860922c90007f71de9f1886ae8176e00ac977/src/Base/Resources/translations/Base.ts#L13
string translated:
https://github.com/FreeCAD/FreeCAD/blob/c87860922c90007f71de9f1886ae8176e00ac977/src/Base/Resources/translations/Base_pl.ts#L14

---
Today I did an experiment.
I used the local translation test method. Everything works properly.
![image](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/3a4252bb-d94d-476f-99c0-e40932cc30b0)


Therefore, I will ask a question: are the new translation files moved/linked to the right place of the sources? , or does the program know that it has them?

**Comment by ronnystandtke** [comment]
This issue should be fixed by this pull request: https://github.com/FreeCAD/FreeCAD/pull/13928

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37249 (Git) AppImage
Build type: Release
Branch: main
Hash: 3acbc561f299b4cddea8215c387a52f3d5132cf6
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

Done :bangbang:  :smiley: 

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/abf910c0-bb86-47c2-af75-cdb937c65244)

Ronny would you like to fix more stuff :grey_question:

**Comment by ronnystandtke** [comment]
> Ronny would you like to fix more stuff ❔

I'm trying to... ;-)

**Comment by kaktusus** [comment]
Not only will the international translation community be grateful to you ...
