### ISSUE TITLE
Draft → main menu → Annotation → Dimension

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#258]
```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33576 (Git) AppImage
Build type: Release
Branch: master
Hash: 8e6fbd2886d3ad51b75232bd0019d92d496e80cb
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
  * Curves 0.5.0
  * sheetmetal 0.2.56
  * Reinforcement
  * BIM 2021.12.0
  * Rocket 3.1.0
  * kicadStepUpMod 10.19.4
  * fasteners 0.4.56
  * Alternate_OpenSCAD 1.0.0
  * Render 2023.2.6
  * Movie 2023.6.10
```

Not all labels have translations in the GUI.

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/40bb3189-3b35-4c8e-8996-6711a3964281)

`Dimension` - string is in Crowdin _(has a hidden parameter)_
    https://crowdin.com/translate/freecad/548/en-pl#6607111

`Local ...` - All three string variants are in Crowdin
   https://crowdin.com/translate/freecad/548/en-pl#6604481
   https://crowdin.com/translate/freecad/548/en-pl#6604485
   https://crowdin.com/translate/freecad/548/en-pl#6604489

The translation for `Local ...` does not work in the other tools in this menu either.

**Comment by kaktusus** [comment]
The following strings conflict in all tools where they occur is a global problem :cry: 

`Local u0394Z`
`Local u0394Y`
`Local u0394Z`

**Comment by chennes** [comment]
"Dimension" is an easy fix, but I suspect a CrowdIn issue for the greek "delta" symbol there: it looks like the backslash is getting lost, or something like that. I wonder if we can create that ∆ in another way.

**Comment by kaktusus** [comment]
Those languages that do not have a Latin alphabet can have their own letters.
However moving the text out of the translation area seems like a good solution.

**Comment by yorikvanhavre** [comment]
Sorry for the late response... good solution!
