### ISSUE TITLE
Draft → main menu → Annotation → Label

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#259]
```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33576 (Git) AppImage
Build type: Release
Branch: master
Hash: 8e6fbd2886d3ad51b75232bd0019d92d496e80cb
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
  * Curves 0.5.0
  * sheetmetal 0.2.56
  * Reinforcement
  * BIM 2021.12.0
  * Rocket 3.1.0
  * kicadStepUpMod 10.19.4
  * fasteners 0.4.56
  * Alternate_OpenSCAD 1.0.0
  * Render 2023.2.6
  * Movie 2023.6.10
 ```

Drop-down list in the Label type section - all items without translations.

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/50a52df8-ef7a-4c00-b37c-183d1c3911be)

1. `Custom` - string is in Crowdin _(has attribute hidden)_
    https://crowdin.com/translate/freecad/548/en-pl#6604647
2. `Name` - string is in Crowdin _(has attribute hidden)_
    https://crowdin.com/translate/freecad/548/en-pl#6612425
3.  `Label` - string is in Crowdin _(has attribute hidden)_
    https://crowdin.com/translate/freecad/548/en-pl#6604455
4. `Position` - no string in Crowdin
https://crowdin.com/translate/freecad/548/en-pl?filter=basic&value=0#q=Position
5.  `Area` - no string in Crowdin
    https://crowdin.com/translate/freecad/548/en-pl?filter=basic&value=0#q=Area
6.  `Volume` - no string in Crowdin
    https://crowdin.com/translate/freecad/548/en-pl?filter=basic&value=0#q=Volume
7.  `Tag` - no string in Crowdin
    https://crowdin.com/translate/freecad/548/en-pl?filter=basic&value=0#q=Tag
8.  `Material` - no string in Crowdin
    https://crowdin.com/translate/freecad/548/en-pl?filter=basic&value=0#q=Material
9.  `Label + Position` - no string in Crowdin
    https://crowdin.com/translate/freecad/548/en-pl?filter=basic&value=0#q=Label%20+%20
10.  `Label + Length` - no string in Crowdin
    https://crowdin.com/translate/freecad/548/en-pl?filter=basic&value=0#q=Label%20+%20
11.  `Label + Area` - no string in Crowdin
    https://crowdin.com/translate/freecad/548/en-pl?filter=basic&value=0#q=Label%20+%20
12.  `Label + Volume` - no string in Crowdin
    https://crowdin.com/translate/freecad/548/en-pl?filter=basic&value=0#q=Label%20+%20
13.  `Label + Material` - no string in Crowdin
    https://crowdin.com/translate/freecad/548/en-pl?filter=basic&value=0#q=Label%20+%20

**Comment by chennes** [comment]
@yorikvanhavre we have to rebuild this UI element, it's directly using the displayed text to look up the correct value. I'll get you a PR.

**Comment by chennes** [comment]
This should be fixed by https://github.com/FreeCAD/FreeCAD/pull/10228

**Comment by yorikvanhavre** [comment]
Thx! Closing then!

**Comment by kaktusus** [comment]
![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/9b4494be-f65a-41ce-b986-d977bcaa4eb5)
works
