### ISSUE TITLE
Draft → main menu → Drafting → selected tools

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#260]
```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33576 (Git) AppImage
Build type: Release
Branch: master
Hash: 8e6fbd2886d3ad51b75232bd0019d92d496e80cb
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
  * Curves 0.5.0
  * sheetmetal 0.2.56
  * Reinforcement
  * BIM 2021.12.0
  * Rocket 3.1.0
  * kicadStepUpMod 10.19.4
  * fasteners 0.4.56
  * Alternate_OpenSCAD 1.0.0
  * Render 2023.2.6
  * Movie 2023.6.10
```

Label on title bar is not translated. Applies to tools in this menu listed below.

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/3bee6669-b70c-41cd-addc-25b52d6be952)

`Polyline` - string is in Crowdin _(has attribute hidden)_
    https://
    https://crowdin.com/translate/freecad/548/en-pl#6606549

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/e83ab3c8-1204-4ea0-9281-621369da283b)

`Fillet` - string is in Crowdin _(has attribute hidden)_
    https://crowdin.com/translate/freecad/548/en-pl#6606963

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/f6041ed0-f16d-48a5-9921-6714f5f18645)

`Ellipse` - string is in Crowdin _(has attribute hidden)_
    https://crowdin.com/translate/freecad/548/en-pl#6607039

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/21e81981-d5f2-4ae2-bcd8-11cc44da3cf2)

`Rectangle` - string is in Crowdin _(has attribute hidden)_
    https://crowdin.com/translate/freecad/548/en-pl#6607123

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/90f12888-ddaf-4501-8e0c-3ba99d86a043)

`Polygon` - string is in Crowdin _(has attribute hidden)_
    https://crowdin.com/translate/freecad/548/en-pl#6606977

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/efe45510-35da-4af7-9c22-1ee6d3966d11)

`Bspline` - no string in Crowdin but for that we have `B-spline` _(has attribute hidden)_
    https://crowdin.com/translate/freecad/548/en-pl?filter=basic&value=0#q=Bspline

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/fc97f7ff-e9e6-44bc-be4b-4b6a6faea6f7)

`CubicBezCurve` - string is in Crowdin
    https://crowdin.com/translate/freecad/548/en-pl#6607011

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/d6b4fd96-4147-4e21-9dcc-12f97a385a1f)

`BezCurve` - string is in Crowdin
    https://crowdin.com/translate/freecad/548/en-pl#6607005

**Comment by chennes** [comment]
All the strings you are seeing in CrowdIn are in a different context: we need to also add them in the "draft" context.

**Comment by chennes** [comment]
This should be fixed by https://github.com/FreeCAD/FreeCAD/pull/10227

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34291 (Git) AppImage
Build type: Release
Branch: master
Hash: 71f1e6b09baa45812026832dfd74e59b5d4d1d35
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
  * Curves 0.6.13
  * sheetmetal 0.3.0
  * Rocket 3.2.1
  * kicadStepUpMod 10.19.4
  * fasteners 0.4.65
  * Render 2023.8.18
  * BIM 2021.12.0
  * FreeCAD-Reinforcement-added_translations.zip
  * FreeCAD-Reinforcement-master.zip
  * Reinforcement
  * Alternate_OpenSCAD 1.0.0
  * Woodworking 0.21.30486
  * dodo 1.0.0
  * Alternate_OpenSCAD.backup1691601718.9594336.zip
```
Everything works nicely.
Thank you :smile:
