### ISSUE TITLE
TechDraw → main menu → TechDraw → Insert Section View

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#261]
```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33593 (Git) AppImage
Build type: Release
Branch: master
Hash: 15371a04f38bbeb5a04edc5a91020ada1e30ef88
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
  * Curves 0.5.0
  * sheetmetal 0.2.56
  * Reinforcement
  * BIM 2021.12.0
  * Rocket 3.1.0
  * kicadStepUpMod 10.19.4
  * fasteners 0.4.56
  * Alternate_OpenSCAD 1.0.0
  * Render 2023.2.6
```

Found one label without a translation..

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/5d4ca4a1-8212-48be-906c-3b7245c07df8)

`No direction set` - string is in Crowdin
    https://crowdin.com/translate/freecad/27911/en-pl#6601849

Also applies to the tool complex section.

**Comment by WandererFan** [comment]
The code looks like it is asking for the translated string:
`    QString msgLiteral =
        QString::fromUtf8(QT_TRANSLATE_NOOP("TaskSectionView", "No direction set"));
    QString msgLiteral =
        QString::fromUtf8(QT_TRANSLATE_NOOP("TaskComplexSection", "No direction set"));
`
Is something else required?

**Comment by luzpaz** [comment]
Weird

**Comment by chennes** [comment]
That shouldn't use NOOP.

**Comment by chennes** [comment]
Will be fixed by https://github.com/FreeCAD/FreeCAD/pull/10189
