### ISSUE TITLE
TechDraw → main menu → TechDraw → Add hole or shaft fit

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#262]
```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33617 (Git) AppImage
Build type: Release
Branch: master
Hash: ae215724dd6c5336dcbb263733c6830a24917963
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
  * Curves 0.5.0
  * sheetmetal 0.2.56
  * Reinforcement
  * BIM 2021.12.0
  * Rocket 3.1.0
  * kicadStepUpMod 10.19.4
  * fasteners 0.4.56
  * Alternate_OpenSCAD 1.0.0
  * Render 2023.2.6
```

Not all labels in the task window have translations.

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/a309f455-600c-47ec-83e3-9e95c1b83c90)

`Hole /Shaft Fit ISO 286` - string is in Crowdin
    https://crowdin.com/translate/freecad/27911/en-pl#6611953

After switching to hole fit the displayed description has no translation.
Also, after changing the fit, translations are lost. There is no need to change the shaft / hole option.

**Comment by luzpaz** [comment]
CC @wandererfan
