### ISSUE TITLE
TechDraw → object names for view tools

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#264]
```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33631 (Git) AppImage
Build type: Release
Branch: master
Hash: 2167fb6f7ec6ac5c2f6365d4c3035d2db6879b1e
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

Some time ago _(#71)_ it was made possible to translate object names for the `Insert Projection Group` tool.

![image](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/d8ecc363-93dd-4b4f-8640-3f5b751a8176)

It is welcome to proceed consistently and translate these names for the other tools in the view group.

![image](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/f1d42e97-a30c-43cd-986a-5c7c5ec39313)

1. `View`
2. `Active view`
3. `Detail`
4. `Section`
5. `Section` for complex section

**Comment by luzpaz** [comment]
CC @wandererfan

**Comment by WandererFan** [comment]
I won't get this in for v0.21, but I'll put my notes here for posterity:
`// I think this can go anywhere, but QGIView.cpp would be the best place.
#if 0// needed for Qt's lupdate utility
    qApp->translate("DrawView", "View");
    qApp->translate("DrawViewPart", "View");
    qApp->translate("DrawViewSection", "Section");
    qApp->translate("DrawComplexSection", "ComplexSection");
    qApp->translate("DrawViewDetail", "Detail");
    qApp->translate("DrawActiveView", "ActiveView");
    qApp->translate("DrawViewAnnotation", "Annotation");
    qApp->translate("DrawViewImage", "Image");
    qApp->translate("DrawViewSymbol", "Symbol");
    qApp->translate("DrawViewArch", "Arch");
    qApp->translate("DrawViewDraft", "Draft");
#endif

// in QGIView.cpp drawBorder
    QString qClassName = QString::fromUtf8("DrawView");
    QString qTypeName = QString::fromUtf8(getViewObject()->getTypeId().getName());
    QRegularExpression rxClassName(QString::fromUtf8("^.+::(.+)"));
    QRegularExpressionMatch match;
    int pos = qTypeName.indexOf(rxFontSize, pos, &match));
    if ( qTypeName.indexOf(rxFontSize, pos, &match)) != -1) {
        qClassName  = match.captured(0);
    }
    QString labelStr = qApp->translate(qClassName, getViewObject()->Label.getValue());
    m_label->setPlainText(labelStr);
`

**Comment by WandererFan** [comment]
Can anybody provide guidance on how I would test this after making the code changes?  

I'm only familiar with the mad rush process at release time.

**Comment by kaktusus** [comment]
I can provide help and guidance if you have a translation test in mind.

**Comment by WandererFan** [comment]
This should be fixed by #10202.  It will probably need a Crowdin cycle before the results are apparent as I was testing with a local translation file.

**Comment by kaktusus** [comment]
great

**Comment by kaktusus** [comment]
thank you for implementing this feature
