### ISSUE TITLE
Start → Documents (tab) → Project icon context menu

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#265]
```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33636 (Git) AppImage
Build type: Release
Branch: master
Hash: a5e350ad469f4030b46baa6fd3d1770375f1ddd1
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
  * Curves 0.5.0
  * sheetmetal 0.2.56
  * Reinforcement
  * BIM 2021.12.0
  * Rocket 3.1.0
  * kicadStepUpMod 10.19.4
  * fasteners 0.4.56
  * Alternate_OpenSCAD 1.0.0
  * Render 2023.2.6
```

Not all context menu items have a translation.

![image](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/e4315d0c-1e43-4ca9-a38e-156028a25459)

1. `Save link` - no string in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Save%20link

2. `Copy link address` - no string in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Copy%20link%20address

**Comment by yorikvanhavre** [comment]
Same as #266

**Comment by kaktusus** [comment]
FreeCAD sources in the following location contain the file qtwebengine_pl.qm.

https://github.com/FreeCAD/FreeCAD/tree/master/src/Gui/Language

So I downloaded it and checked that the translations listed are correct.

![image](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/c0c68be6-ccf7-461c-87d0-350f4fac29ae)


`Copy link address` - I found another similar one `Copy Link URL`


Referring to the conversation in #266 possibly that "our" QT files are old and don't contain all the strings because after all you didn't invent them - right?

**Comment by kaktusus** [comment]
still needs attention.

**Comment by kaktusus** [comment]
We no longer have a start page.

```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37249 (Git) AppImage
Build type: Release
Branch: main
Hash: 3acbc561f299b4cddea8215c387a52f3d5132cf6
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```
