### ISSUE TITLE
Start → Documents (tab) → Contextual menu

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#266]
```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33636 (Git) AppImage
Build type: Release
Branch: master
Hash: a5e350ad469f4030b46baa6fd3d1770375f1ddd1
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
  * Curves 0.5.0
  * sheetmetal 0.2.56
  * Reinforcement
  * BIM 2021.12.0
  * Rocket 3.1.0
  * kicadStepUpMod 10.19.4
  * fasteners 0.4.56
  * Alternate_OpenSCAD 1.0.0
  * Render 2023.2.6
```

Context menu called on the window area - all items without translations.

![image](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/c4f3c4df-09c7-4585-a610-15d76aa6a077)

1. `Back` - no string in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Back

2. `Forward` - in Crowdin are occurrences without a match
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Forward

3. `Reload` - no string in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Reload

7. `Save page` - no string in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Save%20page

8. `View page source` - no string in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=View%20page%20source

**Comment by yorikvanhavre** [comment]
This all comes directly from Qt (These strings don't exist in the FreeCAD source). Probably we need to add the qtwebengine ts files from https://code.qt.io/cgit/qt/qttranslations.git/tree/translations , what do you think @chennes ?

**Comment by kaktusus** [comment]
FreeCAD sources in the following location contain the file `qtwebengine_pl.qm`.

https://github.com/FreeCAD/FreeCAD/tree/master/src/Gui/Language

So I downloaded it and checked that the translations listed are correct.
_All the strings appear and have translations except the last two._

`View page source` - I have not found 
`Save page` - I found another similar one `Save &Page`

Example:

![image](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/4f0f31d9-aabe-4fe9-816d-dcc2c3715f4c)

**Comment by yorikvanhavre** [comment]
> FreeCAD sources in the following location contain the file qtwebengine_pl.qm.

Oops I should have checked before talking :)

Hmm if some strings are missing there, I guess it's a Qt bug... We *could* change it ourselves but it's bad practice because those chages will be overwritten next time we reimport that file.

Wonder what happens if we add the string ourselves in one of our ts files? We'd need to figure out the correct context, though...

**Comment by kaktusus** [comment]
:wink:

> Wonder what happens if we add the string ourselves in one of our ts files? We'd need to figure out the correct context, though...

Last year I proposed such a solution.
The sources will shrink by a few - tens of kilobytes. A lot of files will also fall away. 
It will be easier for translators to find problems.

**Comment by kaktusus** [comment]
#149

**Comment by chennes** [comment]
It's a little strange, because our Qt translation files are *not* old -- I synced them just a month or two ago, they should be 100% up-to-date. I guess it's possible that because Qt Webengine is technically a separate project I missed those?

**Comment by yorikvanhavre** [comment]
This from our own source:
```bash
grep "View page source" src/Gui/Language/*
grep: qtwebengine_de.qm: binary file matches
grep: qtwebengine_ru.qm: binary file matches
grep: qtwebengine_zh_CN.qm: binary file matches
```
Apparently only *some* of the ts files are complete... :/
So I guess the best path forward is to contribute a translation to qt :sweat_smile:

**Comment by chennes** [comment]
Just noting here that it's in our medium-term plans to eliminate qtwebengine, at which time this will be obsolete.

**Comment by kaktusus** [comment]
Any information is invaluable.

**Comment by kaktusus** [comment]
We no longer have a start page.

```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37249 (Git) AppImage
Build type: Release
Branch: main
Hash: 3acbc561f299b4cddea8215c387a52f3d5132cf6
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```
