### ISSUE TITLE
FreeCAD homepage

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#268]
A large number of defects were described by David in this forum post: https://forum.freecad.org/viewtopic.php?style=4&p=697971#p697971
In addition, the fragments that require attention have been highlighted.

Documentation menu.
![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/ccd6c2a2-b063-4800-b25d-799dd4e68322)

Download page.
![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/af52de6e-6d15-43b0-801b-f8e8b83a466e)

Features page.
![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/c98abe0d-3863-4253-a31f-bef6875a50a3)

**Comment by chennes** [comment]
I have pushed a new homepage.po translation strings file to CrowdIn, those strings should now be available to translators.

**Comment by kaktusus** [comment]
Polish team already has them translated, we are waiting for others. :wink:

**Comment by kaktusus** [comment]
Everything works nicely.
Thank you :smiley:
