### ISSUE TITLE
[Crowdin] removal of `Form` strings and others

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#270]
Click the link
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Form
enable `exact match` filter
![image](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/1119f281-21d5-4490-b05c-410d3b47a5ad)

There are 67 instances of the string `Form` in Crowdin, which is not displayed in the GUI.

Switching them all to "cstring" is supposed to solve the problem and remove them from the translation platform.

**Comment by kaktusus** [comment]
the previous solution was not suitable in all cases.
another attempt concerns the parameter `notr="true"` for the insrtuction `string`.

**Comment by yorikvanhavre** [comment]
Should this be closed now?

**Comment by kaktusus** [comment]
I haven't finished chiseling away at GitHub yet.
There are about 100 instances of this case that need to be fixed. I have only fixed a third of them so far.
I will close this ticket when I defeat the monster. 

There are more similar instances but not on such a large scale.

**Comment by kaktusus** [comment]
> below is another example https://crowdin.com/translate/freecad/549/en-pl#6501279
> 
> ![obraz](https://user-images.githubusercontent.com/39754351/263720582-b4e8a7c0-2743-4c2b-bc02-20ea79601506.png)
> 
> Is this quirk necessary? There are several other cases.

@yorikvanhavre, do you have any idea where these strings came from?

**Comment by kaktusus** [comment]
:wink:

**Comment by kaktusus** [comment]
All of these strings are derived from: `FreeCAD.ts`
but I can't find them in the indicated source files.

[`[empty string]`](https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=%5Bempty%20string%5D)

The history has been shortened to a year so thesis is not helpful - https://crowdin.com/project/freecad/activity-stream?lang=38&translation_id=6501328

Is it possible to adjust the configuration so that the history is not truncated?
