### ISSUE TITLE
Start → Preferences → General → Tooltip "Select the workbench you want to switch to when you start the program"

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#272]
```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34198 (Git) AppImage
Build type: Release
Branch: master
Hash: e401e203af7ec9924de5174d5e2f63d2dc52fc2f
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
 ```

No translation of tooltip.

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/2ab7288b-069f-4b23-b446-b48a154ed41e)

`Choose which workbench to switch to after the program launches` - no string in Crowdin.

    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Choose%20which%20workbench%20to%20switch%20to%20after%20the%20program%20launches

here everything looks fine
![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/820f6ae5-5f1f-4f6d-b66d-2cf91190c7bb)

    https://github.com/kaktusus/FreeCAD/blob/master/src/Mod/Start/Gui/DlgStartPreferences.ui

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/861bef50-a6ba-4a52-92dc-3100af9f90ed)

    https://github.com/kaktusus/FreeCAD/blob/master/src/Mod/Start/Gui/Resources/translations/StartPage.ts

**Comment by chennes** [comment]
This was *just* changed: https://github.com/FreeCAD/FreeCAD/commit/22ea5299254ee0fa0399c98870e8374879f58ded

You should instead have the string "Workbench to switch to after loading a file from the Start page, only used if Start is the start up workbench"

**Comment by kaktusus** [comment]
these two strings functioned simultaneously in Crowdin,
how is this possible?

**Comment by chennes** [comment]
Is there anything further to resolve here?

**Comment by kaktusus** [comment]
The menu has been rebuilt and this option is available elsewhere
translation works correctly.
[Start up workbench:](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/579bd26d-55c6-459f-b9f9-484c104fe2de)
