### ISSUE TITLE
FreeCAD test version → Splash screen → "Please do not use it in a production environment."

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#273]
```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34198 (Git) AppImage
Build type: Release
Branch: master
Hash: e401e203af7ec9924de5174d5e2f63d2dc52fc2f
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
```

No translation of the second line of the displayed text.

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/68128204-eeda-413a-a20a-3e0ffb443013)

`Please do not use it in a production environment.` - string is in Crowdin
    https://crowdin.com/translate/freecad/549/en-pl?filter=basic&value=0#6626103

Here everything looks correct

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/ae3d6c35-6c10-4bc5-866c-65ad32a62459)
    https://github.com/kaktusus/FreeCAD/blob/master/src/Gui/MainWindow.cpp

However the translation source file does not include this string.
    https://github.com/kaktusus/FreeCAD/blob/master/src/Gui/Language/FreeCAD.ts

**Comment by chennes** [comment]
That string was changed this week (to include the word "it").

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34873 (Git) AppImage
Build type: Release
Branch: main
Hash: 889c8c49f1bbc0910c8dc32a512f4c6fbedeb8b9
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
```

fixed :smiley:
