### ISSUE TITLE
 AddonManager → "Apply {} update(s)"

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#274]
```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34198 (Git) AppImage
Build type: Release
Branch: master
Hash: e401e203af7ec9924de5174d5e2f63d2dc52fc2f
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
  * Curves 0.6.13
  * sheetmetal 0.3.0
  * Rocket 3.2.1
  * kicadStepUpMod 10.19.4
  * fasteners 0.4.65
  * Render 2023.8.18
  * BIM 2021.12.0
  * FreeCAD-Reinforcement-added_translations.zip
  * FreeCAD-Reinforcement-master.zip
  * Reinforcement
  * Alternate_OpenSCAD 1.0.0
  * Woodworking 0.21.30486
  * dodo 1.0.0
  * Alternate_OpenSCAD.backup1691601718.9594336.zip
```
It seems that the program adjusts the form of the string according to the number of updates found.
Crowdin does not contain properly prepared strings. 

[vokoscreenNG-2023-09-09_08-06-37.webm](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/53e6e01a-fb5b-4046-aeeb-467da6637994)

----

In addition we probably have a discrepancy.

Crowdin string link: https://crowdin.com/translate/freecad/32150/en-pl#6602913

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/5001d29a-cc44-40a4-b489-0bee77fe6850)

https://github.com/kaktusus/FreeCAD/blob/b277feed7d550cd11495c81d2178dafaa4b39146/src/Mod/AddonManager/AddonManager.py#L645

---
source file with strings: https://github.com/kaktusus/FreeCAD/blob/master/src/Mod/AddonManager/Resources/translations/AddonManager.ts

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/a622dd31-087b-4d24-b7dd-31f5a93c6e86)

https://github.com/kaktusus/FreeCAD/blob/b277feed7d550cd11495c81d2178dafaa4b39146/src/Mod/AddonManager/AddonManager.py#L719

**Comment by chennes** [comment]
The translation extraction is ignoring the plural -- that seems to be a bug in lextract, I will look into it.
