### ISSUE TITLE
 [Crowdin] removing unused strings

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#276]
A few ghosts of unknown origin still remain from the previous cleanup:

`Form`

The `Assembly.ts` file is indicated, however I was unable to find this string in the defined source. No information on which code file this string came from.

https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Form

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/d036fe6f-bf6a-4e21-864e-0af2aaa965af)

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/02e5e53d-9fdd-467d-984a-25e45cedfad1)
AND is it some kind of skydiver?

---

`[empty string]`

These strings can be found in the `FreeCAD.ts` file with very sparse information. For example, information about the location filename is missing.

https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=%5Bempty%20string%5D

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/dab5f28d-9782-4a37-93f6-f4713c41e245)

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/49e14d43-460d-437b-8e1e-a2eb2028f49d)

Interestingly, these strings appear only in Polish and Japanese language files.  I can edit them to remove unnecessary strings but is that enough to get them removed from Crowdin?

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/da2bd710-2db7-4e0f-830e-35afcdc80f9f)

**Comment by kaktusus** [comment]
Any ideas?

**Comment by chennes** [comment]
https://github.com/FreeCAD/FreeCAD/blob/1893ff00658d0292e62dc02a7d7daf4e28c31805/src/Gui/propertyeditor/PropertyItem.cpp#L502

**Comment by kaktusus** [comment]
`<empty>`=!`<empty string>`
:wink:

**Comment by kaktusus** [comment]
this stage has been closed
