### ISSUE TITLE
Sketcher → main menu / Sketch → Sketcher visual

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#277]
```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34387 (Git) AppImage
Build type: Release
Branch: master
Hash: d95b26dfb5dd23eaee004b4af3cf5cf4766e7f9c
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
 ```

Not all menu items have translations.

![image](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/e7af2619-d361-4e63-b2bd-6c71df0363a7)

`Sketcher visual` - no string in Crowdin

https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Sketcher%20visual

Code needs to be adapted?:
https://github.com/FreeCAD/FreeCAD/blob/c87860922c90007f71de9f1886ae8176e00ac977/src/Mod/Sketcher/Gui/Workbench.cpp#L91
https://github.com/FreeCAD/FreeCAD/blob/c87860922c90007f71de9f1886ae8176e00ac977/src/Mod/Sketcher/Gui/Workbench.cpp#L139
https://github.com/FreeCAD/FreeCAD/blob/c87860922c90007f71de9f1886ae8176e00ac977/src/Mod/Sketcher/Gui/Workbench.cpp#L167

**Comment by chennes** [comment]
The section at the top of that file that begins
```
#if 0  // needed for Qt's lupdate utility
```
needs to have "Sketcher visual" added to it.

**Comment by kaktusus** [comment]
There is also no translation for the toolbar of that name.
![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/4691cd8f-5f8d-40f4-9430-b8392fbdef09)

**Comment by kaktusus** [comment]
Please update Crowdin.

**Comment by kaktusus** [comment]
![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/8a2a905e-8853-4ed0-a406-420409bc7180)
![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/2dfdc7b0-4b25-48b9-a8d7-d3f23ec5ec3c)
Continuing to not work ...
```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36596 (Git) AppImage
Build type: Release
Branch: main
Hash: 380d452adb5da85f47543a316b6b533f84e829c7
Python 3.11.8, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
Installed mods: 

```
