### ISSUE TITLE
TechDraw → TechDraw menu → selected items (Page, Views from Other Workbenches, Clipped Views, Hatching, Symbols)

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#278]
```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34387 (Git) AppImage
Build type: Release
Branch: master
Hash: d95b26dfb5dd23eaee004b4af3cf5cf4766e7f9c
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
 ```

Not all menu items have translations.

![image](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/5249fac0-6e35-42c9-ba27-206a0771bd9a)

1. `Page` - There are several matches in Crowdin
    https://crowdin.com/translate/freecad/27911/en-pl?filter=basic&value=0#q=Page

2. `Views from Other Workbenches` - no string in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Views%20from%20other%20workbenches

3. `Clipped Views` - no string in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Clipped%20Views

4.  `Hatching` - no string in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Hatching

5.  `Symbols` - no string in Crowdin
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Symbols

Is the declaration missing?
https://github.com/FreeCAD/FreeCAD/blob/c87860922c90007f71de9f1886ae8176e00ac977/src/Mod/TechDraw/Gui/Workbench.cpp#L37

**Comment by chennes** [comment]
Yes, exactly right -- new developers don't always notice that you have to manually insert those strings there.

**Comment by kaktusus** [comment]
![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/206a955e-92ab-48f8-9ca1-d88f83a6f484)

Fixed

```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36677 (Git) AppImage
Build type: Release
Branch: main
Hash: 3fadb1f40bdfa4ee1c61acbf12fbe44680723965
Python 3.11.8, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
Installed mods: 
```
