### ISSUE TITLE
FreeCAD → Toolbar Structure

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#283]
```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34836 (Git) AppImage
Build type: Release
Branch: main
Hash: 862eef57eb4aa042f87d9f19dc768a017b17dae6
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
  * Curves 0.6.14
  * sheetmetal 0.3.1
  * Rocket 3.2.3
  * kicadStepUpMod 10.20.7
  * fasteners 0.4.68
  * Render 2023.8.18
  * BIM 2021.12.0
  * FreeCAD-Reinforcement-added_translations.zip
  * FreeCAD-Reinforcement-master.zip
  * Reinforcement
  * Alternate_OpenSCAD 1.0.0
  * Woodworking 0.21.30486
  * dodo 1.0.0
  * Alternate_OpenSCAD.backup1691601718.9594336.zip
  * OpenDark 2023.10.30
```

The toolbar has three tools of which one is a container. All have lost translations for hints.

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/0c5f9526-8fd9-42ab-ad12-88eefa3922d4)

Error in this string `is is`

`A Part is is a general purpose container to keep together a group of objects so that they act as a unit in the 3D view.
It is meant to arrange objects that have a Part TopoShape, like Part Primitives, PartDesign Bodies, and other Parts.` -  string is in Crowdin
    https://crowdin.com/translate/freecad/549/en-pl#6627325

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/f938df0f-1ae1-4056-92b8-d46c01d5ee29)

`A Group is a general purpose container to group objects in the Tree view, regardless of their data type. It is a simple folder to organize the objects in a model.` - string is in Crowdin.
    https://crowdin.com/translate/freecad/549/en-pl#6627309

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/237731f1-e2d4-48db-beed-6706a4afcbb1)

`A Link is an object that references or links to another object in the same document, or in another document.Unlike Clones, Links reference the original Shape directly,  making them more memory efficient which helps with the creation of complex assemblies.` - stringis in Crowdin.
    https://crowdin.com/translate/freecad/549/en-pl#6627317

**Comment by chennes** [comment]
Someone had tried to add some HTML tags outside the NOOP-translated string, which meant that when it was actually queried for translation the string did not match.

**Comment by kaktusus** [comment]
probably requires export to Crowdin, and later import from Crowdin
