### ISSUE TITLE
Part / PartDesign →  Selection Filter component

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#284]
```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35046 (Git) AppImage
Build type: Release
Branch: main
Hash: 6a66034ce27290e7b385a933d77375f55492d194
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
  * Curves 0.6.14
  * sheetmetal 0.3.12
  * Rocket 3.2.4
  * kicadStepUpMod 10.21.4
  * fasteners 0.4.70
  * Render 2023.8.18
  * BIM 2021.12.0
  * FreeCAD-Reinforcement-added_translations.zip
  * FreeCAD-Reinforcement-master.zip
  * Reinforcement
  * Alternate_OpenSCAD 1.0.0
  * Woodworking 0.21.30486
  * dodo 1.0.0
  * Alternate_OpenSCAD.backup1691601718.9594336.zip
  * OpenDark 2023.10.30
  * freecad.gears 1.0.0
```

Lack of translations for tools and tooltips.

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/175dcd04-63f6-4361-ac10-4ee8c643eb87)

`Selection filter` - string is in Crowdin
https://crowdin.com/translate/freecad/563/en-pl#6627876

`Change the selection filter` - string is in Crowdin
https://crowdin.com/translate/freecad/563/en-pl#6627878

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/bf46106d-2dcb-4c04-bb63-dc3cab174859)

`Vertex selection` - string is in Crowdin
https://crowdin.com/translate/freecad/563/en-pl#6627880

`Only allow the selection of vertices` - string is in Crowdin
https://crowdin.com/translate/freecad/563/en-pl#6627882

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/85ec2a8e-7704-422d-aa5d-0a134ef03d00)

`Edge selection` - string is in Crowdin
https://crowdin.com/translate/freecad/563/en-pl#6627884

`Only allow the selection of edges` - string is in Crowdin
https://crowdin.com/translate/freecad/563/en-pl#6627886

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/8f441eeb-f0f1-46cf-9ce1-7884c8e4ba9e)

`Face selection` - string is in Crowdin
https://crowdin.com/translate/freecad/563/en-pl#6627888

`Only allow the selection of faces` - string is in Crowdin
https://crowdin.com/translate/freecad/563/en-pl#6627890

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/967d7862-7c2a-4552-8a3e-17bf6510da83)

`All selection filters cleared` - string is in Crowdin
https://crowdin.com/translate/freecad/563/en-pl#6627892

Hint duplicated with the name of the option, it is worth correcting.
These translations have been missing from the GUI for a long time. :sob:

**Comment by kaktusus** [comment]
Another occurrence in the 3D view context menu.

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/42476422-c091-4bad-8c93-3ec01522211f)

**Comment by chennes** [comment]
The PR I reference above fixes the menu items themselves -- it's not clear to me that the "Selection filter" text itself is still wrong, it seemed right in my testing.

**Comment by kaktusus** [comment]
Selection filter has a translation see the video below "Filtr wyboru"

[vokoscreenNG-2024-03-05_05-52-50.webm](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/183ac906-f1de-48e1-9801-5f5a60241181)

**Comment by chennes** [comment]
OK, great, then https://github.com/FreeCAD/FreeCAD/pull/12761 will close this

**Comment by kaktusus** [comment]
fixed:
```OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36331 (Git) AppImage
```

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/9124939a-7c22-4ad0-ac01-5c810b990891)
![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/b63f9922-6dcb-46e4-949e-8fbd3584cfd1)
