### ISSUE TITLE
FreeCAD → Edit → Preferences → General → Help

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#290]
```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35176 (Git) AppImage
Build type: Release
Branch: main
Hash: dcd533af4bf0cb3dbc50c7d0e2fb579cad168819
Python 3.10.13, Qt 5.15.8, Coin 4.0.1, Vtk 9.2.6, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
  * Curves 0.6.14
  * sheetmetal 0.3.12
  * Rocket 3.2.4
  * kicadStepUpMod 10.21.4
  * fasteners 0.4.70
  * Render 2023.8.18
  * BIM 2021.12.0
  * FreeCAD-Reinforcement-added_translations.zip
  * FreeCAD-Reinforcement-master.zip
  * Reinforcement
  * Alternate_OpenSCAD 1.0.0
  * Woodworking 0.21.30486
  * dodo 1.0.0
  * Alternate_OpenSCAD.backup1691601718.9594336.zip
  * OpenDark 2023.10.30
  * freecad.gears 1.0.0
```

The entire contents of the "Help" tab have no translations.
Both for the name of the option and the pop-up tips. 

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/613258e8-2c74-4bcd-ae5b-27793007d956)

All strings are in Corwdin. 

`FreeCAD Wiki (online)` - https://crowdin.com/translate/freecad/32170/en-pl#6627478
`The documentation pages will be fetched from the official
FreeCADwiki at https://wiki.freecad.org` - https://crowdin.com/translate/freecad/32170/en-pl#6627602

`Markdown version (online)` - https://crowdin.com/translate/freecad/32170/en-pl#6627482
`The documentation pages will be fetched from an automatic Markdown conversion
of the FreeCAD wiki,hosted on FreeCAD&apos;s GitHub account. This can be styled with a
custom stylesheet below and can look nicer than the wiki option. The &apos;Markdown&apos; or
&apos;Pandoc&apos; Python module should be installed for optimal results.` - https://crowdin.com/translate/freecad/32170/en-pl#6627604

`GitHub (online)` - https://crowdin.com/translate/freecad/32170/en-pl#6627596
`This will fetch the documentation from pages rendered on GitHub.
This is currently not available...` - https://crowdin.com/translate/freecad/32170/en-pl#6627594

`Custom location` - https://crowdin.com/translate/freecad/32170/en-pl#6627470
`Set this to a custom URL or the folder where the help files are located.
You can easily download the documentation for offline use by using the Addon
Manager and installing the &quot;offline documentation&quot; addon. If this
field is left blank, FreeCAD will automatically search for the help files at
the default location ($USERAPPDATADIR/Mod/Documentation).` - https://crowdin.com/translate/freecad/32170/en-pl#6627598

`    Translation suffix:` - https://crowdin.com/translate/freecad/32170/en-pl#6627474
`A translation suffix to use, for example &quot;fr&quot;
to get French translation of the documentation.` - https://crowdin.com/translate/freecad/32170/en-pl#6627600

`Display` - https://crowdin.com/translate/freecad/32170/en-pl#6627484
`
`In a FreeCAD tab` - https://crowdin.com/translate/freecad/32170/en-pl#6627488
`The documentation will open in a new tab inside the FreeCAD interface.` - https://crowdin.com/translate/freecad/32170/en-pl#6627486

`In your default web browser` - https://crowdin.com/translate/freecad/32170/en-pl#6627492
`The documentation will open in your default web browser.` - https://crowdin.com/translate/freecad/32170/en-pl#6627606

`In a separate, embeddable dialog` - https://crowdin.com/translate/freecad/32170/en-pl#6627496
`The documentation will open in a dockable dialog inside the FreeCAD window,
which allows you to keep it open whlle working in the 3D view.` - https://crowdin.com/translate/freecad/32170/en-pl#6627608

`Options` - https://crowdin.com/translate/freecad/32170/en-pl#6627498

`      Custom stylesheet:` - https://crowdin.com/translate/freecad/32170/en-pl#6627500
`You can here indicate the path to an alternative CSS file to be used
to style the Markdown pages. This will only work if you have selected the
Markdown version above.` - https://crowdin.com/translate/freecad/32170/en-pl#6627610

**Comment by yorikvanhavre** [comment]
The translations were just not downloaded yet I think... Will do a cycle later today

**Comment by chennes** [comment]
Where does this stand now, @kaktusus ? Can we close the broad Issue and open individual ones for missing strings?

**Comment by kaktusus** [comment]
I'll check it out today.

**Comment by kaktusus** [comment]
No change - no translations in all places.

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/62f5cb1e-9331-4b12-ba40-32bca90700d6)

I wouldn't close this ticket just yet.

**Comment by kaktusus** [comment]
![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/fb4389b9-c5fd-4b93-8492-ebc0a323b598)

Fixed

```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36677 (Git) AppImage
Build type: Release
Branch: main
Hash: 3fadb1f40bdfa4ee1c61acbf12fbe44680723965
Python 3.11.8, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
Installed mods: 
```
