### ISSUE TITLE
Part design -> menu PartDesign

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#3]
```
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.24992 (Git) AppImage
Build type: Release
Branch: master
Hash: 9332e52d944c1339e3b9a1b5a72dc6edc6d077a8
Python version: 3.9.4
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: Polish/Poland (pl_PL)
```
![obraz](https://user-images.githubusercontent.com/39754351/120902404-81092980-c640-11eb-9d81-8cf3d36093a7.png)
the three utilities at the bottom of the menu do not have translations.

**Comment by luzpaz** [comment]
This should be tested again once @yorikvanhavre push/pulls crowdin again

**Comment by kaktusus** [comment]
Tickets are closed too fast, I also think this should be checked again.

**Comment by kaktusus** [comment]
I liked it when you marked the submission for closure, and when I confirmed that everything was ok only then was it closed.
Maybe it needs more attention but it is the right way.

**Comment by luzpaz** [comment]
It auto-closed since I wrote `Fixes` in the git summary:

![image](https://user-images.githubusercontent.com/4140247/123025809-35c57980-d3a9-11eb-9512-69c04d0e518e.png)

I'll refrain from doing that from here on out
