### ISSUE TITLE
Sketcher → Create rectangle (tool)

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#302]
```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36228 (Git) AppImage
Build type: Release
Branch: main
Hash: 6c8ee5964521a99e01c8d33cbf9aac8a19273ef3
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
  * Curves 0.6.23
  * Rocket 3.3.0
  * kicadStepUpMod 10.23.2
  * fasteners 0.5.12
  * BIM 2021.12.0
  * FreeCAD-Reinforcement-added_translations.zip
  * FreeCAD-Reinforcement-master.zip
  * Reinforcement
  * Alternate_OpenSCAD 1.0.0
  * dodo 1.0.0
  * Alternate_OpenSCAD.backup1691601718.9594336.zip
  * OpenDark 2023.12.17
  * sheetmetal 0.4.2
  * Render 2024.1.23
  * freecad.gears 1.2.0
  * Movie 2024.2.15
  * Assembly3 0.12.2
  * pcb 6.2023.1
  * FreeCAD-NativeIFC 2023.10.27
  * woodworking 0.21.2.33771
```

No translations in the drop-down list of the Rectangle parameters task panel.

Gif ...
![Peek 2024-03-03 20-27](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/4045970f-704a-4b60-b0d4-58c8106dc1ec)

`Corner, width, height` - no string in Crowdin
https://crowdin.com/editor/freecad/all/en-pl?view=comfortable&filter=basic&value=0#q=corner,%20width,%20height

`Center, width, height` - no string in Crowdin
https://crowdin.com/editor/freecad/all/en-pl?view=comfortable&filter=basic&value=0#q=Center,%20width,%20height

`3 corners` - no string in Crowdin.
https://crowdin.com/editor/freecad/all/en-pl?view=comfortable&filter=basic&value=0#q=3%20corners

`Center, 2 corners` - no string in Crowdin.
https://crowdin.com/editor/freecad/all/en-pl?view=comfortable&filter=basic&value=0#q=Center,%202%20corners

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/161e5dea-ff5e-4543-bb97-5ccedab9b36e)
problem found by David69 of the forum.

Pop-up hint without translation.
![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/5cd7260b-90a3-4448-a228-a604d4284955)

`Create two rectangles with a constant offset.` - string is in Crowdin
https://crowdin.com/editor/freecad/569/en-pl?view=comfortable#6634852

**Comment by chennes** [comment]
This same problem is true for circle, arc, arc slot, ellipse, line, and offset. I will fix in a second PR.

**Comment by kaktusus** [comment]
![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/61778319-da09-4541-8475-8fe840ad57a4)

Continuing to not work ...
```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36596 (Git) AppImage
Build type: Release
Branch: main
Hash: 380d452adb5da85f47543a316b6b533f84e829c7
Python 3.11.8, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
Installed mods: 
```
