### ISSUE TITLE
Sketcher → Sketcher geometries (toolbar) → Create conic

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#305]
```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36228 (Git) AppImage
Build type: Release
Branch: main
Hash: 6c8ee5964521a99e01c8d33cbf9aac8a19273ef3
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 

```

Label translations and tooltips are missing.

1. ![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/279f6529-4613-4a30-bc83-9eed29a9d8e2)

`Ellipse by center, radius, rim point` - string is in Crowdin.
    https://crowdin.com/editor/freecad/569/en-pl?view=comfortable#6634604

`Create an ellipse by its center, one of its radii and a rim point` - string is in Crowdin.
    https://crowdin.com/editor/freecad/569/en-pl?view=comfortable#6634864

----
2. ![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/bf1cb9a1-ffe2-40a0-9674-802b3ba7bd8b)

`Ellipse by axis endpoints, rim point` - string is in Crowdin.
    https://crowdin.com/editor/freecad/569/en-pl?view=comfortable#6634606

`Create an ellipse by the endpoints of one of its axes and a rim point` - string is in Crowdin.
    https://crowdin.com/editor/freecad/569/en-pl?view=comfortable#6634866

----
3. ![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/f7a23bf7-0d21-4cb0-ae29-2eb8f712919b)

`Arc of ellipse by center, radius, endpoints` - string is in Crowdin.
    https://crowdin.com/editor/freecad/569/en-pl?view=comfortable#6634608

`Create an arc of ellipse by its center, one of its radii, and its endpoints` - string is in Crowdin.
    https://crowdin.com/editor/freecad/569/en-pl?view=comfortable#6634868

----
4.![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/4b55a125-089d-405e-8f85-bf50bf67a52e)

`Arc of hyperbola by center, vertex, endpoints` - string is in Crowdin.
    https://crowdin.com/editor/freecad/569/en-pl?view=comfortable#6634610

`Create an arc of hyperbola by its center, vertex and endpoints` - string is in Crowdin.
    https://crowdin.com/editor/freecad/569/en-pl?view=comfortable#6634870

----
5. ![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/d9909b1f-b4bd-4ffd-b2a3-c5519ba44735)

`Create an arc of parabola by its focus, vertex and endpoints` - string is in Crowdin.
    https://crowdin.com/editor/freecad/569/en-pl?view=comfortable#6634872

**Comment by chennes** [comment]
Should be fixed by https://github.com/FreeCAD/FreeCAD/commit/1e164f24c0673976b892d6bba706b98cfc4fea14

**Comment by kaktusus** [comment]
fixed:

```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36331 (Git) AppImage
```

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/cf822b21-2f4e-4e51-8ae3-d88f304fd80c)
