### ISSUE TITLE
 Sketcher → Sketcher geometries (toolbar) → Create fillet

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#306]
```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36228 (Git) AppImage
Build type: Release
Branch: main
Hash: 6c8ee5964521a99e01c8d33cbf9aac8a19273ef3
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 

```

Tool label has no translation.

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/a78f91f4-a067-41f4-be94-4abd4757f57d)

`Corner-preserving sketch fillet` -string is in Crowdin
    https://crowdin.com/editor/freecad/569/en-pl?view=comfortable#6634618

**Comment by chennes** [comment]
Should be fixed by https://github.com/FreeCAD/FreeCAD/commit/1e164f24c0673976b892d6bba706b98cfc4fea14

**Comment by kaktusus** [comment]
fixed:

```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36331 (Git) AppImage
```

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/bf74f497-47d1-4942-bee5-e899cdef8109)
