### ISSUE TITLE
FreeCAD → Edit → Preferences → Visibility → UI

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#307]
```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36228 (Git) AppImage
Build type: Release
Branch: main
Hash: 6c8ee5964521a99e01c8d33cbf9aac8a19273ef3
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 

```

Label translations and tooltips are missing.

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/34103db5-722e-4095-8ded-3dc33776dd9a)

`Show visibility icon` - string is in the Crowdin
    https://crowdin.com/editor/freecad/549/en-pl?view=comfortable#6634850

`If enabled, show an eye icon before the tree view items, showing the items visibility status. When clicked the visibility is toggled` - string is in the Crowdin
   https://crowdin.com/editor/freecad/549/en-pl?view=comfortable#6634892

**Comment by chennes** [comment]
Should be fixed by https://github.com/FreeCAD/FreeCAD/commit/1e164f24c0673976b892d6bba706b98cfc4fea14

**Comment by kaktusus** [comment]
![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/c16198a7-8a4c-4cdb-ab5e-c6a14850a31d)

Fixed

```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36677 (Git) AppImage
Build type: Release
Branch: main
Hash: 3fadb1f40bdfa4ee1c61acbf12fbe44680723965
Python 3.11.8, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
Installed mods: 
```
