### ISSUE TITLE
Part Design → Make a thick solid (tool)

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#31]
```
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.25025 (Git) AppImage
Build type: Release
Branch: master
Hash: fb8b21ec43dca706a4aa2d63d59a4fb79f050369
Python version: 3.9.4
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: Polish/Poland (pl_PL)
```

Section title in tool window has no translation

![obraz](https://user-images.githubusercontent.com/39754351/121811090-816a7b80-cc63-11eb-8766-8492e126c880.png)

1. Thickness parameters
no string in Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Thickness%20parameters

1. The Cancel button has an untranslated label
;-)

**Comment by luzpaz** [comment]
Weird, I can't find the `Thickness parameters` string in the source code all.  Hey @ickby can you shed some light on this at all?

**Comment by ickby** [comment]
I tried to find it too, but did not. I can't remember how this naming is set... Sorry

**Comment by luzpaz** [comment]
@wwmayer any idea ?

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28793 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 5386d4e)
Hash: 5386d4ed864cd03edd026e1d3d128cccedf568df
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

After recent updates the problem still persists ...

![obraz](https://user-images.githubusercontent.com/39754351/167263930-2821fd23-1cda-4769-985c-c2a71e94d36c.png)

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28884 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 51fdb42)
Hash: 51fdb42f21b4c6a7c9f91956e51427b896070f96
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

The function key label has a translation.
Fix https://github.com/FreeCAD/FreeCAD/pull/6883

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28945 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0fb7cd9)
Hash: 0fb7cd9758d850f536d571cc094c9833fee18fff
Python 3.9.13, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```


Fixed.


![obraz](https://user-images.githubusercontent.com/39754351/170878664-f4b6dd95-3cde-4306-a119-7c1ca219e30c.png)
