### ISSUE TITLE
 Part Design → Measure Linear (tool)

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#32]
```
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.25025 (Git) AppImage
Build type: Release
Branch: master
Hash: fb8b21ec43dca706a4aa2d63d59a4fb79f050369
Python version: 3.9.4
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: Polish/Poland (pl_PL)
```

Buttons in the tool window have no translations

![obraz](https://user-images.githubusercontent.com/39754351/121811513-f4c0bd00-cc64-11eb-8d78-8e53ff8569ff.png)

1. Selection
no string in Crowdin

2. Reset selection
no string in Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Reset%20selection

1. Toggle direct dimensions
no string in Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Toggle%20direct%20dimensions

1. Toggle orthogonal dimensions
no string in Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Toggle%20orthogonal%20dimensions

2. Clear all dimensions
no string in Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Clear%20all%20dimensions

1. Close button label has no translation.

**Comment by Kuzma30** [comment]
https://github.com/FreeCAD/FreeCAD/blob/72e91dbbca9094d9bd56b1d47a1eeaaeb7266849/src/Mod/Part/Gui/TaskDimension.cpp#L1400
for problem no 1.

**Comment by Kuzma30** [comment]
![Знімок екрана з 2022-05-05 10-53-32](https://user-images.githubusercontent.com/1382812/166882689-2e055d18-959a-49e7-99cb-285c2dd88912.png)
Solution for no 1.
https://github.com/Kuzma30/FreeCAD/commit/836c24c18324c8fb3876699649fb0eb42a106977

**Comment by luzpaz** [comment]
Due to @Kuzma30's PR which was merged, the issue should be fixed in https://github.com/FreeCAD/FreeCAD/commit/3e7ad90b7bbecd6c4c90eb1b1695d03a361c17e6

Please re-open if not.

**Comment by kaktusus** [comment]
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28793 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 5386d4e)
Hash: 5386d4ed864cd03edd026e1d3d128cccedf568df
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...



![obraz](https://user-images.githubusercontent.com/39754351/167255669-d6731607-d0aa-4d55-bcea-30f4afa5d044.png)

After recent updates ...
In Aleks picture, you can see the better quality of the translation ...
it's interesting
