### ISSUE TITLE
FreeCAD → preferences → Import-export → NativeIFC

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#320]
```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36996 (Git) AppImage
Build type: Release
Branch: main
Hash: d92f74ef019fcedbdcdc32055ab2437c950ac23b
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
Installed mods: 

```

The entire page of preferences has no translations.

![obraz](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/c935adbd-dc4c-4ae6-8334-92d7e2914fd9)

The hints also have no translations.
No strings in Crowdin.

**Comment by kaktusus** [comment]
Has this menu item been removed or do I not know how to call it up now?

**Comment by luzpaz** [comment]
@yorikvanhavre could you shed light here ?

**Comment by yorikvanhavre** [comment]
![image](https://github.com/user-attachments/assets/126f35b1-0d72-4280-b74d-b65790f378f1)
Everything looks normal to me?

**Comment by luzpaz** [comment]
It moved to BIM placeholder. Thanks. Looks fixed. Closing.

**Comment by kaktusus** [comment]
:wink:
