### ISSUE TITLE
Part → lack of presentation of translations

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#33]
**This WB** has so many shortcomings that it is impossible to describe everything at this stage,
These include untranslated captions in popup tips, menu captions, and the tools themselves and their windows.

Not all strings are in Crowdin, and there are some that have been exported there, translated, and are not presented in FreeCAD.

Once this is sorted out by the programmers, I'll be happy to see if there are any corrections left to be made.

**Comment by luzpaz** [comment]
@chennes do you think there is a similiar issue here with Part WB as there was with PD in https://github.com/FreeCAD/FreeCAD/pull/4961 ?

**Comment by chennes** [comment]
In some ways it looks like it might be the opposite problem. Is it mostly C++ strings that are missing? My recollection of that script is that it basically assumes single-language modules. I don't think it would be hard to fix, but I'll have to look more closely.

**Comment by yorikvanhavre** [comment]
We need to look better at which strings are not in crowdin, to try to see if either a certain file is not picked by lupdate scripts, or if something in a file is wrongly formatted

**Comment by kaktusus** [comment]
Should I take care of it ?

**Comment by luzpaz** [comment]
@kaktusus it would help immensely if you do. I'll focus on other tickets in the meantime

**Comment by kaktusus** [comment]
ok, so this will be my assignment

**Comment by chennes** [comment]
While you work on that, I'm working on refactoring the extraction script to ensure that no matter whether a mod is Python or C++, both programming languages are scanned all the time, so we don't miss anything. https://github.com/FreeCAD/FreeCAD/pull/5037

**Comment by kaktusus** [comment]
I have prepared some reports, I think that these are not all the irregularities


Part → menu Part / Attachment... (tool) #70
Part → menu Part / Create projection on surface... (tool) #69
Part → menu Part / Check geometry (tool) #68
Part → menu Part / Create primitives... (tool) #67
Part → menu Part / Split (menu tools) #66
Part → menu Part / Create a copy / Create transformed copy (... menu tools) #65
Part → Part menu #64

the next I have to prepare ...

**Comment by kaktusus** [comment]
next submissions:

Part → Chamfer... (tool) #74
Part → Utility to offset ... (component) #75
 Part → Color per face (tool) #76

**Comment by kaktusus** [comment]
let's just say that at the moment I have explored the main options and tools of the Part workbench.

**Comment by chennes** [comment]
I'm going to close this ticket since it's been migrated to all of the actionable sub-issues. I'm slowing chipping away at those now. If you find more, of course, just keep making issues.

**Comment by kaktusus** [comment]
yes I will continue, there are a lot of things to present here, but my time is severely limited by what is going on in my private life.
And the fact that for the past six months developers have had little interest in this corner of the FC world has not helped with self-motivation.
