### ISSUE TITLE
FreeCAD → The tree view context menu

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#332]
```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37730 (Git) AppImage
Build type: Release
Branch: main
Hash: 30f7f2688921e6e5242beaa9d71e0fdd844b20e3
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
Installed mods: 
  * Curves 0.6.39
  * Render 2024.6.5
  * Alternate_OpenSCAD 1.0.0
  * Plot 2022.4.17
  * dodo 1.0.1
  * Rocket 3.3.0
  * pcb 6.2023.1
  * freecad.gears 1.2.0
  * Marz 0.1.5
  * Movie 2024.2.15
  * sheetmetal 0.4.18
  * Reinforcement
  * kicadStepUpMod 11.2.0
  * kicadStepUp.zip
  * fasteners 0.5.22
  * OpenTheme 2024.5.16
  * woodworking 0.21.2.33771
```

No translation in the context menu in the Tree View.

Invoke the context menu of the tree view,
click _Tree settings_ ...

![image](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/2eb95cc1-44e7-4fbf-aef3-58d1e34fd988)

`Show internal name` – no string in Crowdin
    https://crowdin.com/editor/freecad/all/en-pl?view=comfortable&filter=basic&value=0#q=show%20internal%20name

Translation also missing from column header:
`Internal name` – no srting in Crowdin
    https://crowdin.com/editor/freecad/all/en-pl?view=comfortable&filter=basic&value=0#q=Internal%20name

**Comment by luzpaz** [comment]
Has this been addressed  in https://github.com/FreeCAD/FreeCAD/pull/16122 ?

**Comment by hasecilu** [comment]
> Has this been addressed in [FreeCAD/FreeCAD#16122](https://github.com/FreeCAD/FreeCAD/pull/16122) ?

Yes, it's there.

**Comment by kaktusus** [comment]
The premature washing out of reports has often in the past necessitated the publication of new identical ones.

**Comment by luzpaz** [comment]
@kaktusus they can be re-opened though, right ?

**Comment by kaktusus** [comment]
Sometimes I do and sometimes I don't have that super power .... :smile:

**Comment by luzpaz** [comment]
@kaktusus do you have permissions for this repo ?

**Comment by kaktusus** [comment]
I can do basic things, but when reports close the manager I can't always reopen them.

This is the case with this ticket. :last_quarter_moon:

**Comment by luzpaz** [comment]
@yorikvanhavre can you give @kaktusus permissions to re-open tickets in this repo ?

**Comment by kaktusus** [comment]
Fixed:

```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 1.0.0RC1.38643 (Git) AppImage
```

![obraz](https://github.com/user-attachments/assets/d9dbe95d-9e62-43f8-92d9-e7f31380e4b7)
