### ISSUE TITLE
Draft → main menu

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#34]
```
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.25025 (Git) AppImage
Build type: Release
Branch: master
Hash: fb8b21ec43dca706a4aa2d63d59a4fb79f050369
Python version: 3.9.4
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: Polish/Poland (pl_PL)
```
Main menu after module loading, has untranslated items.

![obraz](https://user-images.githubusercontent.com/39754351/121893543-5db83b80-cd1e-11eb-9425-c35991a5d1f7.png)

1. Annotation
there are several items on Draft WB with a status of hidden.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Annotation
2. Modification
There is a "Modification" item in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Modification
3. Utilities
There is a "Utilities" item in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Utilities

**Comment by luzpaz** [comment]
Was able to mark visible
- [x] `&Annotation`
- [x] `&Modification` 

`&Utilities` was already marked visible though https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=3#6576928

**Comment by Roy-043** [comment]
There was also an issue with an incorrect context in the source code. This should be fixed with: https://github.com/FreeCAD/FreeCAD/pull/5370.

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.27319 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 67706b1)
Hash: 67706b14df32b91b948952ea2c9350948ba4d4db
Python version: 3.9.10
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.3
Locale: Polish/Poland (pl_PL)
```
solved
