### ISSUE TITLE
Draft → menu Drafting

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#36]
```
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.25065 (Git) AppImage
Build type: Release
Branch: master
Hash: 4de2ad46b2b9c78ac2721a0dbea7c19306261095
Python version: 3.9.4
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: Polish/Poland (pl_PL)
```

Utility label and tooltip do not have translations in the GUI. Applies to the menu and toolbar.
![obraz](https://user-images.githubusercontent.com/39754351/121901311-922ff580-cd26-11eb-8f8f-b5afad5fc6df.png)
![obraz](https://user-images.githubusercontent.com/39754351/121904217-49c60700-cd29-11eb-9654-080163d08df4.png)

1. Arc by 3 point
The string is present in Crowdin, but is not displayed in the GUI.
https://crowdin.com/translate/freecad/548/en-pl#6587756

2. Creates a circular arc by a center point and a radius.
CTRL to snap, SHIFT to constrain.
The string is present in Crowdin, but is not displayed in the GUI.
https://crowdin.com/translate/freecad/548/en-pl#6587756

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.26238 AppImage
Build type: Release
Branch: (HEAD detached at 237229c)
Hash: 237229c3fc8df1ddede445d3495a0ac640d63e4f
Python version: 3.9.7
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.3
Locale: Polish/Poland (pl_PL)
```

We have a regression ...

This string previously had a correctly displayed translation

![obraz](https://user-images.githubusercontent.com/39754351/140411447-e5d07998-c0ea-4fd1-a129-835d862d25b8.png)

`Arc tools`
https://crowdin.com/translate/freecad/548/en-pl#6586762

**Comment by Roy-043** [comment]
This should be fixed with: https://github.com/FreeCAD/FreeCAD/pull/5370.

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.27319 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 67706b1)
Hash: 67706b14df32b91b948952ea2c9350948ba4d4db
Python version: 3.9.10
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.3
Locale: Polish/Poland (pl_PL)
```

Solved.
It's a bit of a pity that hint pop-ups have been disabled in the menu.

**Comment by Roy-043** [comment]
> hint pop-ups have been disabled in the menu

These items are now treated as normal menu items. Before they were part of a button group. Normal menu items do not display a tooltip. I actually do not know why that is.

**Comment by kaktusus** [comment]
I have noticed that some have these labels and others do not. It is different in different WB.
The labels are also displayed in the status bar - at the bottom.
