### ISSUE TITLE
Draft → menu Modification / Array tools / Array (tool)

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#37]
```
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.25065 (Git) AppImage
Build type: Release
Branch: master
Hash: 4de2ad46b2b9c78ac2721a0dbea7c19306261095
Python version: 3.9.4
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: Polish/Poland (pl_PL)
```

Utility label and tooltip do not have translations in the GUI.
![obraz](https://user-images.githubusercontent.com/39754351/121907620-834c4180-cd2c-11eb-9ef5-0f2fd1c4a78c.png)

1. Array tools
The string is present in Crowdin, but is not displayed in the GUI.
https://crowdin.com/translate/freecad/548/en-pl#6586718

2. Creates copies of the selected object, and places the copies in an orthogonal pattern,
meaning the copies follow the specified direction in the X, Y, Z axes.

The array can be turned into a polar or a circular array by changing its type.

The string is present in Crowdin, but is not displayed in the GUI.
https://crowdin.com/translate/freecad/548/en-pl#6586724

Also applies to the toolbar.

**Comment by Roy-043** [comment]
This should be fixed with: https://github.com/FreeCAD/FreeCAD/pull/5370.

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.27319 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 67706b1)
Hash: 67706b14df32b91b948952ea2c9350948ba4d4db
Python version: 3.9.10
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.3
Locale: Polish/Poland (pl_PL)
```

Solved.
It's a bit of a pity that hint pop-ups have been disabled in the menu.
