### ISSUE TITLE
Draft → menu Modification / Array tools / Circular array (tool)

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#39]
```
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.25065 (Git) AppImage
Build type: Release
Branch: master
Hash: 4de2ad46b2b9c78ac2721a0dbea7c19306261095
Python version: 3.9.4
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: Polish/Poland (pl_PL)
```

Utility label and tooltip do not have translations in the GUI.
![obraz](https://user-images.githubusercontent.com/39754351/121908819-a1ff0800-cd2d-11eb-9942-3c7dc315b690.png)

1. Circular array

The string is present in Crowdin, but is not displayed in the GUI.
https://crowdin.com/translate/freecad/548/en-pl#6576932

2. Creates copies of the selected object, and places the copies in a radial pattern
creating various circular layers.

The array can be turned into an orthogonal or a polar array by changing its type.

The string is present in Crowdin, but is not displayed in the GUI.
https://crowdin.com/translate/freecad/548/en-pl#6586714

**Comment by Roy-043** [comment]
This should be fixed with: https://github.com/FreeCAD/FreeCAD/pull/5370.

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.27319 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 67706b1)
Hash: 67706b14df32b91b948952ea2c9350948ba4d4db
Python version: 3.9.10
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.3
Locale: Polish/Poland (pl_PL)
```

Solved.
It's a bit of a pity that hint pop-ups have been disabled in the menu.
