### ISSUE TITLE
Part design -> menu PartDesign / Shaft design wizard ...

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#4]
```
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.24992 (Git) AppImage
Build type: Release
Branch: master
Hash: 9332e52d944c1339e3b9a1b5a72dc6edc6d077a8
Python version: 3.9.4
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: Polish/Poland (pl_PL)
```
![obraz](https://user-images.githubusercontent.com/39754351/120902671-e1e53180-c641-11eb-935e-d95d9456decd.png)

1. no apply, cancel buttons
it is not possible to exit the tool with anything other than "ok"
2. no title for the tool window
3. no translation for options and information

**Comment by luzpaz** [comment]
Working on this in https://github.com/FreeCAD/FreeCAD/compare/master...luzpaz:crowdin/PD-WizardShaft

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.25541 (Git) AppImage
Build type: Release
Branch: master
Hash: ca043dcb6d20d70b8e24d75e810683214eecc5d4
Python version: 3.9.6
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: Polish/Poland (pl_PL)
```


Today I translated and imporoted a new thong from Crowdin, 

Length [mm] https://crowdin.com/translate/freecad/564/en-pl#6590131
Diameter [mm] https://crowdin.com/translate/freecad/564/en-pl#6590133
Inner diameter [mm] https://crowdin.com/translate/freecad/564/en-pl#6590135
Constraint type https://crowdin.com/translate/freecad/564/en-pl#6590137
Start edge type https://crowdin.com/translate/freecad/564/en-pl#6590139
Start edge size https://crowdin.com/translate/freecad/564/en-pl#6590141

But after running the program, the desired effect is not yet visible

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28793 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 5386d4e)
Hash: 5386d4ed864cd03edd026e1d3d128cccedf568df
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

After recent updates the problem still persists ...

![obraz](https://user-images.githubusercontent.com/39754351/167265223-675bd345-0c81-4b25-8ea7-d2ca13727494.png)

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28945 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0fb7cd9)
Hash: 0fb7cd9758d850f536d571cc094c9833fee18fff
Python 3.9.13, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

After recent updates the problem still persists ...

**Comment by kaktusus** [comment]
If there are as much problems with this feature as outlined in the forum please consider having it temporarily removed from the main release until all issues are resolved.

https://forum.freecadweb.org/viewtopic.php?style=4?f=19&t=69077&p=598807#p598807

**Comment by donovaly** [comment]
The shaft design wizard works now again: https://forum.freecadweb.org/viewtopic.php?style=4&p=599132#p599132

**Comment by chennes** [comment]
This wizard is sort of a mess from a translation point of view: in many cases the widget labels are actually directly passed along to FEM as the name of the constraint types, so we cannot translate them without breaking the wizard. Eventually this should be updated to that the displayed string is just cosmetic, and the underlying FEM constraint is stored alongside it.

**Comment by kaktusus** [comment]
the sooner this is fixed the better
;-)

**Comment by chennes** [comment]
There are only so many hours in the day -- I doubt this is making the top of anyone's priority list, even yours 😄 . With almost 80 other translation issues here, this one is going to be a while.

**Comment by kaktusus** [comment]
We have progress.

```
OS: Debian GNU/Linux 12 (bookworm) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33303 (Git) AppImage
Build type: Release
Branch: master
Hash: 5b075a9938b78076fdde9034de4a05685e42690e
Python 3.10.11, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
  * Curves 0.5.0
  * sheetmetal 0.2.56
  * Reinforcement
  * BIM 2021.12.0
  * Rocket 3.1.0
```

![image](https://github.com/FreeCAD/FreeCAD-translations/assets/39754351/806811cf-9457-4189-bb68-eedcbdd00a8f)

Translations are already visible.
Only the cancel button I wrote about in the first point is missing.
This option will allow you to leave the wizard without modifying the window with the model.

Chris thank you for your commitment and for taking the time to solve such cases. :medal_military: :medal_military: :medal_military:

**Comment by kaktusus** [comment]
Closing 
Translations have been fixed.
