### ISSUE TITLE
Draft → menu Utilities

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#40]
```
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.25065 (Git) AppImage
Build type: Release
Branch: master
Hash: 4de2ad46b2b9c78ac2721a0dbea7c19306261095
Python version: 3.9.4
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: Polish/Poland (pl_PL)
```

Utility label do not have translations in the GUI.

![obraz](https://user-images.githubusercontent.com/39754351/121911256-e7bcd000-cd2f-11eb-9d29-2da8eadc115b.png)

1. Create working plane proxy

The string is present in Crowdin, but is not displayed in the GUI.
https://crowdin.com/translate/freecad/548/en-pl#6586920

2. Move to group

The string is present in Crowdin, but is not displayed in the GUI.
https://crowdin.com/translate/freecad/548/en-pl#6586750

**Comment by Roy-043** [comment]
"Create working plane proxy": This was already fixed apparently.

"Move to group...": AFAICT the problem is not caused by the source code. The tooltip is translated. But the menu text is not.

OS: Windows 8.1 (6.3)
Word size of FreeCAD: 64-bit
Version: 0.20.26761 (Git)
Build type: Release
Python version: 3.8.12
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.3
Locale: Dutch/Netherlands (nl_NL)

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.26720 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 7bca26e)
Hash: 7bca26e7c14d4d43374ff7e0c8582735b249cbfd
Python version: 3.9.9
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.3
Locale: Polish/Poland (pl_PL)
```


![obraz](https://user-images.githubusercontent.com/39754351/148790304-b0433251-41c6-492f-8692-da12414139f7.png)



one repaired, one unrepaired and one new

`Add a new named group` - The string is present in Crowdin, but is not displayed in the GUI.
https://crowdin.com/translate/freecad/548/en-pl#6595069

**Comment by Roy-043** [comment]
`Add a new named group`
This issue was already fixed in the source code: https://github.com/FreeCAD/FreeCAD/pull/5301

`Move to group`
I do not know what is causing this. As already mentioned the source code seems OK.

**Comment by Roy-043** [comment]
PR https://github.com/FreeCAD/FreeCAD/pull/6814 should fix the translation of the "Move to group..." menu item. Of course the fix has to make a 'round-trip' via Crowding etc. So the final result may not make it into the V0.20 release.

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28793 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 5386d4e)
Hash: 5386d4ed864cd03edd026e1d3d128cccedf568df
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

All works as it should.

![obraz](https://user-images.githubusercontent.com/39754351/167263813-5af6adf1-ecf4-4e1d-b462-9d984038d72d.png)
