### ISSUE TITLE
Draft → Create working plane proxy (tool)

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#43]
```
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.25065 (Git) AppImage
Build type: Release
Branch: master
Hash: 4de2ad46b2b9c78ac2721a0dbea7c19306261095
Python version: 3.9.4
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: Polish/Poland (pl_PL)

```

Utility tooltip do not have translations in the GUI.
![obraz](https://user-images.githubusercontent.com/39754351/122070159-01c0e600-cdf6-11eb-930f-212f45e4e4df.png)

1. Creates a proxy object from the current working plane.
Once the object is created double click it in the tree view to restore the camera position and objects' visibilities.
Then you can use it to save a different camera position and objects' states any time you need.

String is in Crowdin.
https://crowdin.com/translate/freecad/548/en-pl#6586922

**Comment by Roy-043** [comment]
This was already fixed apparently.

**Comment by kaktusus** [comment]
Yes, translation works well.
