### ISSUE TITLE
Draft → Snap Dimensions (tool)

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#44]
```
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.25065 (Git) AppImage
Build type: Release
Branch: master
Hash: 4de2ad46b2b9c78ac2721a0dbea7c19306261095
Python version: 3.9.4
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: Polish/Poland (pl_PL)

```

Utility tooltip do not have translations in the GUI.

![obraz](https://user-images.githubusercontent.com/39754351/122072470-e35bea00-cdf7-11eb-83af-90ade5869fae.png)

1. Snap Dimensions

No text string in Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Snap%20Dimensions

**Comment by luzpaz** [comment]
cannot find this in the source code at all :confused:

**Comment by Roy-043** [comment]
https://github.com/FreeCAD/FreeCAD/pull/5370 should take care of this issue. But the PR  is just the first step. For the final result the string has to be published on Crowdin, translated and then merged with the source code.

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.27319 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 67706b1)
Hash: 67706b14df32b91b948952ea2c9350948ba4d4db
Python version: 3.9.10
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.3
Locale: Polish/Poland (pl_PL)
```

Solved.
