### ISSUE TITLE
Draft → All Draft Snap toolbar tools

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#45]
```
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.25065 (Git) AppImage
Build type: Release
Branch: master
Hash: 4de2ad46b2b9c78ac2721a0dbea7c19306261095
Python version: 3.9.4
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: Polish/Poland (pl_PL)
```
Utility tooltip do not have translations in the GUI.

![obraz](https://user-images.githubusercontent.com/39754351/122073793-fcb16600-cdf8-11eb-89c0-af857404fe1c.png)

1. Snap Lock
No string in Crowdin
https://crowdin.com/translate/freecad/548/en-pl?filter=basic&value=0#q=Snap%20lock

1. Snap Endpoint
No string in Crowdin
https://crowdin.com/translate/freecad/548/en-pl?filter=basic&value=0#q=Snap%20Endpoint

1. Snap Midpoint
No string in Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Snap%20Midpoint

2. Snap Center
No string in Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Snap%20Center

3. Snap Angle
No string in Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Snap%20Angle

4. Snap Intersection
No string in Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Snap%20Intersection

5. Snap Perpendicular
No string in Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Snap%20Perpendicular

6. Snap Extension
No string in Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Snap%20Extension

7. Snap Parallel
No string in Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Snap%20Parallel

8. Snap Special
No string in Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Snap%20Special

9. Snap Near
No string in Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Snap%20Near

10. Snap Ortho
No string in Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Snap%20Ortho

11. Snap Grid
No string in Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Snap%20Grid

12. Snap WorkingPlane
No string in Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Snap%20WorkingPlane

**Comment by Roy-043** [comment]
https://github.com/FreeCAD/FreeCAD/pull/5370 should take care of these issues. But the PR  is just the first step. For the final result the strings have to be published on Crowdin, translated and then merged with the source code.

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.27319 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 67706b1)
Hash: 67706b14df32b91b948952ea2c9350948ba4d4db
Python version: 3.9.10
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.3
Locale: Polish/Poland (pl_PL)
```

Solved.
