### ISSUE TITLE
TechDraw → Add Leaderline to View (tool)

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#46]
```
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.25065 (Git) AppImage
Build type: Release
Branch: master
Hash: 4de2ad46b2b9c78ac2721a0dbea7c19306261095
Python version: 3.9.4
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: Polish/Poland (pl_PL)
```

No translation for the Start Symbol combo box.

![obraz](https://user-images.githubusercontent.com/39754351/122243955-ce00c180-cec4-11eb-9fbb-573bb59307de.png)

Presented strings of text do not occur in Crowdin.

No translation for the End Symbol combo box.

![obraz](https://user-images.githubusercontent.com/39754351/122245153-c4c42480-cec5-11eb-8449-538fdab68f30.png)

Presented strings of text do not occur in Crowdin.

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28793 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 5386d4e)
Hash: 5386d4ed864cd03edd026e1d3d128cccedf568df
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

The problem still exists. I've highlighted another item so it doesn't get missed.

![obraz](https://user-images.githubusercontent.com/39754351/167263671-aff94819-2994-4d51-a438-4f248ab5e165.png)

**Comment by kaktusus** [comment]
> For now on, enum properties are not translatable. This needs a higher-level structure in FreeCAD's GUI


 @yorikvanhavre - here the Style checkbox has translated options.

![image](https://user-images.githubusercontent.com/39754351/168151629-fb3e28fe-30c8-409d-b313-c0fee4154584.png)


1.  `Pick points` - The string is in Crowdin.
    https://crowdin.com/translate/freecad/27911/en-pl#6576654

3.  `Save Points` - no string in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Save%20Points

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28884 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 51fdb42)
Hash: 51fdb42f21b4c6a7c9f91956e51427b896070f96
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

The function key label has a translation.
Fix https://github.com/FreeCAD/FreeCAD/pull/6883

**Comment by yorikvanhavre** [comment]
Indeed in the task panel, there we can translate things. Only in the properties editor, there it isn't possible. Need to check where this happens above, it might be fixable...

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28945 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0fb7cd9)
Hash: 0fb7cd9758d850f536d571cc094c9833fee18fff
Python 3.9.13, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```


After recent updates the problem still persists ...

**Comment by kaktusus** [comment]
fixed

Version: 0.21.0.33110 (Git) AppImage

![obraz](https://user-images.githubusercontent.com/39754351/236995784-6861a623-8f47-439e-a1a3-63fc9a0c0c41.png)
although the text is now compressed and becoming unreadable
it worked better before
