### ISSUE TITLE
TechDraw → undo, redo buttons (bug)

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#49]
```
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.25065 (Git) AppImage
Build type: Release
Branch: master
Hash: 4de2ad46b2b9c78ac2721a0dbea7c19306261095
Python version: 3.9.4
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: Polish/Poland (pl_PL)
```

I discovered a bug in the TechDraw module when using the undo & redo buttons. Observes the removal of a drawing from view, and the unexpected termination of the program. What information should I prepare for the problem demonstration?

**Comment by luzpaz** [comment]
Open a thread on the TechDraw subforum with

* What you were trying to do
* What you expected
* What actually happened

**Comment by luzpaz** [comment]
@kaktusus can you provide a screenshot of this issue of undo/redo ?

**Comment by kaktusus** [comment]
https://forum.freecadweb.org/viewtopic.php?style=4&f=35&t=59529

the link in the presented forum topic, contains a video with the demonstration of the problem

again: https://vimeo.com/564764403

**Comment by luzpaz** [comment]
@kaktusus is this still an issue?

**Comment by kaktusus** [comment]
I remember that there was a person willing to solve the problem and submitted a fix.
I have to check if his solution has been implemented.

**Comment by kaktusus** [comment]
The undo redo stack is working properly. There is no longer an undesirable effect of the whole model disappearing when undoing the last operation.

What remains to be solved is the inconvenience of the model disappearing when closing the "Add face axis" tool window with the cancel button.
I also noticed it at the same time.
I can make a separate ticket out of it.

**Comment by kaktusus** [comment]
Done.
https://forum.freecadweb.org/viewtopic.php?style=4&f=35&t=59529&p=594271#p594271
