### ISSUE TITLE
TechDraw → Insert Detail View (tool)

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#50]
```
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.25065 (Git) AppImage
Build type: Release
Branch: master
Hash: 4de2ad46b2b9c78ac2721a0dbea7c19306261095
Python version: 3.9.4
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: Polish/Poland (pl_PL)
```

No translation for the GUI.

![obraz](https://user-images.githubusercontent.com/39754351/122641133-97fd5080-d103-11eb-8bd5-bf3d215fa3ce.png)

1. Drag Highlight

String is in Crowdin.
https://crowdin.com/translate/freecad/27911/en-pl#6582112

2. Detail / Detail

No string is in Crowdin.
https://crowdin.com/translate/freecad/27911/en-pl?filter=basic&value=0#q=Detail

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28793 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 5386d4e)
Hash: 5386d4ed864cd03edd026e1d3d128cccedf568df
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

After recent updates the problem still persists ...

![obraz](https://user-images.githubusercontent.com/39754351/167263315-4175c710-08e0-459d-9038-b0b0a30c8440.png)

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28945 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0fb7cd9)
Hash: 0fb7cd9758d850f536d571cc094c9833fee18fff
Python 3.9.13, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```


After recent updates the problem still persists ...

**Comment by Kuzma30** [comment]
There is "Drag Highlight" TaskDetail.ui:95 which redefined in .cpp. Add ability to translate in .cpp file too.
