### ISSUE TITLE
FreeCAD → Tree view (panel) / Link actions

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#51]
```
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.25065 (Git) AppImage
Build type: Release
Branch: master
Hash: 4de2ad46b2b9c78ac2721a0dbea7c19306261095
Python version: 3.9.4
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: Polish/Poland (pl_PL)
```

No translation for the GUI.
![obraz](https://user-images.githubusercontent.com/39754351/122663539-764fa800-d19b-11eb-96ae-6188717168ee.png)

1. Link actions

String is in Crowdin.
https://crowdin.com/translate/freecad/549/en-pl#6577910

**Comment by kaktusus** [comment]
I also wrote about it here: [FreeCAD or Arch → Combo View (tree view) #16](url=https://github.com/FreeCAD/FreeCAD-translations/issues/16)

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28793 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 5386d4e)
Hash: 5386d4ed864cd03edd026e1d3d128cccedf568df
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

All works as it should.

![obraz](https://user-images.githubusercontent.com/39754351/167263080-d83900b9-af5c-411d-875d-e2cb45b4e6b3.png)

**Comment by Kuzma30** [comment]
![Знімок екрана з 2022-05-30 17-35-23](https://user-images.githubusercontent.com/1382812/171016055-607d97c4-6316-45da-b539-b7f9b7d81c88.png)
Fixed in menu but not in toolbar.

**Comment by kaktusus** [comment]
we have reported it separately https://github.com/FreeCAD/FreeCAD-translations/issues/72
