### ISSUE TITLE
Mesh part → Meshes (menu)

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#54]
```
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.25131 (Git) AppImage
Build type: Release
Branch: master
Hash: 7c519689f0d5ea78fb3292be36a857d283c05507
Python version: 3.9.5
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: Polish/Poland (pl_PL)
```

Utility label do not have translations in the GUI.

![obraz](https://user-images.githubusercontent.com/39754351/122964371-7dd3a480-d387-11eb-8aff-7750a9cbb771.png)

1. Cutting
No proper string in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Cutting

2. Unwarp mesh
No string in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Unwarp%20mesh

3. Unwarp Face
No string in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Unwarp%20Face

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.26375 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 8a6e3d1)
Hash: 8a6e3d1b766a34546806b22d750929c2d00e30a6
Python version: 3.9.7
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.3
Locale: Polish/Poland (pl_PL)
```
no change, issue still exists

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.26498 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 1895593)
Hash: 18955931c7f0926a4cd9d2719be5a433b49ae56e
Python version: 3.9.7
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.3
Locale: Polish/Poland (pl_PL)
```

New edition has been published, the issue still persists.

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28793 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 5386d4e)
Hash: 5386d4ed864cd03edd026e1d3d128cccedf568df
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

After recent updates the problem still persists ...

![obraz](https://user-images.githubusercontent.com/39754351/167262890-13afa982-c199-47da-8960-86a6894fa0e5.png)

but it's a little smaller ;-)

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28945 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0fb7cd9)
Hash: 0fb7cd9758d850f536d571cc094c9833fee18fff
Python 3.9.13, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```


After recent updates the problem still persists ...

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28993 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 6d92e53)
Hash: 6d92e532bcc31c99a0ab4c153ff00b6414b8f527
Python 3.9.13, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
```

the issue in point one has been fixed.

![obraz](https://user-images.githubusercontent.com/39754351/171991031-8dc41c1a-5073-440f-a551-a61f3a9a82e4.png)

**Comment by chennes** [comment]
I believe everything in this Issue has been resolved now: if something is still out there, let's make a new issue for it.

**Comment by kaktusus** [comment]
fixed

![image](https://user-images.githubusercontent.com/39754351/234043954-b4a5d591-e0f8-404b-aba6-5cf4617f3ef9.png)
