### ISSUE TITLE
Draft → Draft Statusbar

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#56]
```
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.25131 (Git) AppImage
Build type: Release
Branch: master
Hash: 7c519689f0d5ea78fb3292be36a857d283c05507
Python version: 3.9.5
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: Polish/Poland (pl_PL)
```
When the Draft workbench is loaded, a tiny toolbar is displayed in the status bar. 

![obraz](https://user-images.githubusercontent.com/39754351/124343500-34c3f180-dbcc-11eb-8786-879cf072cf36.png)

There are 5 tools available, one of which is a component.
Tools labels and tooltips do not have translations.

1.  `Toggles Grid On/Off`
![obraz](https://user-images.githubusercontent.com/39754351/124344027-54f5af80-dbd0-11eb-9b56-961f658daa4f.png)

The string is present in Crowdin, but is not displayed in the GUI.
https://crowdin.com/translate/freecad/548/en-pl#6586678

2. `Object snapping`
![obraz](https://user-images.githubusercontent.com/39754351/124344042-6fc82400-dbd0-11eb-9c0f-306c4b081e04.png)

The string is present in Crowdin, but is not displayed in the GUI.
https://crowdin.com/translate/freecad/548/en-pl#6586680

All popup labels for this component's tools have no translations.

3. `Toggles Visual Aid Dimensions On/Off`
![obraz](https://user-images.githubusercontent.com/39754351/124344048-7f476d00-dbd0-11eb-98f7-7274e6cd9cfd.png)

The string is present in Crowdin, but is not displayed in the GUI.
https://crowdin.com/translate/freecad/548/en-pl#6586682

4. `Toggles Ortho On/Off`
![obraz](https://user-images.githubusercontent.com/39754351/124344057-91c1a680-dbd0-11eb-8da1-f7078f85949f.png)

The string is present in Crowdin, but is not displayed in the GUI.
https://crowdin.com/translate/freecad/548/en-pl#6586684

5. `Toggles Constrain to Working Plane On/Off`
![obraz](https://user-images.githubusercontent.com/39754351/124344069-a4d47680-dbd0-11eb-8d0f-0c67e93c52b4.png)

The string is present in Crowdin, but is not displayed in the GUI.
https://crowdin.com/translate/freecad/548/en-pl#6586686

**Comment by luzpaz** [comment]
@carlopav can you confirm this issue ? :sweat_smile:

**Comment by carlopav** [comment]
@luzpaz thanks for the head up... I don't really know what I did wrong, but I can say that the tooltip was intended to be translated...

Anyway I'm not really satisfied about the the Draft Snap toolbar and of the Draft Snap widget and I wanted to change them to stadard toobars, cause I dont' really think we need them to be different from other toolbars (@yorikvanhavre what do you think?) but I encountered some problems with the statusbar Snap dropdown menu... 

https://forum.freecadweb.org/viewtopic.php?f=23&t=61715&p=530715#p530715

https://github.com/FreeCAD/FreeCAD/compare/master...carlopav:Draft_SnapToolbarToStandard?expand=1

**Comment by Roy-043** [comment]
The mentioned translation issue has been fixed with https://github.com/FreeCAD/FreeCAD/pull/5370.

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.27319 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 67706b1)
Hash: 67706b14df32b91b948952ea2c9350948ba4d4db
Python version: 3.9.10
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.3
Locale: Polish/Poland (pl_PL)
```

Solved.
