### ISSUE TITLE
Plot → main menu / Plot

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#60]
```
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.25645 (Git) AppImage
Build type: Release
Branch: master
Hash: 37d9757399b4c2ec30318eb88d7cd7c508246345
Python version: 3.9.7
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: Polish/Poland (pl_PL)
```
Plot label do not have translations in the GUI.

![obraz](https://user-images.githubusercontent.com/39754351/132554730-eae4f6b2-93cd-4f0c-ac94-495f23a28034.png)

The string is present in Crowdin, but is not displayed in the GUI.
https://crowdin.com/translate/freecad/27891/en-pl#6465939

However, I am not sure if I have found a good string.

**Comment by luzpaz** [comment]
@kaktusus I'm not certain this is an issue since we've removed Plot from master (partially). I'm CC-ing the [Plot workbench](https://github.com/FreeCAD/freecad.plot) dev to get more clarity on this. 

CC @sanguinariojoe

**Comment by luzpaz** [comment]
@sanguinariojoe ping

**Comment by luzpaz** [comment]
Ping @sanguinariojoe
