### ISSUE TITLE
FreeCAD global Crowdin duplicates option problem...

### ISSUE THREAD

**Issue by FreeCAD-Tools** [FreeCAD/FreeCAD-translations#61]
Properties headers: Axis, Position, Base is not presented in Crowdin site (from App::Property context)?

![изображение](https://user-images.githubusercontent.com/90561109/132991230-89a07761-d9ec-4176-9665-3e5626188bed.png)

But it presented in FreeCAD.ts.

```
<context>
    <name>App::Property</name>
    ....
    <message>
      <source>Axis</source>
      <translation>...</translation>
    </message>
    <message>
      <source>Position</source>
      <translation>...</translation>
    </message>
    <message>
      <source>Base</source>
      <translation>...</translation>
    </message>
  </context>
```

Perhaps this is due to some kind of collision.

For example, < source>Axis</source> is also available in Arch.ts. Perhaps due to the fact that these tags match, script used with Crowdin is ignore <source>Axis</source>,<source>Position</source> and <source>Base</source>.

This bug does not allow to make translations for these terms, as well as correct existing incorrect translations of this terms.

**Comment by FreeCAD-Tools** [comment]
To solve this problem, you need to disable the hiding duplicates option in the Crowdin project settings. But only project managers can do this.

**Comment by luzpaz** [comment]
That would potentially expose an overwhelming amount of strings to translation. Surely there must be a reasonable solution?

**Comment by FreeCAD-Tools** [comment]
"That would potentially expose an overwhelming amount of strings to translation. "

Well, yes, the strings that were hidden will now be available for translation. This seems to be normal...

Now there are a lot of values that cannot be translated. For example, "Draft"," Thickness " is probably about ~20-30 pcs. What about this, If these lines cannot be translated and corrected? Isn't it possible to make a backup of the translation *.ts files? In any case, this should be fixed. Since the number of unavailable strings will grow with each new update.

**Comment by FreeCAD-Tools** [comment]
Is there anything planned to solve this problem?

**Comment by chennes** [comment]
I think the real solution to the inadvertently-removed duplicates is to use the disambiguation string in Qt's translation system to ensure that the things that look like duplicates but aren't can be differentiated. I can't imagine that we want to globally disable hiding duplicated strings, that sounds like a real mess!

**Comment by FreeCAD-Tools** [comment]
> 
> 
>  I can't imagine that we want to globally disable hiding duplicated strings, that sounds like a real mess!

Why is this such a concern... what is the number of duplicates is now? Is this number known?

It seems to me that the main source of duplicates is commands.

**Comment by FreeCAD-Tools** [comment]
If to be more precise the commands are the root of ~850 duplicates:

```
for wb in Gui.listWorkbenches():
   Gui.activateWorkbench(wb)

print(len(Gui.Command.listAll())-len(Gui.listWorkbenches()))
```

**Comment by chennes** [comment]
It seems like we have a path forward to solve the Command duplication issue, so let's get that done, then see if we can figure out how many duplicates remain.

**Comment by FreeCAD-Tools** [comment]
> use the disambiguation string

I think we not need disambiguation string when this Crowdin setting is hide duplicates with differnt contexts.
Which is a bit strange. I think Crowdin detects duplicates by <source></source> string.

**Comment by kaktusus** [comment]
@FreeCAD-Tools 
I think this ticket can be closed now
Crowdin configuration has been adjusted.
