### ISSUE TITLE
FreeCAD → View → Standard views → "Axonometric" is not presented in Crowdin

### ISSUE THREAD

**Issue by FreeCAD-Tools** [FreeCAD/FreeCAD-translations#63]
FreeCAD → View → Standard views → "Axonometric" is not presented in Crowdin for translate.

![изображение](https://user-images.githubusercontent.com/90561109/132991800-cf65ce46-ca49-4951-8468-9f7578542032.png)

**Comment by luzpaz** [comment]
@FreeCAD-Tools please confirm manually or wait till the next crowdin push (next Sunday) and let us know if this is fixed for you. Thanks for reporting
