### ISSUE TITLE
Part → Part menu

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#64]
```
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.25645 (Git) AppImage
Build type: Release
Branch: master
Hash: 37d9757399b4c2ec30318eb88d7cd7c508246345
Python version: 3.9.7
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: Polish/Poland (pl_PL)
```

FC main menu, Part submenu

![obraz](https://user-images.githubusercontent.com/39754351/133841162-25d25de6-1a79-4a19-bba2-afa2f6cac1e4.png)

1.  `Create points object from mesh` -  no string in Crowdin
 https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Create%20points%20object%20from%20mesh

2. `Create a copy` -  no string in Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Create%20a%20copy

3. `Create projection on surface` -  no string in Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Create%20projection%20on%20surface

4. `Attachment...` -   There is a string in Crowdin, no translation in the GUI
https://crowdin.com/translate/freecad/563/en-pl#6513114

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.25943 (Git) AppImage
Build type: Release
Branch: master
Hash: a65464b722a846bd2999aa2fecdff1132b15b297
Python version: 3.9.7
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: Polish/Poland (pl_PL)
```


items 1 and 3 are displayed correctly

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28945 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0fb7cd9)
Hash: 0fb7cd9758d850f536d571cc094c9833fee18fff
Python 3.9.13, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```


![obraz](https://user-images.githubusercontent.com/39754351/170877627-1981f8a4-3890-4475-a737-a7d07f909b36.png)

**Comment by Kuzma30** [comment]
@channes can you review this commit too ;)?

**Comment by kaktusus** [comment]
![image](https://user-images.githubusercontent.com/39754351/174496803-49823e34-7cb1-4b7c-95f4-c61f7a493c9b.png)

is ok
