### ISSUE TITLE
Tech Draw → Group Projection. Projections Names.

### ISSUE THREAD

**Issue by FreeCAD-Tools** [FreeCAD/FreeCAD-translations#71]
![изображение](https://user-images.githubusercontent.com/90561109/133885410-f57dd22c-8832-4449-83f9-da3b6aa915b4.png)

Presumably they are located here...

https://github.com/FreeCAD/FreeCAD/blob/5d49bf78de785a536f941f1a6d06d432582a95d3/src/Mod/TechDraw/App/DrawProjGroupItem.cpp

Specified as enum... Will the workbench work normally if you translate these names?

**Comment by kaktusus** [comment]
These are just internal labels, not visible on the printout

**Comment by FreeCAD-Tools** [comment]
I known, but it's still better when they are translated into the user's language.

**Comment by luzpaz** [comment]
@chennes recently showed me the alternative way to expose strings that are in enums to translations (but not actually doing within the enum block). I can't find that ATM

**Comment by chennes** [comment]
I don't recall what technique I showed you, but I'd probably make a map and use it as a lookup table, so something like:
```
std::map<std::string, std::string> enumToDisplayTextMap;
enumToDisplayTextMap["Front"] = tr("Whatever","Front");
enumToDisplayTextMap["Back"] = tr("Whatever","Back");
// etc...

**Comment by chennes** [comment]
I am not sure where the actual rendered text string is being created for this one, I'm going to see if WandererFan can give me an assist.

**Comment by WandererFan** [comment]
The text is just the item's Label.  It is assigned in:
App::DocumentObject* DrawProjGroup::addProjection(const char* viewProjType)

The "rendering" happens here:
void QGIView::drawBorder()

**Comment by chennes** [comment]
Awesome, thanks. I think the right strategy here is to leave the label's text alone, and just use `QT_TRANSLATE_NOOP` to add it to the translation database at point-of-creation, and then do the translation only at the last moment, here:
```
    QString labelStr = QString::fromUtf8(getViewObject()->Label.getValue());
```
https://github.com/FreeCAD/FreeCAD/blob/f5eccb11a1fc997ba1c51f8715e681788de6fef5/src/Mod/TechDraw/Gui/QGIView.cpp#L460

See any issues with that strategy?
