### ISSUE TITLE
PartDesign → Map sketch to face... (tool)

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#73]
```
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.25645 (Git) AppImage
Build type: Release
Branch: master
Hash: 37d9757399b4c2ec30318eb88d7cd7c508246345
Python version: 3.9.7
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: Polish/Poland (pl_PL)
```

Some labels displayed in the tool window do not have translations in the GUI.

![obraz](https://user-images.githubusercontent.com/39754351/133890337-5a44259f-3c9b-4f0b-8518-d84d4c52aa90.png)

1. `inertialCS` - no string in Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=inertialCS

2. `Deactivated` - the string is present in Crowdin, but is not displayed in the GUI.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Deactivated

3. `FlatFace` - no string in Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=FlatFace

4. `ObjectXZ`` - no string in Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=ObjectXZ

5. `ObjectYX` - no string in Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=ObjectYX

6. `ObjectYZ` - no string in Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=ObjectYZ

**Comment by kaktusus** [comment]
![obraz](https://user-images.githubusercontent.com/39754351/152687254-68138820-304c-48aa-82f9-9a22ab86c15e.png)


Untranslated error message.
the string is present in Crowdin.
https://crowdin.com/translate/freecad/569/en-pl#6584992

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28793 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 5386d4e)
Hash: 5386d4ed864cd03edd026e1d3d128cccedf568df
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

After recent updates the problem still persists ...

![obraz](https://user-images.githubusercontent.com/39754351/167261731-7ec7e170-3da5-48bc-b332-461f53b5d9fc.png)

**Comment by chennes** [comment]
I think that the actual string creation for insertion into the menu is being done here: https://github.com/FreeCAD/FreeCAD/blob/bfb3efbc72a2b562a5ed7a0696e4a72f563bfd2b/src/Mod/Sketcher/Gui/Command.cpp#L587

It is not actually using the AttacherTexts.cpp functions, and I believe should be, but we need to verify that there isn't any string comparison happening to determine what the user actually selected. If there is, we have to attach some extra data to each entry.

**Comment by kaktusus** [comment]
fixed

Version: 0.21.0.33110 (Git) AppImage
