### ISSUE TITLE
[Renaming] TechDraw → Preferences → General Tab → Projection Group Angle (ComboBox)

### ISSUE THREAD

**Issue by FreeCAD-Tools** [FreeCAD/FreeCAD-translations#77]
![изображение](https://user-images.githubusercontent.com/90561109/133906138-5ee99bca-420c-4a5f-a32a-b7d813ede238.png)

I suggest replacing (There is a place for a long text is defined):
First -> First-angle projection (ISO Europe/GOST)
Third -> Third-angle projection (American ASME)
Page -> I do not know what this means at all, needs to add some meaning...

Link to more info:
https://en.wikipedia.org/wiki/Multiview_orthographic_projection

**Comment by kaktusus** [comment]
The problem has been solved, you can close the ticket.

![image](https://user-images.githubusercontent.com/39754351/168879107-0798554d-63a3-46cb-a240-78a67c768b25.png)
