### ISSUE TITLE
Part Design → main menu / View / Toolbars

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#8]
```
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.24992 (Git) AppImage
Build type: Release
Branch: master
Hash: 9332e52d944c1339e3b9a1b5a72dc6edc6d077a8
Python version: 3.9.4
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: Polish/Poland (pl_PL)
```
![obraz](https://user-images.githubusercontent.com/39754351/120915999-29ea6f80-c6a7-11eb-92e2-6211d4ca1be4.png)

**1.** no GUI translation, there is a corresponding string in Crowdin _(I guess)_
https://crowdin.com/translate/freecad/549/en-pl#6502997
**2.** no string in Crowdin
![obraz](https://user-images.githubusercontent.com/39754351/120916082-b7c65a80-c6a7-11eb-8325-ff58e753a6dd.png)
**3.** no string in Crowdin
![obraz](https://user-images.githubusercontent.com/39754351/120916103-e5130880-c6a7-11eb-8b2d-0507bf1c1f9c.png)
**4.** no GUI translation, no string in Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=measure

**Comment by kaktusus** [comment]
a second item on the same menu: "Workbench"
no GUI translation, I don't know which string in Crowdin is the right one
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Workbench

**Comment by luzpaz** [comment]
This should be tested again once @yorikvanhavre push/pulls crowdin again

**Comment by kaktusus** [comment]
> This should be tested again once @yorikvanhavre push/pulls crowdin again

Do you know when it's scheduled for?

**Comment by kaktusus** [comment]
Issues 2, 3, 4 have been resolved
![obraz](https://user-images.githubusercontent.com/39754351/123294559-4266e080-d515-11eb-89b1-ab77fb73ddd5.png)
the second item of this submenu remains to be solved, I have not reported it before

**Comment by luzpaz** [comment]
I have no idea why `Structure` is not getting translated.

**Comment by kaktusus** [comment]
Crowdin contains two "structure" strings with the hidden attribute
https://crowdin.com/translate/freecad/549/en-pl#6502997
https://crowdin.com/translate/freecad/549/en-pl#6503000

maybe one of them corresponds to this option in the menu.
I don't know if the hidden string is exported to FC.

**Comment by luzpaz** [comment]
OK, I've made them both visible in crowdin

**Comment by kaktusus** [comment]
The problem was not solved.
I have just imported the translation file after the changes.

**Comment by luzpaz** [comment]
I guess I can  brute force add it to the `Workbench.cpp` file and see if that solves it?

**Comment by kaktusus** [comment]
This may be necessary, same as for 'Part Design Helper', and 'Part Design Modeling'.

I also think the situation is analogous with the 'Workbench' toolbar name translation not working. I also mentioned this.

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.25541 (Git) AppImage
Build type: Release
Branch: master
Hash: ca043dcb6d20d70b8e24d75e810683214eecc5d4
Python version: 3.9.6
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: Polish/Poland (pl_PL)
```


reported problems numbered: 2, 3, 4 have been fixed

**Comment by kaktusus** [comment]
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28793 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 5386d4e)
Hash: 5386d4ed864cd03edd026e1d3d128cccedf568df
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...

After recent updates the problem still persists ...

![obraz](https://user-images.githubusercontent.com/39754351/167265118-e973ea92-c0df-45c1-9bbc-3f94cbdc27bd.png)

but a little smaller ;-)

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28945 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0fb7cd9)
Hash: 0fb7cd9758d850f536d571cc094c9833fee18fff
Python 3.9.13, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

![obraz](https://user-images.githubusercontent.com/39754351/170880118-5edb6b0e-a63a-4705-8080-8a6cb634cd5d.png)

**Comment by kaktusus** [comment]
Well I lived to see it ....
;-)

is ok
