### ISSUE TITLE
FEM → Thermal Constraints

### ISSUE THREAD

**Issue by FreeCAD-Tools** [FreeCAD/FreeCAD-translations#80]
The FEM workbench has a lot of missed translations.

![изображение](https://user-images.githubusercontent.com/90561109/134230861-8abc7e86-24c7-436b-a5b2-16ae99764d66.png)

![изображение](https://user-images.githubusercontent.com/90561109/134231076-1b48daac-ea16-4478-8d9c-ee4bc9f140e9.png)

![изображение](https://user-images.githubusercontent.com/90561109/134231118-e0ac1bc1-5c90-4c5c-8b07-1939dc43468c.png)

And menu:

![изображение](https://user-images.githubusercontent.com/90561109/134231279-b94bdb89-e491-4a08-85a9-7ac3928151fe.png)

**Comment by luzpaz** [comment]
@FreeCAD-Tools please add full [About](https://wiki.freecadweb.org/About) info 

CC @berndhahnebach

**Comment by FreeCAD-Tools** [comment]
FreeCAD_0.20.25645_Win-LPv12.5.4_vc17.x-x86-64

OS: Windows 10 Version 1909
Word size of FreeCAD: 64-bit
Version: 0.20.25645 (Git)
Build type: Release
Branch: master
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0

**Comment by FreeCAD-Tools** [comment]
It is possible that the Fem. ts in Crowdin is not updated or is not correct.

**Comment by luzpaz** [comment]
@FreeCAD-Tools please retest

**Comment by kaktusus** [comment]
fixed, can be closed
