### ISSUE TITLE
 SpreadSheet → main menu /  Spreadsheet

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#81]
```
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.25844 (Git) AppImage
Build type: Release
Branch: master
Hash: 1b20118dfa3fb9f127f0e4fb122701f7fcdaa9fc
Python version: 3.9.7
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: Polish/Poland (pl_PL)
```
 SpreadSheet label do not have translations in the GUI.

![obraz](https://user-images.githubusercontent.com/39754351/135477794-54304977-1e1c-423e-81f7-62951b01a742.png)

I think the right string is missing from Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=%20SpreadSheet

**Comment by FreeCAD-Tools** [comment]
It will take a lot of effort to translate this line. At the beginning, you will need to remove repetitions in the spreadsheet code and on other desktops. Then you will need to cancel the duplicate hiding mode. In short, it's a half-year job.

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28793 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 5386d4e)
Hash: 5386d4ed864cd03edd026e1d3d128cccedf568df
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

All works as it should.

![obraz](https://user-images.githubusercontent.com/39754351/167250023-5a37c7fb-f357-45d2-a2de-489df56c23b2.png)
