### ISSUE TITLE
Drop down menu translations only show after changing translations language twice

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-translations#87]
Tracking this ticket here even though this is not a translation content issue. There are some anomalies in Qt translation system or how FC implements them.

### Bug
1. Start FreeCAD
2. Switch to PartDesign
3. `Preferences` -> `General` + change lang to Polish
4. Observe: the dropdown menu still in English
5. Go back to `Preferences` -> `General` + change to English
6. Observe: dropdown menu is now in Polish

```
OS: Manjaro Linux (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.26155 (Git) AppImage
Build type: Release
Branch: master
Hash: 0926a4148bcff11249fd4f56bc30256102ffe105
Python version: 3.9.7
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.3
Locale: English/United States (en_US)
```

**Comment by kaktusus** [comment]
@luzpaz I propose to close this topic.
in the following topic 0penBrain wrote that the issue can not be reproduce - probably does not occur?
https://github.com/FreeCAD/FreeCAD/issues/6704#issuecomment-1272268537
