### ISSUE TITLE
FreeCAD → Edit → Preferences ... / General / General / Preference Packs

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#89]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.26238 AppImage
Build type: Release
Branch: (HEAD detached at 237229c)
Hash: 237229c3fc8df1ddede445d3495a0ac640d63e4f
Python version: 3.9.7
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.3
Locale: Polish/Poland (pl_PL)
```

FreeCAD has a new option, whose labels do not have translations in the GUI

![obraz](https://user-images.githubusercontent.com/39754351/141244612-ff7ec906-d269-4ece-b5d9-b86e0870775c.png)

1.  `Preference Packs` - no string in Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Preference%20Packs

2.  `Preference Pack Name` - no string in Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Preference%20Pack%20Name

3.  `Tags` - no string in Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Tags

4.  `Apply` - the string from Crowdin does not apply to this case
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Apply

5.  `Save New...` - no string in Crowdin
(https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Save%20New...)

**Comment by luzpaz** [comment]
CC @chennes

**Comment by chennes** [comment]
Thanks! I'll get that fixed up shortly.

**Comment by chennes** [comment]
(ETA: I see I don't have the appropriate permissions to edit this issue. Can someone who does assign it to me?)

**Comment by chennes** [comment]
It's all being set to translate in the code, so it may just be that we need to push a new `lupdate` run to CrowdIn. @yorikvanhavre ?

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28793 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 5386d4e)
Hash: 5386d4ed864cd03edd026e1d3d128cccedf568df
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

All works as it should.

![obraz](https://user-images.githubusercontent.com/39754351/167249768-82559876-c23d-4827-a06c-f2a0513e72a2.png)
