### ISSUE TITLE
Part Design →  Part Design Modeling Toolbar / Create a mirrored feature

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#9]
```
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.24992 (Git) AppImage
Build type: Release
Branch: master
Hash: 9332e52d944c1339e3b9a1b5a72dc6edc6d077a8
Python version: 3.9.4
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: Polish/Poland (pl_PL)
```
![obraz](https://user-images.githubusercontent.com/39754351/120928259-350fc080-c6e4-11eb-801e-b39f3f0b0cb5.png)

1. cancel button has no translation
2. no GUI translation, no string in Crowdin
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=mirrored%20parameters

it also applies to other transformation tools. 
![obraz](https://user-images.githubusercontent.com/39754351/120928561-6b9a0b00-c6e5-11eb-9bb8-92d7dc2efd1b.png)

**Comment by Kuzma30** [comment]
![Знімок екрана з 2022-05-05 09-28-48](https://user-images.githubusercontent.com/1382812/166872595-2afd3485-82a3-442b-8a3f-4d6157c3f004.png)

Made on test crowdin server after apply https://github.com/FreeCAD/FreeCAD/pull/6822 
 and update .ts with last version of updatets.py

**Comment by kaktusus** [comment]
same as in #24

**Comment by kaktusus** [comment]
![image](https://user-images.githubusercontent.com/39754351/168030182-b7837211-5593-43ea-ba6e-91ed60594d86.png)

The solution to point 1. can be found here:
https://github.com/FreeCAD/FreeCAD/issues/6875#issuecomment-1124619639

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28945 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0fb7cd9)
Hash: 0fb7cd9758d850f536d571cc094c9833fee18fff
Python 3.9.13, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```


Fixed.

![obraz](https://user-images.githubusercontent.com/39754351/170879910-01ba7549-0965-459f-9c3d-5f277494f858.png)
