### ISSUE TITLE
FEM → View (menu) → Toolbars

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#90]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.26306 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 6701788)
Hash: 670178869ecdca52f7dcd332c513cb0c82b25cce
Python version: 3.9.7
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.3
Locale: Polish/Poland (pl_PL)
```

The first issue related to problems in the GUI translation, in the FEM Workbench _(which I' m reporting)_.
All dedicated toolbar labels do not have translations displayed in the GUI.

![obraz](https://user-images.githubusercontent.com/39754351/141326657-8e8ec126-d322-4fb2-9ba6-128694f9b35a.png)

1.  `Model`  - the string from Crowdin does not apply to this case
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Model
2.  `Electrostatic Constraints`  - no string in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Electrostatic%20Constraints
3. `Fluid Constraints`  - no string in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Fluid%20Constraints
4. `Geometrical Constraints`  - no string in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Geometrical%20Constraints
5. `Mechanical Constraints`  - no string in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Mechanical%20Constraints
6.  `Thermal Constraints`  - no string in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Thermal%20Constraints
7. `Mesh`  - the string from Crowdin does not apply to this case.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Mesh
8. `Solve`  - the string from Crowdin does not apply to this case.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Solve
9. `Results`  - the string from Crowdin does not apply to this case.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Results
10. `Utilities`  - the string from Crowdin does not apply to this case.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Utilities

**Comment by luzpaz** [comment]
Weird thing is that they look correct in the source https://github.com/FreeCAD/FreeCAD/blob/a545fb6741b8421e88d187adb5bcb5d36e4b972c/src/Mod/Fem/Gui/Workbench.cpp#L41-L71 so by deduction...they aren't being picked up by the translation script? 
CC @yorikvanhavre @berndhahnebach @chennes

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.26306 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 6701788)
Hash: 670178869ecdca52f7dcd332c513cb0c82b25cce
Python version: 3.9.7
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.3
Locale: Polish/Poland (pl_PL)
```


Solved after new import into Crowdin.
