### ISSUE TITLE
FEM → Model (menu)

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#92]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.26306 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 6701788)
Hash: 670178869ecdca52f7dcd332c513cb0c82b25cce
Python version: 3.9.7
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.3
Locale: Polish/Poland (pl_PL)
```

Sub menu labels do not have translations in the GUI.

![obraz](https://user-images.githubusercontent.com/39754351/141333754-446aa0b8-5ca6-4c12-a8c3-39d9d8b74904.png)

1.  `Materials`  - the string from Crowdin does not apply to this case
https://crowdin.com/translate/freecad/559/en-pl#6498611
2.  `Element Geometry`  - no string in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Element%20Geometry
3. `Electrostatic Constraints`  - no string in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Electrostatic%20Constraints
4. `Fluid Constraints`  - no string in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Fluid%20Constraints
5. `Geometrical Constraints`  - no string in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Geometrical%20Constraints
6.  `Mechanical Constraints`  - no string in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Mechanical%20Constraints
7. `Thermal Constraints`  - no string in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Thermal%20Constraints
8. `Constraints without solver`   - no string in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Constraints%20without%20solver
9. `Overwrite Constants`   - no string in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Overwrite%20Constants

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.26306 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 6701788)
Hash: 670178869ecdca52f7dcd332c513cb0c82b25cce
Python version: 3.9.7
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.3
Locale: Polish/Poland (pl_PL)
```


Solved after new import into Crowdin.

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28810 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 6f5a5a2)
Hash: 6f5a5a2019c586db63650713de860d3e810739d4
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```


Something's broken

![obraz](https://user-images.githubusercontent.com/39754351/167543787-c5906375-de9a-47ac-a810-0da77b2584cd.png)


it worked properly before.

1.  `Analysis container` - no string in Crowdin.
    https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=analysis%20container

The same applies to the translation of utility labels in each sub-menu.
The same goes for the other FEM menus.

 8-O

I'm guessing the source code doesn't meet the relevant standards, and translation strings are skipped during selection.

Do I need to prepare detailed submissions?

**Comment by kaktusus** [comment]
A very large number of toolbar tools also lack translations.

This looks really bad.
I think I opened a pandora's box.

**Comment by luzpaz** [comment]
![facepalm-really](https://user-images.githubusercontent.com/4140247/167741269-ed63d5fe-adc1-4f5b-8a2f-29e7742b2fa5.gif)
