### ISSUE TITLE
FEM → Solve (menu)

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#94]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.26306 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 6701788)
Hash: 670178869ecdca52f7dcd332c513cb0c82b25cce
Python version: 3.9.7
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.3
Locale: Polish/Poland (pl_PL)
```

Utility labels do not have translations in the GUI.

![obraz](https://user-images.githubusercontent.com/39754351/141343394-6e3836a0-a155-4ad1-9d41-ebfcde53f43f.png)

1.  `Solver CalculiX Standard`  - the string from Crowdin does not apply to this case
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Solver%20CalculiX%20Standard

2.  `Solver CalculiX (new framework)`  - no string in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Solver%20calculix%20(new%20framework)

3.  `Solver Mystran`  - no string in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Solver%20Mystran

4.  `Solver Z88`  - the string from Crowdin does not apply to this case
https://crowdin.com/translate/freecad/559/en-pl#6500097

5.  `Electricforce equation`  - no string in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Electricforce%20equation

6.  `Flux equation`  - no string in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Flux%20equation

7.  `Heat equation`  - no string in Crowdin.
https://crowdin.com/translate/freecad/all/en-pl?filter=basic&value=0#q=Heat%20equation

**Comment by kaktusus** [comment]
all but item 2 solved ...

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28793 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 5386d4e)
Hash: 5386d4ed864cd03edd026e1d3d128cccedf568df
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

Something is broken the whole menu has no translations, the right strings are missing in Crowdin.

![obraz](https://user-images.githubusercontent.com/39754351/167250789-5fd7bbe5-9573-4387-9bad-247b4bf2241b.png)

**Comment by luzpaz** [comment]
:boom:  All translations under solver are gone ([thread](https://forum.freecadweb.org/viewtopic.php?f=18&t=68729))

**Comment by kaktusus** [comment]
Yes, we know that

https://github.com/FreeCAD/FreeCAD-translations/issues/92#issuecomment-1121933466

**Comment by Kuzma30** [comment]
https://github.com/Kuzma30/FreeCAD/blob/4e5cef18df3e1be99f1e60439185ee3bec909b40/src/Mod/Fem/Gui/Resources/translations/Fem.ts#L600

I use same upsatets.py 
You can check other strings.

**Comment by kaktusus** [comment]
huh  - all the strings from Crowdin got thrown out, almost the whole module has no translations ...
something broke after last script changes and import to Crowdin

**Comment by luzpaz** [comment]
@yorikvanhavre ☝️

**Comment by Kuzma30** [comment]
@luzpaz Just test one string from list, it now on crowdin server. Need wait for upload from crowdin to github and check (final on-release update). I think most of the issues will be closed.

**Comment by kaktusus** [comment]
Exactly, as I whined last time (I think on the forum)
once the string export from Crowdin is done a lot of the missing stuff will disappear. Including the current backlog.

AppImage is released every two days, it's a shame there are no strings updated on a regular basis.

**Comment by luzpaz** [comment]
I hear you. I think we can really tackle auto-translation updates very very soon, thank you for your patience so far y'all! 

We also have [nightly Snap package](https://github.com/FreeCAD/FreeCAD-snap), we can test them on or we can use the scripts that have been made for translators to test themselves. But definitely, i see a lot more translation updates going in to master in this next development cycle. It's going to be a goal of mine to help realize, but I'll need help and count on ya'll to continue the rally and pace you've been keeping :wink: 

Thanks again for all the hard work!

**Comment by yorikvanhavre** [comment]
Latest strings pushed with 1e034cc47f

**Comment by kaktusus** [comment]
This is very good news, I will tell other people about it.

**Comment by kaktusus** [comment]
o!!! you have already written about it in the forum.
;-D

**Comment by kaktusus** [comment]
```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28945 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0fb7cd9)
Hash: 0fb7cd9758d850f536d571cc094c9833fee18fff
Python 3.9.13, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```


Item 2 has not been fixed

![obraz](https://user-images.githubusercontent.com/39754351/170876087-9e07ec82-8760-4eb1-9784-5b9c2c43eebd.png)

https://crowdin.com/translate/freecad/559/en-pl#6599096

**Comment by kaktusus** [comment]
fixed

Version: 0.21.0.33303 (Git) AppImage
